### ISSUE TITLE
pinned and not pinned columns- scrolling problem

### ISSUE THREAD

**Issue by arikanos** [ceolter/angular-grid#101]
![bildschirmfoto 2015-04-27 um 14 21 27](https://cloud.githubusercontent.com/assets/11754462/7347547/e885b3da-ece9-11e4-8c75-78b7479abbe4.png)
on my mac with safari 8.0.5 the columns do not scroll synconiously. as known the pinned column can't be scrolled, the unpinned column scrolls as expected, but the pinned one does not "go with the scroll". 
on firefox, everything is as expected. I am getting this behavior just with safari.

**Comment by ceolter** [comment]
this is very strange, nobody else has reported this, given lots of safari users, i'm surprised. it's working for me on safari on windows. anyone else seeing this behavior?

btw - what version are you using? latest release (1.4) or latest from master? (there were some changes in this area just yesterday after the release was done)

**Comment by arikanos** [comment]
i am using the latest from master (1.5-SS). the problem is just with this version. in the latest release (1.4) the scrolling works as expected=)

**Comment by ceolter** [comment]
i've just fixed this and checked in. an improvement we introduced doesn't work on all browsers. latest in master has it working again.

**Comment by ceolter** [comment]
trouble merging . . . 5 min

**Comment by ceolter** [comment]
ok fix is in now
