### ISSUE TITLE
Server Side Sort

### ISSUE THREAD

**Issue by ccollie** [ceolter/angular-grid#102]
Just a ping :-) I'd prefer to use angular-grid instead of ui-grid, but this is an absolute must-have.

**Comment by ceolter** [comment]
what's your time frame? and can you do the sorting outside the table as a workaroun while your waiting? (eg put a select (drop down) outside the grid with the columns you can sort by, that your datasoruce uses) . . . just as a temporary solution?

**Comment by ccollie** [comment]
Timeframe is more or less immediate (the length of a sprint). And unfortunately external controls won't match user expectations/ui guidelines. If there were a way to access column sort information through the api, i could use that info in a datasource.

**Comment by ceolter** [comment]
oh - i've an idea - you could provide your own header renderer? so don't use the sorting from the grid at all. then just code it up yourself?

**Comment by ccollie** [comment]
I was thinking of that as a workaround, except using some jQuery hackery.
Another idea is to have sort based events which are emitted when a header is clicked. We can then explicitly redraw on a header clicked event.

**Comment by ceolter** [comment]
yea your idea will work also, but you will still need to render the sort icon, so am thinking header renderer is better option.

**Comment by Jamunadevi-Vijayan** [comment]
Can we get a sample code for this
