### ISSUE TITLE
How to set Grid column width by Percentage value?

### ISSUE THREAD

**Issue by ShwetShah** [ceolter/angular-grid#105]
How can I set grid column width for AngularGrid with percentage value ??
this is how I am trying to set but not working.

$scope.gridOptions = {
columnDefs:{
cellStyle: {width: "50%"}
}
}

Thanks in advance

**Comment by ceolter** [comment]
Hi there, you cant use % for widths, only pixel widths. Not sure why you would want to to do this, maybe explain why you want this? PS This is a question, not an issue with the grid, so am closing the issue :) Any followup - can you put on the bulletin board please? thanks again!!
