### ISSUE TITLE
How to?- Column headers show title in two rows, when title to long 

### ISSUE THREAD

**Issue by arikanos** [ceolter/angular-grid#106]
How can i get this working? 
my problem is, that i load the titles of the headers from my server and some titles are short and others are long. when the title is to long the grid does not display the title at all. it just adds "..." at the end. is there a way to make the grid show the title in two or more lines? 
it should also update the column-header when i resize it...
 i thought about using headerCellRenderer... is that the right way?

thx.

**Comment by ceolter** [comment]
this is not an issue, it's a question!!!! best place for questions is the bulletin board :) so i'll close this issue off!!

to get the grid to show the header in two or more lies, yes you should use a header cell renderer. in this you can return back a div, and inside the div, have whatever structure you want. you will also need to set the head height (in grid options) so whatever height makes sense for you.

with regards updating the header when you resize, there is no callback for that, so you will have to have your header dynamically fit the available space.
