### ISSUE TITLE
"wheel" scrolling doesn't work when over pinned columns

### ISSUE THREAD

**Issue by sfescape** [ceolter/angular-grid#108]
When your mouse is over unpinned columns scrolling with the mouse wheel works as expected, if you move the mouse over a pinned column it stops working. You can see this by testing a mouse wheel with the pinning example in the documentation.

**Comment by ceolter** [comment]
thanks for raising. this is a dupe :)
https://github.com/ceolter/angular-grid/issues/14

**Comment by thisisbinod** [comment]
I just noticed this today. As the issue #14 and this one have been closed, does that mean there won't be any scrolling on the pinned columns? 
BTW, thank you for creating such an awesome grid!

**Comment by ceolter** [comment]
#14 is open!!
