### ISSUE TITLE
Pagination Footer Says: '1 to 0 of 0'and 'Page 1 of 0'

### ISSUE THREAD

**Issue by Skinner927** [ceolter/angular-grid#113]
Firstly, thanks for the amazing grid, here's my issue:
I'm using pagination and when I use a datastore whilst doing outside filtering I do this to apply the filter:
```
$scope.gridOptions.datasource.rowCount = -1;
$scope.gridOptions.api.onNewDatasource();
```

Then the datasource's `getRows` function runs. 

If it's a bad filter combination, no results will return from the DB.
I set `datasource.rowCount = 0` and I'm not sure if I should call for a success or failure.

If I do `callbackSuccess(data, start + data.length);` I get the odd issue of the footer saying `1 to 0 of 0` and `Page 1 of 0` with the option to advanced to the next page, then clicking back puts you on a negative page; this doesn't look too hot.

But if I instead call `callbackFail()`, the `1 to 0 of 0` goes away and the page count now says `Page 1 of many` which lets the user advance to the next page (of which there is none but it's still allowed).

What might I be missing to prevent these odd 'features' from happening or is this just how it is for the moment?

**Comment by ceolter** [comment]
Thanks for raising. Will fix when back from hols.

**Comment by ceolter** [comment]
fixed in the branch 'selection' . . . . will be merging into master in the next few days.

now, when no rows, call: callbackSuccess([], 0)
ie pass in empty array (empty rows for this page) and zero (for last row index)
