### ISSUE TITLE
groupKeys takes up only simple field values?

### ISSUE THREAD

**Issue by vivektodi** [ceolter/angular-grid#114]
I found that groupKeys takes up only values which are simple field values.

But when I use the `cellRenderer` property to render my columns say, 
`{displayName: "Party Name", cellRenderer: function (params) {
			var rowData = params.data;
			return rowData.party.name;
		},width: 150}`  and want to perform grouping, I can't.

**Comment by ceolter** [comment]
Fair point. Will improve to group on enbedded values, or maybe I create a 'getGroupKey' callback for maximum flexibility.

**Comment by cgat** [comment]
I'd love to see this supported as well. Any current work arounds? All I can think of is mapping the nested property to a first level property.

**Comment by ceolter** [comment]
no workarounds, unless you want to hack it. :(

**Comment by vivektodi** [comment]
Can I use grouping when I make use of Value Getters?

**Comment by ceolter** [comment]
Not yet, it's on my 'to do' list.

**Comment by ceolter** [comment]
fixed in master. will be in next release.

**Comment by cgat** [comment]
@ceolter I'm assuming this change should be in the latest release, yes?  I can't figure out how it's done, event after looking at your commit. Documentation doesn't suggest this is possible. To be clear, I want to group by embedded properties.

**Comment by ceolter** [comment]
it's done using valueGetters. put a valueGetter on the col you want to group by, have the valueGetter return the value for the group.

**Comment by cgat** [comment]
This is what I actually tried after reviewing your source code. I use 'groupColumnDef' to define the group column. In that definition, I set the valueGetter to return the value for the group. 

The first problem I see here is that grouping isn't done if groupKeys isn't set to some non-empty array, so the valueGetter never gets called (I've verified this with a debug breakpoint). If groupKeys is set with some value(s), then these will be used for grouping.

The second problem is that, even if the valueGetter function in the column definition did work, I don't feel this is the best place defining how things are group. To use the olympic athlete example, consider that the athlete objects have their country defined in an embedded property (e.g. 'address.country').  I want to group by 'address.country', but when the group is expanded, I want the athlete name to be shown. The column definition is responsible for the value shown in the column, which in this case is the field 'name', but hypothetically could use a valueGetter with a function that concatenates firstName and lastName. In this case, the valueGetter of the group column is a separate issue to how the groups are formed.

**Comment by ceolter** [comment]
> The first problem I see here is that grouping isn't done if groupKeys isn't set to some non-empty array, so the valueGetter never gets called (I've verified this with a debug breakpoint). If groupKeys is set with some value(s), then these will be used for grouping.

Slight misunderstanding i think. The groupKeys should have the id of the column (the column will use the field for the ID if it's provided). so use the valueGetter in the col, but also provide a field (or a colid directly) for the col and put this id in the groupKeys array.

>  I don't feel this is the best place defining how things are group.....

Hide the column you are grouping on. Don't show it.

So either in your gridOptions set:
groupHidePivotColumns=true;

Or mark the column explicitly as:
myColDef.hide = true;

**Comment by outofgamut** [comment]
It looks like this fix only resolved grouping by columns with valueGetters. Is there an open issue for not being able to group by columns with cellrenderers?

**Comment by ceolter** [comment]
no. cellrenderers should not be used.

cellRenderers are for the rendering process, drawing on the screen.

the grouping operation is a stage that takes place before the cells are rendered.
