### ISSUE TITLE
when dontUseScrolls and groupUseEntireRow are enabled, the grid does not render correctly

### ISSUE THREAD

**Issue by jcomet** [ceolter/angular-grid#115]
When dontUseScrolls: true  and groupUseEntireRow: true the grid does not render correctly.  It shows the group header, but the regular rows are not shown.

**Comment by ceolter** [comment]
Thanks for raising. Will look into when back from hols.

**Comment by ceolter** [comment]
fixed in branch 'selection' . . . will be merging into master in the next few days.

the fix was i removed "position: absolute" from .ag-group-cell-entire-row and .ag-footer-cell-entire-row
