### ISSUE TITLE
Links in Group Aggregate Rows still toggle collapse

### ISSUE THREAD

**Issue by JimmyBoh** [ceolter/angular-grid#116]
By default clicking in the first column of a table with group aggregates causes that group to either expand or collapse depending on the current state. When I add `a` or `button` tags to it I cannot click the elements without preventing the expand/collapse. [Here is a working example.](http://jsfiddle.net/dbhwkygx/2/)

I tried to `return false;`, `$event.stopPropagation();`, but neither worked.

Is there a way to stop it bubbling up? Can we implement an option to limit the grid to only allow the icon to toggle the collapsed state?

**Comment by ceolter** [comment]
My plan is to change the implementation, so groups require double click to expand if you don't click directly on the expand button (like how folders work in windows xp file browser).

**Comment by ceolter** [comment]
This should be working now, because the groups no require double-click to be expanded.

**Comment by JimmyBoh** [comment]
Very cool, thanks!
