### ISSUE TITLE
About tree with angular.

### ISSUE THREAD

**Issue by ohohco** [ceolter/angular-grid#117]
First, a great job! Congratulations!
There is nothing good about tree with angular. I find in angular-grid, it has tree now. I hope author will support a powerfull tree with angluar like angular-grid!

**Comment by ceolter** [comment]
Just use angular grid!!! Have one column (for the tree) and set header size
to 0px and its a tree!!! I am doing exactly that in one of my projects and
works great.

**Comment by ohohco** [comment]
Great ! Thanks a log, I am going to have a try.

**Comment by ohohco** [comment]
will it be support with drag & drop?

**Comment by ceolter** [comment]
Afraid not.

For now,  you will need to implement yourself by proving a drop target in a
custom cell renderer.
