### ISSUE TITLE
Checkboxes displayed by checkboxSelection attribute are not editable

### ISSUE THREAD

**Issue by franciscopuyo** [ceolter/angular-grid#118]
Hi,
When you set checkboxSelection as a columnDef attribute it displays a checkbox for each row. That's fine.
The problem is that if I want to change the checkbox image and so I have to make a css trick using the checkbox label but it can't be added or related to the checkbox.

I saw the angularGrid.js code and made something like that 

In this section:
```
if (colDef.checkboxSelection) {
        var eCheckbox = this.selectionRendererFactory.createSelectionCheckbox(node, rowIndex);
        eCellWrapper.appendChild(eCheckbox);
        
/* I added this code */

       var label = this.selectionRendererFactory.createLabelForCheckbox(node, rowIndex);
        eCellWrapper.appendChild(label);
/**************************/
}
```

In the file I added this function 
```
    SelectionRendererFactory.prototype.createLabelForCheckbox = function(node, rowIndex) {
        var label = document.createElement('label');
       var labelFor = rowIndex + 'row-checkbox';
        label.htmlFor = labelFor;

        label.onclick = function(event) {
            event.stopPropagation();
        };

        return label;
    };
```
In this function:
```
SelectionRendererFactory.prototype.createSelectionCheckbox = function(node, rowIndex) {
    var eCheckbox = document.createElement('input');
    eCheckbox.type = "checkbox";
    eCheckbox.name = "name";
    eCheckbox.className = 'ag-selection-checkbox';
    setCheckboxState(eCheckbox, this.selectionController.isNodeSelected(node));
 
/* I added this code */

    var labelFor = rowIndex + 'row-checkbox';
    eCheckbox.id = labelFor;

/***************************/
    var that = this;
    eCheckbox.onclick = function(event) {
        event.stopPropagation();
    };

    eCheckbox.onchange = function() {
        var newValue = eCheckbox.checked;
        if (newValue) {
            that.selectionController.selectIndex(rowIndex, true);
        } else {
            that.selectionController.deselectIndex(rowIndex);
        }
    };

    this.angularGrid.addVirtualRowListener(rowIndex, {
        rowSelected: function(selected) {
            setCheckboxState(eCheckbox, selected);
        },
        rowRemoved: function() {}
    });
    return eCheckbox;
};
```

I think that it would be enough.

Anyhow, to be clearer I attach the thing I want to do:

http://webdesign.tutsplus.com/tutorials/quick-tip-easy-css3-checkboxes-and-radio-buttons--webdesign-8953

Really thanks

Francisco

**Comment by ceolter** [comment]
hi - what you want to do can be done, you just need to NOT use the default checkbox selection!!!!

what you should do is create your own cell renderer, and have whatever type of selection mechanism you want, using the grid API for doing the selecting.

eg something like (i didn't test this, just typing into github, so might have a method name wrong or something):
colDef.cellRenderer = function(params) {
var div = document.createElement('div');
div.innerHTML = "<button>Select</button> and some text!!!";
div.querySelector('button').addListener('click', function() {
  params.api.selectIndex(params.index, true);
});
return div;
}

**Comment by franciscopuyo** [comment]
Thanks a lot, it was very useful. It's working now

**Comment by haifahrul** [comment]
Hi @franciscopuyo 

I try this and it's work, my be help :

    var columnDefs = [
      {
        headerName: 'Refunded', 
        field: 'refunded',
        editable: true,
        cellEditor: 'booleanEditor',
        cellRenderer: booleanCellRenderer
      },
    ];


**Function checkbox editor**

    function getBooleanEditor() {
        // function to act as a class
        function BooleanEditor() {}
        
        // gets called once before the renderer is used
        BooleanEditor.prototype.init = function(params) {
            // create the cell
            var value = params.value;

            this.eInput = document.createElement('input');
            this.eInput.type = 'checkbox'; 
            this.eInput.checked = value;
            this.eInput.value = value;
        };

        // gets called once when grid ready to insert the element
        BooleanEditor.prototype.getGui = function() {
            return this.eInput;
        };

        // focus and select can be done after the gui is attached
        BooleanEditor.prototype.afterGuiAttached = function() {
            this.eInput.focus();
            this.eInput.select();
        };

        // returns the new value after editing
        BooleanEditor.prototype.getValue = function() {
            return this.eInput.checked;
        };

        // any cleanup we need to be done here
        BooleanEditor.prototype.destroy = function() {
            // but this example is simple, no cleanup, we could
            // even leave this method out as it's optional
        };

        // if true, then this editor will appear in a popup
        BooleanEditor.prototype.isPopup = function() {
            // and we could leave this method out also, false is the default
            return false;
        };
        
        return BooleanEditor;
    }

**And then booleanCellRenderer function**

    function booleanCellRenderer(params) {
        var value = params.value ? 'checked' : 'unchecked';
        
        return '<input disabled type="checkbox" '+ value +'/>';
    }


**Let the grid know which columns and what data to use**

    var gridOptions = {
        columnDefs: columnDefs,
        pagination: true,
        defaultColDef: {
            filter: true,
            resizable: true,
        },
        onGridReady: function(params) {
            params.api.sizeColumnsToFit();
        },
        onCellValueChanged: function(event) {
            if (event.newValue != event.oldValue) { 
                // do stuff
                // such hit your API update
                event.data.refunded = event.newValue; // Update value of field refunded
            }
        },
        components:{
            booleanCellRenderer: booleanCellRenderer,
            booleanEditor: getBooleanEditor()
        }
    };

**Setup the grid after the page has finished loading**    

    document.addEventListener('DOMContentLoaded', function() {
        var gridDiv = document.querySelector('#myGrid');
        // create the grid passing in the div to use together with the columns & data we want to use
        new agGrid.Grid(gridDiv, gridOptions);
        
        fetch('$urlGetData').then(function(response) {
            return response.json();
        }).then(function(data) {
            gridOptions.api.setRowData(data);
        })
    });
