### ISSUE TITLE
Autosize columns to fit available grid width

### ISSUE THREAD

**Issue by pinnacleag-dev** [ceolter/angular-grid#120]
I would like the ability to have the sizeColumnsToFit (or a gridOptions option to do automatically on grid init) to have the grid only consider those columns that have a width defined to make up the left over space.

For instance, col1 is 200px wide, col2 is not set, col3 is set to 150px and the grid has 1000px in overall width.  Upon calling sizeColumnsToFit, or a new function, say consumeUnusedColumnWidth(), col2 will be updated to be 650px.

**Comment by ruratnayake** [comment]
yes... nice to have functionality. i too had a such requirement.

**Comment by ceolter** [comment]
in latest release. Fixed width cols for 'size to fit' - add 'suppressSizeToFit' to column definition to have the column width not change during the 'size to fit' operation.
