### ISSUE TITLE
Table sizing and alignment

### ISSUE THREAD

**Issue by xenit-raven** [ceolter/angular-grid#122]
Hey,

I'm trying to implement this grid in my page. This JSFiddle shows the roughly the layout I'm using: http://jsfiddle.net/9b5gnjf1/8/

I would like to make the grid fit within the page. Right now it's overflowing md-content. Also the cell content should be aligned vertically in the center. Does anyone know how I could style the grid like this?

**Comment by ceolter** [comment]
for cell content, use the cell styling as outlined in the docs.

for fitting the grid, are you trying to do something like the demo, ie have it fill width and height, but leave a gap on the top for a header panel???

ps going to close this as it's not an issue, it's a question, it should be on the web bulletin page!!
