### ISSUE TITLE
Quick Filter Does Not Support Value Getter

### ISSUE THREAD

**Issue by Skinner927** [ceolter/angular-grid#123]
If a column definition has a `valueGetter` defined, it is not included when evaluating `gridOptions.quickFilterText`. 

See the fiddle for an example: https://jsfiddle.net/p6n7nojf/

**Comment by Skinner927** [comment]
From what I can tell, the issue is in the `InMemoryRowController.prototype.aggregateRowForQuickFilter`. It doesn't take into account columns that use `newValueHander`.

https://github.com/ceolter/angular-grid/blob/2f400e063b6c25caa6d8a44891e2c2514c44a006/src/js/inMemoryRowController.js#L419

I'd create a PR but I don't currently understand the code base well enough.

**Comment by ceolter** [comment]
yup, something i haven't gotten around to. the value getters should be used here when creating the quick filter text.

**Comment by steezeburger** [comment]
Any sort of hacked fix for this? Or even a suggestion on how I might start making this happen?

**Comment by ceolter** [comment]
i just checked in a fix. i didn't test it at all - i just saw your comment looking for a hack fix, so i check in a hack fix :)

class: InMemoryRowController
method: aggregateRowForQuickFilter

i haven't done a build, so to get this fix, take latest from trunk and build

**Comment by steezeburger** [comment]
After building, it seemed to crash the grid. The API is no longer available. Also, opening the new angularGrid.js crashes Sublime for some reason. I tried both regular and minified versions, but neither worked.

Thanks for your insanely quick reply btw.

**Comment by ceolter** [comment]
i just gave it a quick once over, and is working for me. maybe something specific to your setup. can you tell me the error you are getting?

**Comment by steezeburger** [comment]
I started over from step one this morning and was able to get it to work. Not sure what I did differently. Thanks for the awesome support man.
