### ISSUE TITLE
ag-body padding-top not applied in Firefox 31.0

### ISSUE THREAD

**Issue by psalaberria002** [ceolter/angular-grid#124]
The table header does not appear in Firefox. padding-top for ag-body is never applied.

![captura de pantalla 2015-05-11 a las 12 07 54](https://cloud.githubusercontent.com/assets/2410564/7562734/00b8b446-f7d7-11e4-8dcc-5fbf298d1c8f.png)

**Comment by ceolter** [comment]
it's working in 37.0.2

i don't have different versions of ff installed - so in the spirit of open source, i'm hoping someone can tell me what's wrong and how to fix it!

**Comment by ruratnayake** [comment]
@psalaberria002 in which version of fire fox you got this issue ?

**Comment by ceolter** [comment]
ok i think i know what the problem might of been - i was setting the style with 'padding-top' where it should be 'paddingTop'.

i've check the change in - but i can't test it. can someone test where this was an issue?
either grab the latest, or in your code, search for 'padding-top' and 'padding-bottom' and replace with 'paddingTop' and 'paddingBottom'

thanks,

**Comment by ceolter** [comment]
i believe this is now working.
