### ISSUE TITLE
Unexpected behavior of group headers.

### ISSUE THREAD

**Issue by vivektodi** [ceolter/angular-grid#129]
The group header section says

>open: The column is only shown when the group is open.
>closed: The column is only shown when the group is closed.
>everything else:Any other value, including null and undefined, the column is always shown.

Regarding incompatible sets it says,

>If a group has a 'incompatible' set of columns, then the group opening / closing will not be activated. An incompatible set is one which will have no columns visible at some point (ie all are set to 'open' or 'closed').

Now if I have three columns in a group header, 2 being set to `groupShow: "open"` and 1 being set to `groupShow: "always"` _meaning I want it to be always shown_ the group opening / closing should be activated right?

Have I understood it correctly?

**Comment by ceolter** [comment]
yes that's right.

however you don't need to set 'always', this is the default if you don't specify 'open' or 'closed'

**Comment by vivektodi** [comment]
Here's my columnDefs

```	var columnDefs = [
		{displayName: "Party Name", field: 'name', group: "Order Details", width: 150, filter: "string",checkboxSelection: true},
	    {displayName: "Order Id", field: 'orderId', group: "Order Details", width: 90},
	    {displayName: "Order Date", field: 'salesOrderDate', group: "Order Details", groupShow: "open",  width: 90},
	    {displayName: "Product Group", group: "Item Details", groupShow: "open",  field: 'prodGroupName', width: 120},
	    {displayName: "Product Cat No.", group: "Item Details", field:'productCatlgNo', width: 120},
	    {displayName: "Description", group: "Item Details", groupShow: "open",  field: 'description', width: 120},
	    {displayName: "Item Type", group: "Item Details", groupShow: "open", field: "itemType", width: 100},
	    {displayName: "Current Stock", group: "Item Details", field: "currentStock", width: 100},
	    {displayName: "Order Qty", field:'quantity', width: 100},
	    {displayName: "Pending Qty", field: 'pendingQuantity', width: 100},
	    {displayName: "Item Value", cellRenderer: function (params) {
	    	var rowData = params.data;
	    	return rowData.quantity * rowData.rate * (1 - rowData.discount/100)
	    },  width: 90},
	    {displayName: "Order Value", field: 'grandTotal', filter:"number", width: 90},
	    {displayName: "Due Date", field: "dueOn", width: 100},
	    {displayName: "Delay", cellRenderer: function (params) {
	    	var rowData = params.data;
	    	var pendingDays = moment(rowData.dueOn).diff(moment(), 'days');	    	
	    	return pendingDays;
	    }, width: 70}

	];
```

And here's my gridOptions

```	$scope.gridOptions = {
	    columnDefs: columnDefs,
	    dontUseScrolls: false,
	    groupHeaders: true,
	    enableColResize: true,
	    enableSorting: true,
	    enableFilter: true,
	    rowSelection: 'multiple',
	    groupCheckboxSelection: 'children',
	    groupSelection: true,
	    
	    
	};
```


The group headers show up, but the close / open don't seem to work here. Where am I making a mistake? Here's the screenshot to help.

![screen shot 2015-05-13 at 7 36 10 pm](https://cloud.githubusercontent.com/assets/1806863/7612283/5d62b5e4-f9a7-11e4-8aa8-417fe650849e.png)

**Comment by ceolter** [comment]
I don't know,  it looks good to me  :(

Can you give a jsfiddle?

**Comment by vivektodi** [comment]
Alright, fixed it!

Wasn't using the latest version. 

My bad, Sorry about it!
