### ISSUE TITLE
Filters don't work on CellRenderer things.

### ISSUE THREAD

**Issue by vivektodi** [ceolter/angular-grid#130]
Just like group keys.

Filters don't seem to work on the columns which have a `cellRenderer` instead of simple `field` value.

**Comment by ceolter** [comment]
cell renderers should be for formatting only (ie creating complex html). so the renderer shouldn't be part of the filtering.

if you want to filter a value not based on field, you should be using valueGetters, which do work with filtering.

**Comment by zweeen** [comment]
@ceolter  I think the api changed since 2015.

@vivektodi you should use [filterValueGetter](https://www.ag-grid.com/javascript-grid-value-getters/) because `valueGetters` work only ig you want to format the value for display.
