### ISSUE TITLE
[FEAT] Custom child groupKeys

### ISSUE THREAD

**Issue by axelnormand** [ceolter/angular-grid#132]
Thanks for creating such a great directive. Starting to use it quite extensively now.

We are looking to add custom grouping when certain key values are rendered and was wondering how you might recommend we implement the following (happy to fork the code)

The following diagram explains what i mean more

```
Region (Grouped)			|	Population (aggregated)
--------------------------------------------------------------------------------------------------------
- Europe						742,500,000
	- Germany					80,000,00
		- Berlin				8,000,000
			- Mitte				100,000
			- Spandau			200,000
			...
    - UK						60,000,000  
		+ North		
		- South
			- London        	5,000,000		
				- Camden		200,000
				- Highgate		100,000	
				...       
		+ East
		+ West

	- France					80,000,00
		- Paris					8,000,000
			- Louvre			100,000
			- Bourse			200,000
			...
		
- Asia

```

The groupKeys is initially [Continent, Country, City] and the final leaf is a District

However when the Country value "UK" is hit we'd like to specify different groupKeys for its children. In this case we add in "Quarter" (North/South/East/West). ie groupKeys for the children of UK is ["Quarter", "City"] rather than just ["City"]

So ideally we'd like to specify these group key overrides in a list something like
```
groupKeyOverrides = 
[
	{ 
		key: "Country", 
		value: "UK" 
		childGroupKeys: ["Quarter", "City"]	
	},
]
```

For reference a District row object might be 
```
{ 
	District: "Bourse",
	City: "Paris",
	Country: "France",
	Quarter: "North",
	Continent: "Europe",
	Population: 200000
}
```

Any thoughts very helpful
Many thanks.

**Comment by ceolter** [comment]
The built in grouping feature is intended to be used as is. If you want more specific grouping functionality, then that's where you would have to create the groups yourself. This is what the FileBrowser demo does. My plan was, provide a quick and easy 'default' grouping feature, but for anything more bespoke, you would have to implement it yourself. I don't want to extend what's currently there as I have plans to extend that in another direction, in particular I'll be introducing 'slice and diece' features, which will only work when the dimensions are common accorss the entire dataset (in your case, the dimensions are district, city, country etc).

PS as this isn't an issue with the gird (it's a questions!!) I'm closing this issue. Thanks :)

**Comment by axelnormand** [comment]
All understood and thanks for reply. Sorry if this was not the best platform to ask a question.
Excited to see upcoming slice and dice features.
Thanks again.

**Comment by axelnormand** [comment]
Quick question. Can this tree structure aggregate the data for me or should i do that myself?

**Comment by ceolter** [comment]
You have to do it yourself!!

**Comment by axelnormand** [comment]
:) Thought as much, just checking, sorry.
Right on to write it all.
