### ISSUE TITLE
Grouped but hidden row

### ISSUE THREAD

**Issue by JimmyBoh** [ceolter/angular-grid#139]
I'd like to be able to manually hide a row from displaying. Or specify that it should never be displayed, just included in the data for the `groupAggFunction`.

I slapped a `hidden` class (`display:none;`) on the row but that just makes it invisible, the other rows do not fill in the negative space. Is it possible to hide certain rows, other than just not including them when I call `setDataSource`?

----
_Why I ask:_
The reason behind this is to allow aggregate group row without children. I have data (`bank` can have many `branches`, where everything has a `name`, `address`, `city`, etc.) that is stored as a hierarchy/parent-child. Some `banks` do not have physical `branches`, but they should still be shown, just with no children. My idea is to add the `bank` along side of the `branches` but then just hide that row, so the `bank` group aggregate is displayed even when there are no real `branches`.

**Comment by JimmyBoh** [comment]
Also looks like #111 might solve what I'm trying to do, but this might be easier.

**Comment by ceolter** [comment]
what you could do is group the data yourself, and give the grid grouped data. this is what the file explorer does.

**Comment by dbubs** [comment]
Hi @ceolter,
I am trying to do the same thing. I'm curious about your suggestion to manually group the data before passing it to the grid. If I use lodash `groupBy` there is no key for the group name, so I'm not sure what I would define in the `groupKeys` array.

If lodash `groupBy` outputs data like this:
```
var food = {
  "Fruits": [
    {"name": "Apple", "color": "red"},
    {"name": "Banana", "color": "yellow"}
  ],
  "Vegetables": [
    {"name": "Carrot", "color": "orange"},
    {"name": "Cucumber", "color": "green"}
  ]
}

$scope.gridOptions = {
	rowData: food,
	columnDefs: [
		{
			displayName: 'Name',
			cellRenderer: function(params) {
				return params.data.name; //  how would I get access to name?
			}
		},
		{
			displayName: 'Color',
			cellRenderer: function(params) {
				return params.data.color; //  how would I get access to color?
			}
		}
	],
	groupKeys: [] // What would go here?
};
```

**Comment by JimmyBoh** [comment]
@ceolter That's right, I couldn't remember where I saw that in the documentation.

@dbubs It looks like it needs to follow a particular structure, see the snippet below or the javascrpit code for the file explorer for more info.

From the file explorer example:

    var rowData = [
        {
            group: true,
            expanded: true,
            data: {name: 'C:'},
            children: [
                {group: true,
                    data: {name: 'Windows', size: '', type: 'File Folder', dateModified: '27/02/2014 04:12'},
                    children: [
                        {group: false, data: {name: 'bfsve.exe', size: '56 kb', type: 'Application', dateModified: '13/03/2014 10:14'}},
                        {group: false, data: {name: 'csup.txt', size: '1 kb', type: 'Text Document', dateModified: '27/11/2012 04:12'}},
                        {group: false, data: {name: 'diagwrn.xml', size: '21 kb', type: 'XML File', dateModified: '18/03/2014 00:56'}}
                    ]
                },
                {group: true,
                    data: {name: 'Program Files', size: '', type: 'File Folder', dateModified: '11/09/2013 02:11'},
                    expanded: true,
                    children: [
                        {group: true,
                            data: {name: 'ASUS', size: '', type: 'File Folder', dateModified: '13/03/2014 1014'},
                            children: [
                                {group: false, data: {name: 'bfsve.exe', size: '56 kb', type: 'Application', dateModified: '13/03/2014 10:14'}},
                                {group: false, data: {name: 'csup.txt', size: '1 kb', type: 'Text Document', dateModified: '27/11/2012 04:12'}},
                                {group: false, data: {name: 'diagwrn.xml', size: '21 kb', type: 'XML File', dateModified: '18/03/2014 00:56'}}
                            ]
                        },

**Comment by ceolter** [comment]
@JimmyBoh exactly . . . . you need to have it in that node structure, which is specific to the grid. i plan on making this easier to created, and better documented, in the future . . . .
@dbubs  . . . . if you are passing in grouped data, then you don't need to specify groupKeys, leave that attribute out of the grid  options. as JimmyBoh suggests, best look at the code in the File Browser example.

**Comment by dbubs** [comment]
@JimmyBoh, @ceolter Many thanks for your replies! I will look at the File Browser example.
