### ISSUE TITLE
Scroll on pinned columns

### ISSUE THREAD

**Issue by dejanberic** [ceolter/angular-grid#14]
Mouse wheel does not scroll table when mouse is above pinned columns.

**Comment by ceolter** [comment]
I don't think this is possible to fix with the design (would be delighted if anyone can disagree - and let me know how to do it if I'm wrong). The scrolling window is on the main body only (does not include the pinned columns). The only way to get 'scroll' events from the pinned columns or the header (eg mouse wheel or touch-screen drag), would be to make these panels scrollable also - but doing so, in the browsers, introduces scroll-bars, which looks wrong (would mean two sets of scrollbars).

**Comment by dejanberic** [comment]
I think if you add listener mousewheel to ePinnedColsViewport you can simulate scrolling.

**Comment by ceolter** [comment]
sounds like a plan, i'll give it a shot

**Comment by danseid** [comment]
@ceolter the example in #31 uses jquery [scroll](https://api.jquery.com/scroll/) event and [scrollTop](https://api.jquery.com/scrollTop/) to enable pinned columns scrolling. Not sure it is a performant solution though.

**Comment by ceolter** [comment]
Cool, thanks for passing on.

**Comment by amcdnl** [comment]
This has the craziest scrolling example of pinned columns I've seen - http://handsontable.com/demo/column_freeze.html

**Comment by simedw** [comment]
Hi @danseid, 
While not perfect this seems to do the trick, might want to make it optional :)
I went for hard coded pixel amount since I couldn't figure out a good way to calculate the line/page height needed for DOM_DELTA_LINE/DOM_DELTA_PAGE across different browsers [0]
```javascript
this.ePinnedColsViewport.addEventListener("wheel", function (evt : any) {        
    var scrollTopMax = that.eBodyViewport.scrollHeight - that.eBodyViewport.clientHeight;
    var scrollAmountPx = 0;                                                      
                                                                                 
    if(evt.deltaY < 0) {                                                         
        scrollAmountPx = -40;                                                    
    } else if(evt.deltaY > 0) {                                                  
        scrollAmountPx = 40;                                                     
    }                                                                            
    var newTopPosition = lastTopPosition + scrollAmountPx;                       
                                                                                 
    if(newTopPosition < 0) {                                                     
        newTopPosition = 0;                                                      
    }                                                                            
                                                                                 
    if(newTopPosition > scrollTopMax) {                                          
        newTopPosition = scrollTopMax;                                           
    }                                                                            
                                                                                 
    if(newTopPosition != lastTopPosition) {                                      
        that.scrollPinned(newTopPosition);                                       
        that.eBodyViewport.scrollTop = newTopPosition;                           
        that.requestDrawVirtualRows();                                           
        lastTopPosition = newTopPosition;                                        
                                                                                 
        evt.preventDefault();                                                    
    }                                                                            
});
```

[0] https://developer.mozilla.org/en-US/docs/Web/Events/wheel
