### ISSUE TITLE
Allow cell template to be retrieved from $templateCache

### ISSUE THREAD

**Issue by daric81** [ceolter/angular-grid#141]
Hi,
Just a feature request.
It would be great if the TemplateService tried the $templateCache when requesting the template. This is something ng-grid handled and would be handy as we use grunt-angular-templates for caching views.

**Comment by ceolter** [comment]
is there anything except a performance benefit? i'm slow to use any Angular feature that is not of great benefit, as I plan on also supporting Angular 2 and other frameworks - currently the grid can exists outside any framework - so limiting exposure to Angular is good for the grid.

**Comment by daric81** [comment]
Its purely for performance. Its a fair standpoint you make regarding angular features. Our grunt strips .html file extension when naming templates in the cache. I guess we could alter the grunt process, or alternatively allowing the override of the Template Service implementation might be nice.  We currently use ng-grid and its not performing too well for us so are trialling swapping it out.

**Comment by ceolter** [comment]
what about not using templates? i only put that in to ease peoples journey away from ng-grid. however, in my applications using Angular Grid, I simply don't use them. your grid will work much faster if you don't use templates. I'm going to close this request if you don't mind, I don't think I'll be making a code change :)

**Comment by dinoboff** [comment]
With Angular 1.4 and ag-grid 1.14.1 I have to monkey patch TemplateService:

```
someModule.run([
    '$window',
    '$templateRequest',
    '$log',
    function($window, $templateRequest, $log) {
      $window.awk.grid.TemplateService = TemplateService;

      function TemplateService() {
        this.templateCache = {};
        this.requestPromises = {};
      }

      TemplateService.prototype.init = function($scope) {
        this.$scope = $scope;
      };

      // returns the template if it is loaded, or null if it is not loaded
      // but will call the callback when it is loaded
      TemplateService.prototype.getTemplate = function(url, callback) {
        var templateFromCache = this.templateCache[url];

        if (templateFromCache) {
          return templateFromCache;
        }

        var promise = this.requestPromises[url];
        var self = this;

        if (!promise) {
          promise = this.requestPromises[url] = $templateRequest(url, false).then(function(tmpl) {
            self.templateCache[url] = tmpl;
          }).catch(function(err) {
            $log.warn('Unable to get template error ' + err.status + ' - ' + url);
          }).finally(function() {
            self.requestPromises[url] = undefined;
          });
        }

        promise.then(function() {
          callback();
        });

        // caller needs to wait for template to load, so return null
        return null;
      };

    }
  ]);
```

It will be nice to have an option to properly overwrite it.
