### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by khoshbin** [ceolter/angular-grid#142]
Hi there!
  Congratiulations! it is really great.Does it support Right to left layout? It looks like it has some problems.

Thanks

**Comment by ceolter** [comment]
RTL is a css feature. Apply at the CSS level to get it working. Either the cell CSS, or create (or edit an existing) theme.

**Comment by MhosenBiglari** [comment]
[look at this](https://stackoverflow.com/questions/53921749/ag-grid-headers-move-to-the-opposite-direction-upon-horizontal-scroll/56027707#56027707)
