### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by m4urer** [ceolter/angular-grid#154]
Are you planning on supporting internationalization?
Right now, the only problem I see is the search template... it's hardcoded in english:
```javascript
var template = [
...
    '        <input class="ag-filter-filter" type="text" placeholder="search..."/>',
...
    '           (Select All)',
...
]
```

I don't know if there's more text around, maybe in the paging I guess (I haven't used it)
Could you provide a gridOptions attribute for text overrides?

Thanks!

**Comment by ceolter** [comment]
yea that's my plan, i'll put in some overrides in the gridoptions.
