### ISSUE TITLE
How to use for more level field?

### ISSUE THREAD

**Issue by ohohco** [ceolter/angular-grid#158]
`{field:'contact.address.address',displayName:'contacts'},`
How to use like this more levels fiedl?
For example, response json as:
```
[
    {
        name: "hello",
        contact: {
            phone: '23432432',
            address: {
                address: 'xxxxxxxxxxx'
            }
        }
    },
    {
        name: "world",
        contact: {
            phone: '089832432',
            address: {
                address: 'xxxxxxxxxxx'
            }
        }
    }
]
```

**Comment by ceolter** [comment]
use value getter and expression, eg:
colDef = {valueGetter:'contact.address.address', displayName:'contacts'}

look at the documentation page for value getters.
