### ISSUE TITLE
add ability to change headerCellClass

### ISSUE THREAD

**Issue by ceolter** [ceolter/angular-grid#167]
http://www.angulargrid.com/forum/showthread.php?tid=2228

**Comment by thomas3577** [comment]
Is there any news for this issue?

**Comment by ceolter** [comment]
haven't implemented it yet. given you interest, i'll target getting it into
this weekends release. wtill write a post-it and leave on my desk till it's
done!!

On 16 June 2015 at 19:58, Thomas Huber <notifications@github.com> wrote:

> Is there any news for this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/167#issuecomment-112528797>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by thomas3577** [comment]
Yes, I'm interested for this issue because, I can fix two special cases in my project.

**Comment by ceolter** [comment]
done. in next release.

**Comment by thomas3577** [comment]
How I can use this?

**Comment by thomas3577** [comment]
okay... the propery name in the columDefs is headerClass.

**Comment by ceolter** [comment]
yup!!
