### ISSUE TITLE
Support for AngularJS 1.4?

### ISSUE THREAD

**Issue by mykbaker** [ceolter/angular-grid#168]
Any known issues with using angular-grid with angular 1.4?

**Comment by ceolter** [comment]
I have had nobody mention anything about 1.4, no reason to suspect any issues.

**Comment by mykbaker** [comment]
If that is the case, can you modify the bower.json file to include 1.4? Thanks.

**Comment by ceolter** [comment]
you don't need to use the version that i specify as a dependency, you are free to use whatever version you want??? depending on how you build, you should be only taking the files from my 'dist' folder, you should be getting angularjs as a seperate dependency in your project???

**Comment by jadjoubran** [comment]
Because you're not specifying any version of Angular, this is causing issues for some build scripts - check this [issue here](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/45#issuecomment-138949304).

If you're worried about locking it down to a specific version, you can have a ">1.3" or so..

**Comment by ceolter** [comment]
@jadjoubran are you advising me to do this in ag-grid, or mykbaber to do it in his code?

**Comment by jadjoubran** [comment]
hi @ceolter, thanks for your reply.
Actually it's better if `ag-grid` explicitly defines its dependencies (Angular in this case) so that it works harmoniously with build systems and package managers.

**Comment by ceolter** [comment]
ah - that's the problem, ag-Grid does NOT depend on angular, angular is optional. the grid works all on it's own, angular is only used if you specify you want it inside your custom cells.
