### ISSUE TITLE
The tree style need to improve!

### ISSUE THREAD

**Issue by ohohco** [ceolter/angular-grid#169]

**Comment by ceolter** [comment]
the default is pretty basic - in know that!! but you can provide your own icons? or can you give an example of what your are suggesting?

**Comment by ohohco** [comment]
Just like http://www.ztree.me/v3/demo.php#_514 style or jstree style ,I'v tried to use by provide my own icons,I failed

**Comment by ceolter** [comment]
you should be able to do it with providing your own icons, that's what the file explorer demo does. sorry, but i don't intend creating styles for every use, that's up to you, to style the grid as you need for your application. otherwise i'd be creating new styles for everyone's different taste!!
