### ISSUE TITLE
Text filter does not update

### ISSUE THREAD

**Issue by kenobi883** [ceolter/angular-grid#172]
First of all, thanks for providing the new filtering options! The set filter type is very helpful.

I am having trouble using the text filter type API method `setFilter()`. Here is a JSBin to demonstrate the problem: http://jsbin.com/debidepeyi/1/edit?html,js,output

If you click the button "Set name to John", nothing will happen. It appears that the filter is not applied. Clicking the button "Set age to 36" works, as this applies to the number filter. I took a quick look at the `TextFilter` code, and it appears that the set value is applied to `filterNumber` when maybe it should be set to `filterText`?

Let me know if I can provide more information. Thanks!

**Comment by ceolter** [comment]
Thanks for pointing out. I test the number filter API, and then copy & pasted the logic into the text filter!! I've just checked in a fix to latest on master.
