### ISSUE TITLE
Safari css

### ISSUE THREAD

**Issue by AndreyGoDev** [ceolter/angular-grid#189]
I'm using angular-grid 1.7 on OS X 10.9.5

Please see screenshot for details.

![screen shot 2015-06-06 at 10 13 42 am](https://cloud.githubusercontent.com/assets/12772332/8018777/31da1520-0c35-11e5-906f-0093126c80e9.png)

**Comment by ceolter** [comment]
so i'm clear, your raising the layout been misplaced, looks like the rows are slightly off placement?

**Comment by AndreyGoDev** [comment]
Yes, rows are off placement.

This screenshot is taken on official angular-grid site. I think you can reproduce this bug if you visit official site on safari (I'm not sure if this can be reproduced on Windows)

**Comment by ceolter** [comment]
Just read your board post! Linking in here:
http://www.angulargrid.com/forum/showthread.php?tid=2255

**Comment by ceolter** [comment]
trial and error, i found something that works, change:
.ag-cell { display: inline-block }
to
.ag-cell { display: inline-table }
which appears to fix it in Safari, but then breaks it in Chrome and IE (didn't try FF).

Guess I need to write some code to apply CSS classes specific to browser.

**Comment by AndreyGoDev** [comment]
Didn't work for me in Safari on OS X.

Same on my iPhone.

**Comment by ceolter** [comment]
That's a problem then, I can't troubleshoot, I don't have a mac :(

Will try and got hold of one...

**Comment by AndreyGoDev** [comment]
margin-top: -10px
Seems to be working for Safari (some css artifacts are still noticeable).
I have no idea how to make this hack Safari only

**Comment by ceolter** [comment]
that doesn't work for me, on safari and windows v 5.1.7

sounds odd though, not sure how margin would help - think i need to understand more about why this is happening. but i'm a bit stuck as the fix i have doesn't work for you, and vice versa.

**Comment by ceolter** [comment]
i'll add the browser type as a class on the main grid div, then css can be
specified per browser (and platform??)

On 6 June 2015 at 12:55, Andrey <notifications@github.com> wrote:

> margin-top: -10px
> Seems to be working for Safari (some css artifacts are still noticeable).
> I have no idea how to make this hack Safari only
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/189#issuecomment-109570827>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by AndreyGoDev** [comment]
Looks like it's impossible to download Safari for Windows. I've recorded a video to demonstrate this bug
https://vid.me/iQe1

It would be great if angular-grid worked in all browsers without browser specific hacks.

**Comment by ceolter** [comment]
i think it's the images that are throwing it off. somehow on safari, the images are putting spacing in.

can you please look at the examples in the documentation, where there are no images, is it laid out correctly?

**Comment by ceolter** [comment]
![image](https://cloud.githubusercontent.com/assets/6539563/8019722/373f0fc8-0c55-11e5-8193-a53cd0f613bb.png)

see here, i marked he cell background red, the spacing is put in around the colums with images (country flags and stars) or icons (the boolean column)

**Comment by AndreyGoDev** [comment]
You're right.

Everything's fine, except for tables with images and checkboxes 0:15 https://vid.me/hdn2

**Comment by ceolter** [comment]
fixed it (on windows anyway, hope you can test the mac for me!!)

solution was to apply "float: left" to css class ag-cell

laid out constantly for me in chrome, safari, firefox and IE

**Comment by AndreyGoDev** [comment]
Thank you! Everything works great.

**Comment by jovana** [comment]
For some reason the table cells are not aligned horizontal but vertical. 

<img width="738" alt="schermafbeelding 2015-08-01 om 11 31 24" src="https://cloud.githubusercontent.com/assets/645456/9021411/1d2f1dea-3841-11e5-9e25-561ddd1757bc.png">

To fix this I have added the float: left also to classes .ag-fresh .ag-header-cell and .ag-fresh .ag-cell.
Tested this on Mac Safari, Chrome, FF and Windows IE10.

```css
.ag-fresh .ag-header-cell {
  border-right: 1px solid #808080;
  float: left
}
.ag-fresh .ag-cell {
  padding: 2px;
  float:left;
}
```

**Comment by jovana** [comment]
I'am sorry! Ignore my previous post. I seems CSS file was not loaded at all. :speak_no_evil:

**Comment by ceolter** [comment]
no probs, duly ignored!!

**Comment by surjikal** [comment]
This helped me today, thanks!
