### ISSUE TITLE
Overall grid footer aggregation

### ISSUE THREAD

**Issue by sivaecekrr** [ceolter/angular-grid#190]
Is there is any way to display Overall grid footer aggregation of all rows ? If there please suggest how to proceed. Thanks in advance.

**Comment by ceolter** [comment]
think you are looking for floating footer rows (that don't disappear when you scroll). that is not in. only way around that right now is to use grouping, and have all rows in on master group. then you can use groupIncludeFooter=true in your grid option to display a footer. there is already an issue raised for floating footers.

**Comment by sivaecekrr** [comment]
ok :+1:

**Comment by linuradu** [comment]
It is possible for floating footer to add a property like, "suppressClickEdit: true" that is available only for the footer?

**Comment by linuradu** [comment]
Found a solution:

```
editable: function (data: any) {
    return !data.node.isFloating();
}
```
