### ISSUE TITLE
angularGrid.quickFilterText

### ISSUE THREAD

**Issue by AndreyGoDev** [ceolter/angular-grid#192]
Please correct me if I'm wrong.

It seems that quick text filter works only with ng-model="angularGrid.quickFilterText"
Even if your grid $scope name is different from "angularGrid", for example if it's named "gridOptions".

**Comment by ceolter** [comment]
no it can be anything on the scope, see the example here:
http://www.angulargrid.com/example-data-grid/index.php
the grid options are on the scope as "gridOptions"

**Comment by ceolter** [comment]
sorry, you were right. it's hard coded. i'm fixing that now. will be fixed in next weekends release. in the mean time, you can call the api.setQuickFilter(quickFilter) to set it manually.

**Comment by mindnervestech** [comment]
api.setQuickFilter(quickFilter) not working when my gridOtions have rowModelType: 'infinite'
it gives error ag-grid: cannot do quick filtering when doing virtual paging
