### ISSUE TITLE
<Feature Request> add function for hiding grid columns

### ISSUE THREAD

**Issue by Fangmingdu** [ceolter/angular-grid#195]
I'm using kendo-grid now. It has a very nice feature to show and hide different columns.
and the dropdown menu also looks nice with sorting, filtering and other function. Please take a look at the picture below.
Thanks!!

![kendo-grid](https://cloud.githubusercontent.com/assets/5725594/8041374/6c3ab73e-0ddd-11e5-9f7f-312c7c94a7e4.png)

**Comment by ceolter** [comment]
noted. thanks.

**Comment by vlio20** [comment]
+1

**Comment by ceolter** [comment]
the new tool panel covers this.
