### ISSUE TITLE
header missing in firefox

### ISSUE THREAD

**Issue by vladdvs** [ceolter/angular-grid#196]
I found the tag "ag-body" is not assigned the property "padding-top"
only in firefox(my version is 31.0)

![image](https://cloud.githubusercontent.com/assets/1526857/8051591/c9e6a930-0ec1-11e5-91e4-b4441ba1f912.png)

**Comment by vladdvs** [comment]
in the first time when i opened the page it was all right, but after 15 minutes it appeared
since then it has continued despite the restart of the browser

**Comment by ceolter** [comment]
same as https://github.com/ceolter/angular-grid/issues/124

**Comment by vladdvs** [comment]
Yes

**Comment by vladdvs** [comment]
it's ok now
