### ISSUE TITLE
Bower & NPM

### ISSUE THREAD

**Issue by tannerlinsley** [ceolter/angular-grid#20]
Please register this in Bower and NPM.  I would love to consume it right away!

**Comment by ceolter** [comment]
yea i've been pushing this out for a while now, and your not the first to ask!!! maybe over the easter weekend :)

**Comment by nonmanifold** [comment]
+1 for npm and bower, its not that hard
for bower: create bower.json http://bower.io/docs/creating-packages/ and add a tag "v0.0.1" in your github
for npm: create package.json and register at npmjs.com

**Comment by tannerlinsley** [comment]
I would honestly submit a pull request, but no one should feel good about
registering the bower and npm package names for a repo they don't own. ;)

**Comment by ceolter** [comment]
on my 'todo' list for tonight!! get it onto bower!! this will also help with knowing how many people are using it.

**Comment by juanmav** [comment]
@ceolter Hi, awesone grid!

I think also will be good if you could use "bower" to resolve the dependencies of angular-grid and delete the lib folder.

**Comment by tommck** [comment]
accidental reference there.. edited, but don't know how to remove the reference
