### ISSUE TITLE
api.onNewRows delete set filters, but keep number filters

### ISSUE THREAD

**Issue by Fangmingdu** [ceolter/angular-grid#203]
After I change the number filter on one column, the filter still applies after I called api.onNewRows with new data.
But for the set filter, it is deleted after api.onNewRows.

You can take a look here at this plunker.
http://plnkr.co/edit/iDA3lq?p=preview

Thanks!

**Comment by ceolter** [comment]
thanks for the feedback. i'll take a look soon. ps in the mean time, you can manually clear the filters via the api to at least get consistency.

**Comment by Fangmingdu** [comment]
thanks!

but actually I want to keep the filters other than delete them. :)

**Comment by ceolter** [comment]
in which case, save the filter state, update the rows, then set the filters
again.

the only problem with set filters, is that the set of available values can
change between the row sets - that's why i decided to just clear the filter
with new rows. with a different set of available values, the filter state
may not make sense with the new rows.

On 9 June 2015 at 22:30, Fangming Du <notifications@github.com> wrote:

> thanks!
>
> but actually I want to keep the filters other than delete them. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/203#issuecomment-110509374>
> .
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by Fangmingdu** [comment]
OK. I see the problem.

Thanks for providing an alternative solution!

**Comment by Fangmingdu** [comment]
Hello,

It seems I met a new problem. After I load different total with api.onNewRows, the set filter still gives me the same set of data for selection, it is not updated.

You can still try from this plunker.
http://plnkr.co/edit/iDA3lq?p=preview

Thanks!

**Comment by ceolter** [comment]
indeed. thanks for raising.

**Comment by Fangmingdu** [comment]
Thanks.
Do you think it would be hard to fix? I'm also taking a look at the source code.

**Comment by ceolter** [comment]
no - if you know what your doing!

i was thinking, as a quick fix, the FilterManager contains a list of filters. the filter is created the first time you show the filter popup. what could be done is create api.resetFilters() that would call filterManager.resetFilters() that would clear out all the 'created so far' filters, hence starting from scratch, and forcing each filter to create again next time it is shown.

**Comment by Fangmingdu** [comment]
Thanks for the hint.

It seems I can do the quick fix.

FilterManager.prototype.resetFilters = function () {
    this.allFilters = {};
};

and expose resetFilters from api.

I'm thinking a better way would be to update all the uniqueValues for the filter model after user do api.onNewRows.

**Comment by ceolter** [comment]
> I'm thinking a better way would be to update all the uniqueValues for the filter model after user do api.onNewRows.

problem with that is what do you do if the selection doesn't match? ie if you selected 'green & blue',  but only 'blue' is in the new set. and is the user focusing on what's selected, or deselected???

**Comment by Fangmingdu** [comment]
That's true.

Do you want me to create a pull request for that quick fix?

**Comment by ceolter** [comment]
no it's ok, i'll stick the code in now. i also want to review it all, make sure i'm not missing (breaking) anything. not having test, i need to be the master brain and watch every line of code!

**Comment by ceolter** [comment]
i fixed this by having the filters all clear by default, and also allowing an option to not clear them. if you want to grab the latest from master, be my guest, just be aware there is 10% chance of a bug as i haven't done my regression testing (i do that only when doing releases).

the idea of removing the filters totally didn't work for me in my brain, as in the future, i want to be able to 'pin filters' (ie filters that are displayed outside of the menu, maybe in a header area, or a dockable sidebar) and haven't decided yet how they will work when new rows are loaded.

**Comment by ceolter** [comment]
oh - and i now identify the filters by columnID (which defaults to the field name if no id is set), so when you add / remove / rearrange rows, the filters will stay with the right column (before the filters were assigned the index of the column which was just wrong)

**Comment by gdaszuta** [comment]
> in which case, save the filter state, update the rows, then set the filters
> again.

> the only problem with set filters, is that the set of available values can
> change between the row sets - that's why i decided to just clear the filter
> with new rows. with a different set of available values, the filter state
> may not make sense with the new rows.

Could you elaborate, please? I'm trying to save filters in onAfterFilterChanged, and then restore them in onModelUpdated, but then restoring filters reloads dataset, which in turn makes neverending loop :(
