### ISSUE TITLE
can we use no vertical scroll only instead "dontUseScrolls"?

### ISSUE THREAD

**Issue by vladdvs** [ceolter/angular-grid#204]
I did not find this in the documentation and issues

**Comment by ceolter** [comment]
afraid not - the 'dontUseScrolls' doesn't just simply suppress the scrolling, the table is laid out in a different way (see the layout page in the documentation). If you want just scrolling in one direction (ie horizontally) then I suggest you work out the height of the table dynamically based on the number of rows. i'd rather not have the table change height by itself, it's design is to fill the div you put it in.

**Comment by vladdvs** [comment]
Ok, thanks

**Comment by vladdvs** [comment]
it's implemented by adding classes:
   .nonVerticalSlider .ag-scrolls {height: unset;}
   .nonVerticalSlider .ag-body {height: unset;}
   .nonVerticalSlider .ag-body-viewport-wrapper {height: unset;}
   .nonVerticalSlider .ag-body-viewport {height: unset;}
and grid defining as:
   <div ag-grid="gridOption" class='ag-fresh-custom nonVerticalSlider'>

**Comment by vladdvs** [comment]
I assume that you can not set the height of the tags if for example the directive "no vertical scroll" is set

**Comment by ceolter** [comment]
i just tried this out, it works!! thanks for the tip.

**Comment by ceolter** [comment]
any ideas on having a max height?

**Comment by vladdvs** [comment]
I think algorithm must be very simple yet -
Only the assignment of CSS properties "max-height" if the user specified it

**Comment by ceolter** [comment]
sorry, i had to take this out again. in the next release, this feature will be dropped. i have redesigned they way the layout works, and not it is no longer compatilble with your suggested solution.
