### ISSUE TITLE
Using the grid in a "flex" box

### ISSUE THREAD

**Issue by kktos** [ceolter/angular-grid#206]
Hi,

we're evaluating the grid, so we're absolute beginners with it, hence possible stupid questions ;)
We have a page with different areas. This page layout is done using the display flex.

Is there already some CSS we have to use to make the grid "flex" aware ?

We can do it wut before overriding the grid CSS we wished to check ;)

thanks.

**Comment by ceolter** [comment]
hi, the grid is not aware of flex (like me, i don't use flex, am not aware of how it works). basically the grid takes up the space you give it - so if flex can size the containing div, then do that and the grid will fit it.

please can you ask questions on the board on my website instead? that way others can benefit form the answers! thanks :)
