### ISSUE TITLE
Pagination - How to update rowCount in the existing dataSource 

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#207]
When setting up a dataSource I actually don't have rowCount initially. So inside getRows method when the ajax call made, it returns back the total counts which I can assign to rowCount. But unfortunately that not seems to be appear in the UI. My Code looks like this:

var dataSource = {

                pageSize: 20,

                getRows: function (start, finish, callbackSuccess, callbackFail) {

                    var self = this;

                    return dataService.single.getAllByMatchMakerId(user.id, start, finish)
                        .then(function (data) {

                            self.rowCount = data.counts;
                            var rowsThisPage = data.singles;
                            var lastRow = -1;
                            callbackSuccess(rowsThisPage, lastRow);
                            console.log(dataSource)
                            if (vm.gridOptions) {
                                vm.gridOptions.api.refreshView();
                            }
                        });
                }
            };

            vm.gridOptions = {
                columnDefs: gridOptions.columnDefs,
                angularCompileRows: true,
                ready: function (api) {

                    api.setDatasource(dataSource);
                }
            }

Any suggestion?

**Comment by ceolter** [comment]
Pass the row count into the callbackSuccess, as lastRow.

eg:
callbackSuccess(rowsThisPage, data.counts);

**Comment by ammar91** [comment]
Awesome, Thanks so much :)

**Comment by rajgopalk** [comment]
Thanks

**Comment by kcs-chiragdudhat** [comment]
@Team We have use angular ag grid as per below : 
<ag-grid-angular 
#agGrid
id="agGrid"
	style="width: auto; height: 500px;" 
	class="ag-theme-balham"
    pagination="true"
    [paginationPageSize]="pagesize"
    sorting="true"
	[rowData]="rowData" 
	[columnDefs]="columnDefs"
    rowSelection="multiple"
    (gridReady)="onGridReady($event)"
    (onFirstDataRendered)= "onFirstDataRendered()"
   
    >
</ag-grid-angular>

so can you please help me where we do set total rows count , Suppose : i have 1000 rows , so we have need to show 100 rows per page and go request from server side as per next pages.
