### ISSUE TITLE
Pagination - Messed up when updating DataSource

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#209]
I have a dropdown in my view which basically allow to change the Page Size 

Show x entries

Every time when dropdown value change the below function get's called and updated the Grid data. The data looks good but seems like the pagination information at the bottom messing up. Like when the view initially load the Page Size set to 10 by default. And it shows correct pagination info which looks like this: 1 of 10 of 19,800

But when I change the dropdown value from 10 to 20, instead of showing 1 of 20 of 19,800, it shows 1 to 119 of 19,800. Please suggest

  function getAllSinglesByMatchMaker() {

            var dataSource = {

                pageSize: vm.pageSize,
                getRows: function (start, finish, callbackSuccess, callbackFail) {

                    return dataService.single.getAllByMatchMakerId(user.id, start, finish)
                        .then(function (data) {

                            var rowsThisPage = data.singles;
                            var lastRow = data.counts;
                            callbackSuccess(rowsThisPage, lastRow);
                        });
                }
            };

            if (vm.gridOptions) {
               
                vm.gridOptions.api.setDatasource(dataSource);
                return false;
            }

            vm.gridOptions = {
                columnDefs: gridOptions.columnDefs,
                angularCompileRows: true,
                rowClass: function (params) {
                    if (!params.data.published) {
                        return 'text-red';
                    }
                },
                ready: function (api) {
                    api.setDatasource(dataSource);
                }
            }
        }

**Comment by ceolter** [comment]
> var lastRow = data.counts;
>                         callbackSuccess(rowsThisPage, lastRow);

in the above code, what is lastRow when the problem happens?

lastRow should always be null/undefined/-1 until you know how big your dataset is, then you set it to the rowindex of the very last row.

the fact the grid is showing 119 looks odd, as it should only show an odd number here (not an 'end of page' number) when it hits the last page.

other than that, you code looks fine. it's difficult for me to suggest what else might be wrong. if you could replicate in a plunker, would be easier.

**Comment by ammar91** [comment]
lastRow set to 19,800, which is the total number of records. The surprising thing is, it works well when it initially load whatever the page size I set but when it changes from dropdown and I reassign the datasource, it's getting out of syc.

**Comment by ceolter** [comment]
when you update the page size, are you resetting the datasource?

eg
gridOptions.api.onNewDatasource();

**Comment by ammar91** [comment]
yes, I do. 

 if (vm.gridOptions) {
            vm.gridOptions.api.setDatasource(dataSource);
            return false;
        }

**Comment by ammar91** [comment]
When ever dropdown value change, it calls the function 'getAllSinglesByMatchMaker' and inside it, it creates a dataSource with the updated Page Size and then I check if the vm.gridOptions already exist, if so I reset the dataSource.

**Comment by ceolter** [comment]
kind'of toubleshooting blind here, but:

print to the console the datasource pageSize just before your if statement:
> console.out('pageSize=' + dataSource.pageSize
> if (vm.gridOptions) {
>
>            vm.gridOptions.api.setDatasource(dataSource);
>           return false;
>        }

if the grid is working (which it is i believe, lots of people using it) then I thin you might be setting the page size to 119.

**Comment by ammar91** [comment]
It shows page size=10 (the updated one). Yes, Grid is working fine but not sure what's going with the pagination info. I am not setting the page size to 119 anywhere. Also I noticed when I jump to the last it shows the correct info (i.e, 19,791 to 19,800 of 19,800) but when I again go to the first page it says 1 to 109 of 19,800 and this dramatically change when I go to the second page it shows 11 to 1,109 f 19,800.

**Comment by ammar91** [comment]
I am sorry, my mistake. I did not parse the model value to int and it was passing the string literal.

**Comment by ammar91** [comment]
Again, Thanks for all your help.

**Comment by ceolter** [comment]
knew it!!! :)

good luck with your app. if it's an external facing website, please pass on a link so i can see the grid in use!

**Comment by ceolter** [comment]
i have updated my demo to now including changing page size (won't be online till my next release). i also put in logic to check the type, if it's not a number, it prints to the console warning such. so nobody will have the same problem you did!

**Comment by ammar91** [comment]
Sounds Great:)

Unfortunately, It's not integrated on public pages so not sure how would you be able to review. And also it will be a part of my next release, I found this grid really great among others. Really appreciate all of your hard work.

**Comment by ceolter** [comment]
which other grid did you use? and why did you change? (ie what was good about ag-grid in particular)

if you don't  mind me asking!!

**Comment by nandhacse** [comment]
How to display the pagination select tag after the table in ag-grid. if i change the select into the bottom of the table then it won't function properly, meaning can't select. it simply idle.

Please suggest...

**Comment by harshitgupta** [comment]
Hi @ceolter.

I was facing a similar issue. I was receiving an integer in the json and passing it to the success callback as it is. as we normally do. But it was not working.

It started working only after i used parseInt(). Please let me know if I am missing something. I would really appreciate it.

Also, if possible, please update the documentation for the same so people like me in the same situation, won't end up wasting time.

Thanks a lot for the component.

**Comment by ceolter** [comment]
mayve parseInt() was not a full number? i'll update the code and validate it

**Comment by ceolter** [comment]
just updated the code, now the grid parses and floors the number, so it will be converted to a whole number if it is not already.

**Comment by denver-HJS** [comment]
Hi @ceolter,

I'm running into an issue where the `paginationPageSize` doesn't seem to be having any effect. You can see in the following code I isolate the value into a variable that's a parsed integer, but it does not change the results in the grid. It does scroll it to the top though.

```
      function setDataSource(data) {
                let isApiAvailable = self.options.api;
                if(isApiAvailable) {
                    let pageSize = parseInt(self.selectedPageSize, 10);
                    self.options.api.setDatasource({
                        paginationPageSize: pageSize,
                        rowCount: data.length,
                        getRows: (params) => {
                            if (!angular.equals(params.sortModel, self.currentSortModel)) {
                                self.currentSortModel = params.sortModel;
                                data = _.orderBy(data, self.currentSortModel.map(model => model.colId), self.currentSortModel.map(model => model.sort));
                            }
                            params.successCallback(data.slice(params.startRow, params.endRow));
                        }
                    });
                }
            }
```
Do you see anything that's obviously wrong here?
