### ISSUE TITLE
sizeColumnToFit error - Cannot read property 'clientWidth' of undefined

### ISSUE THREAD

**Issue by chiptus** [ceolter/angular-grid#211]
I get this error when trying to use sizeColumnsToFit
TypeError: Cannot read property 'clientWidth' of undefined
    at Object.Grid.addApi.api.sizeColumnsToFit - line 44
I tried to look for documentation for this function in case i'm not using it correctly, but can't find anything about it in http://www.angulargrid.com/angular-grid-api/index.php

**Comment by ceolter** [comment]
> I tried to look for documentation for this function

it's mentioned here:
http://www.angulargrid.com/angular-grid-resizing/index.php

re why it's failing, i don't have enough info. do you have a stacktrace?

maybe the grid isn't attached to the dom when you are calling??

**Comment by chiptus** [comment]
It seems like this option isn't working when dontUseScrolls is true. that's why it failed.
Can you add this function also to the API documentation? seems logical to me. also state that dontUseScrolls should be false.
Now, when it is working i have all columns width about 5px and only the last one filling the rest of the screen.

![image](https://cloud.githubusercontent.com/assets/1381655/8105608/4a4f0e50-1043-11e5-9fb1-983b145cd2ad.png)
And as you can see the scrollbars are covering part of the table

**Comment by ceolter** [comment]
size cols to fit was no intended to work with 'noScrolls', i'll add the check in, so errors if person tries to use it.

does the grid display fine if you don't call this method?

**Comment by chiptus** [comment]
display ok, it's doesn't fit my window.

**Comment by ceolter** [comment]
i can't really say - by just a screenshot it could be anything. it's probably something you are doing though, as the grid is working for 100's of people and nobody has reported this.

**Comment by chiptus** [comment]
Of course it something I'm doing wrong :) otherwise it would work.
For now I fixed my issues
