### ISSUE TITLE
How to disable filter and sort for a specific columns

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#212]
I applied filtering and sorting on gridOptions object by setting the relative property

enableSorting:true,
enableFilter: true

But there are some custom columns in my grid which contain Action buttons like Edit, Delete etc..And I want to disable filtering and sorting for that specific column. How it would be possible?

**Comment by ceolter** [comment]
http://www.angulargrid.com/angular-grid-column-definitions/index.php

colDef.suppressMenu = true
colDef.suppressSorting = true

**Comment by ammar91** [comment]
Great, Thanks so much:)

**Comment by shankar-velaga** [comment]
http://jsfiddle.net/7ony74h5/1/

**Comment by HariBabuThubati** [comment]
@ceolter :  How to limit the quick filter for few columns using ag-gridd-Enterprise, please advise me?

**Comment by ceolter** [comment]
@HariBabuThubati if you don't want a column in quick filter, then use colDef.getQuickFilterText and return null for the columns you want to exclude.
https://www.ag-grid.com/javascript-grid-filtering/

**Comment by HariBabuThubati** [comment]
@ceolter : Thanks for response but it was not working.As you suggest setting null for few columns which are not required , still showing results from those columns.

**Comment by ceolter** [comment]
then i don't know what's wrong. maybe you can debug through ag-Grid and see what the logic is, why it's breaking?

**Comment by HariBabuThubati** [comment]
@ceolter : I am using ag-grid-enterprise 4.2.11

**Comment by ceolter** [comment]
```I am using ag-grid-enterprise 4.2.11```
check the release notes, this feature was introduced in v6.<something>
https://www.ag-grid.com/change-log/changeLogIndex.php

**Comment by diegoa1989** [comment]
How can I use this feature on Mobile? because I'm using with this parameter: "suppressSorting: true" and doesn't work.

**Comment by jaganmohanreddy2106** [comment]
How can I apply filtering on column, when I use cellRenderFramework ..?
For example:
Coldef: [ 
{headerName: "Details", filed: "user", cellRenderFramework: myRemder},
{headerName: "Details1", filed: "temp1"},
]
Once I merge two values into one cell, i'm unable to filter the column and download it.

**Comment by allanpichler** [comment]
![filter_context_menu](https://user-images.githubusercontent.com/16302352/40784851-189627b2-64e7-11e8-94ee-f50d2b8656ca.jpg)

Is it possible to make the "context-menu" for columns open on the "filter"-tab ???

**Comment by BernhardBaumrock** [comment]
> http://www.angulargrid.com/angular-grid-column-definitions/index.php
> 
> colDef.suppressMenu = true
> colDef.suppressSorting = true

Thanks for that. Is there a reason why suppressSorting is not in the docs? https://www.ag-grid.com/javascript-grid-sorting/

**Comment by JabbyPanda** [comment]
Since ag-grid v20 please use colfDef.sortable for same purpose 

```
/** @deprecated since v20, use colDef.sortable=false instead */
suppressSorting?: boolean; 
```

**Comment by waqasajaz** [comment]
In ag-grid v25 there is no specific attribute to disable filtering on a column. But you can remove the filtering option `filterMenuTab` from the column menu by changing the menu options.
`menuTabs: ['generalMenuTab',  ,'columnsMenuTab']`
