### ISSUE TITLE
Custom Filter - Filter is missing method getGui

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#213]
I created a custom filter basically just copy and paste the one show here:
http://www.angulargrid.com/angular-grid-filtering/index.php

But when I click on menu icon, it put the error in console 

"Uncaught Filter is missing method getGui"

However, I double check my code and it is define there. Please suggest

**Comment by ceolter** [comment]
All I can say is what the grid is already telling you, that you don't have a 'getGui' method in your filter.

the code in ag-grid is:

    if (!filterWrapper.filter.getGui) { // because users can do custom filters, give nice error message
        throw 'Filter is missing method getGui';
    }

where 'filter' is the result of calling 'new' on the provided filter.

**Comment by ammar91** [comment]
OK I was wrapping the Interface in IIFE, that causes this. I took out from the IIFE and it works. 
Thanks.

**Comment by manollyjohnny** [comment]
@ammar91  can you provide the fixed code? i can't seem to make it work
