### ISSUE TITLE
sorting by datetime

### ISSUE THREAD

**Issue by bgauvey** [ceolter/angular-grid#214]
when the time is 12h, the sorting is not correct.  It seems to be sorting via alpha

**Comment by ceolter** [comment]
the default sorting is by this:
valueA < valueB

so if numbers, it compares the numbers, if strings, it's alpha numeric, if dates, it's just dateA < dateB

if this doesn't work, then you need to provide your own custom sorting function. see the docs (sorting page) on providing your own sorting func.
