### ISSUE TITLE
FilterParams CellRenderer and Searching

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#215]
I have a column name 'Gender'. In the db it's value stored in a single character, i.e, either M or F.
On the UI I am decoding it to full value with a directive and uses 'template' attribute in column definition. It renders the value in Grid as expected. Now I have a filter menu in which I also need to format it, other wise it would show 'M' and 'F'. So for that I am formatting it using the CellRenderer function within filterParams object, it also looks good in filter list but the problem I noticed is with searching. Looks like it search with the actual value that is 'M' or 'F', when I type full decoded value inside Search box, i.e, Male it make the list empty. Screenshot attached:

             {
                   displayName: "Gender",
                   field: "gender",
                   template: '<span data-char-to-text="gender" data-char-to-decode="data.gender</span>',
                   filter: 'set',
                   filterParams: {
                       cellRenderer: function (params) {
                          
                           return commonService.decodeFieldTextFromChar('gender', params.value);
                       }
                   }
               },

![result](https://cloud.githubusercontent.com/assets/7683970/8132874/259aa79e-113e-11e5-9ded-c9b3f732f0d6.PNG)
![no-result](https://cloud.githubusercontent.com/assets/7683970/8132875/2929a0f4-113e-11e5-93ad-a159bb7f3bae.PNG)

Is there anything else I need to take care?

**Comment by ceolter** [comment]
user valueGetter for the conversion, not cellRenderer. see section in docs.

**Comment by ammar91** [comment]
I tried this, but still not seems to be working. Can you please point out what I am doing wrong?

              {
                   displayName: "Gender",
                   field: "gender",
                   template: '<span data-char-to-text="gender" data-char-to-decode="data.gender</span>',
                   valueGetter: commonService.decodeFieldTextFromChar('gender', 'data.gender'),
                   filter: 'set',
                   filterParams: {
                       cellRenderer: function (params) {

                           return commonService.decodeFieldTextFromChar('gender', params.value);
                       }
                   }
               },

**Comment by ceolter** [comment]
> valueGetter: commonService.decodeFieldTextFromChar('gender', 'data.gender'),

the value getter needs to be either a function or an expression (string)

i'm guessing what  you mean is something like:

valueGetter: function(params) {
  return commonService.decodeFieldTextFromChar('gender', params.data.gender);
}

**Comment by ammar91** [comment]
This is pretty awesome. It also eliminate the need of a directive that I previously wrote :)
Thanks again for all your help.

**Comment by shreyaagarg** [comment]
Hi,
I have a column -> in which there is a button and on clicking the button a modal pops up in which the data of column appears as table.
The button I have made using cell renderer.

Now I am getting problems in searching. As the table contents are not searchable and it returns empty
