### ISSUE TITLE
getFilterModel() function returns string value even for int fields

### ISSUE THREAD

**Issue by Fangmingdu** [ceolter/angular-grid#216]
I have a column with all int value and set filter.
Then I used getFilterModel() function to save the filter on that column, but it returns all value as string.
Then when I use api.setFilterModel() function to set back the saved model, it says "is not a valid value for filter", because the values are int and the model saved values are all string.

Please take a look at this plunker. http://plnkr.co/edit/8dOgMlhmaftahd27RnWK?p=preview

Thanks!

**Comment by ceolter** [comment]
thanks for raising. i'll fix this.
