### ISSUE TITLE
Rowspan

### ISSUE THREAD

**Issue by Thrilleratplay** [ceolter/angular-grid#22]
Reading through the story of "Why The World Needed Another AngularJS Grid" sounded hauntingly familiar.  Bouncing from ng-grid, to pure Angular.js to looking into writing a d3/svg implementation.  

I am curious, is there a way to mimic rowspan behavior like in HTML tables?

**Comment by ceolter** [comment]
lol - yea i expect it's familiar for a lot of people!! re row-span and col-span, interesting idea, hadn't thought of that. i wonder how many applications of this would there be? from how Angular Grid lays out the cells, it's technically feasible, each cell boils down to a div with a {x,y,width,height}, so it's just left to the maths to calculate what needs to be drawn - gets tricky with the virtualisation of the rows. also i wonder how such would be represented in the model (ie the rows passed to the grid).

**Comment by ceolter** [comment]
I had a quick play, you can change the height of the cells, use colDef.cellStyle. See below. Basically increase the height of the cell you want to span more than one row, and set to zero the one you want to remove.

colDef {
    cellStyle: function(params) {
        if ( isThisARowIWantToExpand(params.data)) {
            return {'height', '50px'};
        if ( isThisARowIWantToShrink(params.data)) {
            return {'height', '0px'};
        } else {
            return null;
        }
    },
    // other cold def stuff here
}

**Comment by ceolter** [comment]
am closing this issue as a) not a lot of interest around it, b) putting something in would be a large amount of effort, for little gain (given not many people have asked for it) and c) there is a workaround as described above :)

**Comment by fpauser** [comment]
So no rowspan/colspan support?

**Comment by ceolter** [comment]
no rowspan / colspan support right now.

**Comment by santosh-k1** [comment]
Yes we can create row span look and fill ... i have used below code to Done this -

   ```
 headerData[item].headerName = $translate.instant(headerData[item].field);
                    if (headerData[item].field == "ProposedQty") {
                        headerData[item].cellRenderer = function (params) {
                            if (params.data["ProposedQty"] == 0) {
                                return 0;
                            }
                            else {
                                return params.data["ProposedQty"];
                            }
                        }
                        headerData[item].cellClassRules = {
                            'column-merge-with-value': 'x == 0',
                            'column-merge-with-no-value': 'x != 0',
                        };
                    }
```

CSS classes -

```
/*column-merge- in ag-grid start from here*/
 .column-merge-with-value {background-color: white; border-bottom: 0px solid #fff !important;}
 .column-merge-with-no-value { background-color: white; border-top: 1px solid #D6D6D6 !important;  border-bottom: 0px solid #fff !important;}
 .column-merge-with-value:focus, .column-merge-with-no-value:focus {color:#000!important}
/*column-merge- in ag-grid end from here*/
```

**Comment by maomao93** [comment]
I want to merge cells within a group after performing the grouping, but it doesn't seem to be supported

**Comment by casamia918** [comment]
Check this out 

https://github.com/ag-grid/ag-grid/issues/7627
