### ISSUE TITLE
Responsive Grid and Column Widths?

### ISSUE THREAD

**Issue by dereklin** [ceolter/angular-grid#220]
I did some search but couldn't find the answers:

I was wondering if angular grid can be responsive to window resize, and that the column widths could automatically take up the whole screen real estate.

**Comment by ceolter** [comment]
Grid automatically resizes to the containing div. So if div grows (window
resize or other reason)  then grid will grow to fit.

There is a method 'size cols to fit'  that you can call to get cols to fit
width. You Could call this in listener to window resize, best in a timer,
try 500 ms, to give grid time to resize first.

**Comment by dereklin** [comment]
@ceolter Here is a plunker I have created: http://plnkr.co/edit/kveA78BUA8iXNZbb8usa?p=preview

I can only define column width in pixels.  And they default to 200px by default, right?

How can I stretch out the the grid with my current settings?

And when I resize the window, the grid is not resized.

Thanks,

Derek

**Comment by ceolter** [comment]
to get the grid to resize, you need to have the div containing the grid to resize. this is outside the scope of the grid, it's standard css. try using 100% width and height.

for the cols to fit the width, call the api function api.sizeColsToFit() (might have it spelt wrong here, but you can get it exactly from the documention api page)

**Comment by kvanlaan** [comment]
Setting width to 100% does not work. The div will not resize. This is a persisting but with Ag-Grid and the issue should not be closed.

**Comment by ceolter** [comment]
the main demo here:
https://www.ag-grid.com/example.php
demonstrates the grid resizing as you change the browser size.

so 100% width does work.

furthermore, see the examples here for detailed discussion on responsive design:
https://www.ag-grid.com/javascript-grid-responsiveness/

**Comment by kvanlaan** [comment]
Hi Niall. This does not work. The toolbar is fixed to the side. But the
columns do not resize.

Katrina

**Comment by viknes-interana** [comment]
Something to note is that if the parent grid uses flex box and if the width is determined automatically by `flex-grow: 1`, then it won't work. We would have to specify `width` explicitly and it does work even if it is in percentage. 

Quick way to try it out is clone `ag-grid-react-example` and set the `width` to `100%` in `src/richComponentExample/RichComponentsExample.jsx`. Then goto the page that displays this example (`Dynamic React Components - Richer example`) and resize the window. The columns automatically resizes along with the window. With this, you can try to troubleshoot which css code in your code prevents it from working.

**Comment by viknesb** [comment]
Something to note is that if the parent grid uses flex box and if the width is determined automatically by `flex-grow: 1`, then it won't work. We would have to specify `width` explicitly and it does work even if it is in percentage. 

Quick way to try it out is clone `ag-grid-react-example` and set the grid container's `width` to `100%` in `src/richComponentExample/RichComponentsExample.jsx`. 
You also have to add a listener to `window.resize`
```javascript
onGridReady(params) {
        this.gridApi = params.api;
        this.columnApi = params.columnApi;
        this.gridApi.sizeColumnsToFit();
        window.onresize = () => {
            this.gridApi.sizeColumnsToFit();
        }
}
```
Then goto the page that displays this example (`Dynamic React Components - Richer example`) and resize the window. The columns automatically resizes along with the window. With this, you can try to troubleshoot which css code in your code prevents it from working.

**Comment by kvanlaan** [comment]
Hi all, Sorry about the late reply. I was able to get it to work! Thanks!

**Comment by ymjongbin** [comment]
How about if have two columns?  The first column is 60%, second column is 40%. How to keep this ratio even if whole width changed by splitter moving?

**Comment by vdemidov230583** [comment]
So how to make columns responsive in the MasterTable feature? How should I plug nested table into the div, that I can style?

**Comment by vasanth300** [comment]
hi

**Comment by martin-morales** [comment]
I know I'm late to the party, but for future Googlers, using window.onresize only allows you to have one listener at a time. Using master/detail grids or multiple grids, will not work with that approach. Instead, you should use event listeners. Note: You'll need to keep an instance variable of the event listener function, so that you can remove it on component destroy.
```
@Component({
  selector: 'sample-component'
  template: `
    <ag-grid-angular
    ...
    (gridReady)="onGridReady()"
    ></ag-grid-angular>
  `
})
export class MyComponent implements OnDestroy {
  private resizeListenerFunc = () => { this.gridOptions.api.sizeColumnsToFit(); };
  ...
  onGridReady() {
    this.gridOptions.api.sizeColumnsToFit();
    window.addEventListener('resize', this.resizeListenerFunc);
  }
  ngOnDestroy() {
    window.removeEventListener('resize', this.resizeListenerFunc);
  }
}
```
