### ISSUE TITLE
Can't customize checkbox of column with checkboxSelection

### ISSUE THREAD

**Issue by sanfords** [ceolter/angular-grid#221]
I have a column that contains checkboxes for selection.  I set checkboxSelection:true on the column.

I don't know how to make custom css for a checkbox within this column.  To my knowledge, custom css for a checkbox requires a `div` around the checkbox.  What renders is a `span` around the checkbox.

When I create a cell renderer, my render appears behind a normal checkbox.  Looking at the code, checkboxSelection appears to call `that.selectionRendererFactory.createCheckboxColDef();` and there's no way to patch it.

Am I missing some way of wrapping the `input` with a `div` so I can customize the look and feel of the checkbox?

**Comment by ceolter** [comment]
> To my knowledge, custom css for a checkbox requires a div around the checkbox.

That's not true! You just need the right CSS selector to get to the checkbox.



> When I create a cell renderer, my render appears behind a normal checkbox. Looking at the code, checkboxSelection appears to call that.selectionRendererFactory.createCheckboxColDef(); and there's no way to patch it.

What you can do is create your own cellRenderer from scratch - forget about the built in checkbox. Provide your own checkbox. Then use the selection api to select / unselect the row.

**Comment by noherczeg** [comment]
I'd like to share some sample code if anyone would need help regarding this issue :)

What this does is, allows you to set an id to the select boxes which would be impossible with the built in selector.

Directive Controller code:
```
MyListCtrl.prototype.selectNodeById = function (nodeIdx) {
        if (this.lodash.find(this.gridOptions.api.getSelectedNodes(), {id: nodeIdx})) {
            this.gridOptions.api.deselectIndex(nodeIdx);
        } else {
            this.gridOptions.api.selectIndex(nodeIdx, true);   // true means additive selection
        }
    };

MyListCtrl.prototype.addControlColumns = function () {
        var vm = this;
        this.columns.unshift({
            field: 'select',
            headerName: '',
            width: 30,
            suppressSorting :true,
            cellRenderer: this.selectBoxFn.bind(vm)
        });
    };

MyListCtrl.prototype.selectBoxFn = function (params) {
        var compID = 'MyCustomComponentID';
        return '<input id="' + compID + '" type="checkbox" name="list-item-row-selection" ng-click="vm.selectNodeById(' + params.node.id + ')">';
    };
```
