### ISSUE TITLE
Default sort on server side sorting

### ISSUE THREAD

**Issue by jonsamwell** [ceolter/angular-grid#222]
Hi,

I'm looking for a way to set a default sort when the sorting, filtering and paging are done on the server.  I would have thought there might be a property you could set on a column definition to indicate that the initial sort of the data is on this column, which would then get passed to the getRows function when the grid loads.

Thanks,

Jon

**Comment by ceolter** [comment]
noted, i'll put something like this in.

however, would the following work:
1) create grid
2) set sort via api.setSortModel()
3) set datasource via api.setDatasource()

**Comment by jonsamwell** [comment]
I'll give it a try now

**Comment by ceolter** [comment]
let me know if it works please

**Comment by jonsamwell** [comment]
This doesn't seem to work I get a warning in the console:

ag-grid: You are setting the sort model on a grid that does not have sorting enabled

My grid options are:

```
self.gridOptions = {
      enableFilter: true,
      enableSorting: true,
      enableServerSideSorting: true,
      enableServerSideFilter: true,
      quickFilterText: String.empty,
      enableColResize: true,
      rowSelection: 'multiple',
      rowDeselection: true,
      pinnedColumnCount: 1,
      suppressVerticalScroll: true,
      columnDefs: [
        {headerName: 'Col1', field: 'field1', suppressMenu: false, checkboxSelection: true, filter: 'text'},
        {headerName: 'Col2', field: 'field2', suppressMenu: true},
        {headerName: 'Col3', field: 'field3', suppressMenu: false, filter: 'number'},
        {
          headerName: 'Created', field: 'created', suppressMenu: true, cellRenderer: function (params) {
          return $filter('date')(params.value, 'dd MMMM yyyy');
        }
        }
      ]
    };
```

**Comment by jonsamwell** [comment]
If looks like the logic is a bit wrong in the setSortModel function.  It appears to go not sort if sorting is enabled.

```
Grid.prototype.setSortModel = function(sortModel) {
    if (this.gridOptionsWrapper.isEnableSorting()) {
        console.warn('ag-grid: You are setting the sort model on a grid that does not have sorting enabled');
        return;
    }
```

I think it should be this:

```
Grid.prototype.setSortModel = function(sortModel) {
    if (this.gridOptionsWrapper.isEnableSorting() === false) {
        console.warn('ag-grid: You are setting the sort model on a grid that does not have sorting enabled');
        return;
    }
```

**Comment by jonsamwell** [comment]
If I change the code to not return if sorting is enabled it still doesn't work :-(

**Comment by ceolter** [comment]
oh crap, i'll look at that now, the examples on my website around this are broken also

**Comment by ceolter** [comment]
i've patched and released.

the demo is working for me now (locally, i haven't updated website, i cant do that from my day job)

if you get latest, why does it still not work?

**Comment by jonsamwell** [comment]
Awesome!  I'll get the latest and look now.

**Comment by jonsamwell** [comment]
It's working now, I foolishly wasn't passing an array into the setSortModel function!  So the full working solution if anybody else stumbles across this is below.

```
 gridOptions.ready = function (api) {
      api.setSortModel([{field: 'name', sort: 'asc'}]);
      api.setDatasource({
        getRows: getRowsFn,
        pageSize: 50
      });
    };
```

**Comment by jonsamwell** [comment]
Great library by the way!

**Comment by ceolter** [comment]
Thanks :)
