### ISSUE TITLE
function refreshView() support recalculation and redraw child for group

### ISSUE THREAD

**Issue by loongdefect** [ceolter/angular-grid#227]
when I change the value of field key.
I use the function
option.api.refreshView ()
but the row only change values and not move to another group. You can support the call option.api.refreshView () will recalculate and redraw the child of group's?
for example:
```javascript
data: [{field1: a, field2: b}, {field1: c, field2: d}]
option = {
columnDef: [{field: 'field1', headerName: 'field1'}, {field: 'field2', headerName: 'field2'}],
rowData: data,
groupKey: ['field1']
}
```

first show:

field1 | field2
------------ | -------------
group a | 
a | b
group c | 
c | d

after changing the value of row 2: field1 = a
display:

field1 | field2
------------ | -------------
group a | 
a | b
group c | 
a | d

**Comment by loongdefect** [comment]
demo:
http://plnkr.co/edit/VYOmzXjAcz9ARqzjWJR6?p=preview

**Comment by ceolter** [comment]
if you want the grouping to be done again, call api.onNewRows()
