### ISSUE TITLE
Column width in % instead of pixel and resize?

### ISSUE THREAD

**Issue by dereklin** [ceolter/angular-grid#228]
Here is my plunker: http://plnkr.co/edit/kveA78BUA8iXNZbb8usa?p=preview

When first loaded, the grid's horizontal scroll bar shows because the content of the grid is more than total grid width.  Then I click on the Resize button to resize the grid.  And the grid looks good.

Then increase the view port width by dragging its left border.  Now the column width is still the same, and there is a big gray empty area in the grid.

In order to make the grid look nice, I have to hit the resize button one more time.  And in order to make this seamless, I have to resize the grid programmatically in a resize event, right?

I was wondering: instead of setting the column width in pixel, can I set the width in percentage?

**Comment by ceolter** [comment]
> In order to make the grid look nice, I have to hit the resize button one more time. And in order to make this seamless, I have to resize the grid programmatically in a resize event, right?

--> yes that's right. maybe in the future in put a hook in, to resize when the grid resizes, but it's not on my immediate list.



> I was wondering: instead of setting the column width in pixel, can I set the width in percentage?

--> again, that's right. the grid is laid out in pixel perfect sizing. although percent sounds nice, the implementation of it is more awkward.

**Comment by togakangaroo** [comment]
what's the story on this? Is column percentage sizing just flat out not possible?

**Comment by sahilgandhi15** [comment]
any progress on this?

**Comment by teuf22** [comment]
Evaluating ag-grid for a new project and very pleased so far. However, column percentage width is required for the project. Any plan for this, or at least a workaround ?
Thanks

**Comment by linuradu** [comment]
With this approach you can somehow simulate "width percentage".
1. Write your approximate desired width(s) with classic approach.
2. Use the following config.

```
var gridOptions = {
    onGridSizeChanged: () => {
        gridOptions.api.sizeColumnsToFit();
    }    
    ...other gridOptions
};
```

**Comment by teuf22** [comment]
@linuradu Thanks but sizeColumnsToFit will not preserve the percentage. The project requirement is that the columns have a fixed percentage width, regardless of their content. I could overwrite widths in onGridSizeChanged (after calculating based on the new grid size) but this seems hacky to me.

**Comment by m-farahmand** [comment]
I think a good workaround could be use vw instead of percent

**Comment by pranshu1995** [comment]
> I had this problem and have been forced to use vw and @media to solve it.
> **Is there a good workaround?**

My workaround is to calculate the width of the parent div of AG-Grid and calculating pixels by percentage to be assigned to a particular column. Here's the solution I using jQuery :

```
  function columnWidth(id, percentage){
    var div = $("#" + id);  // HTML ID of Grid
    var parent = div.parent();
    var width = parent.width() * percentage/100;  // Pixel calculation
    return width;
}

var colDefs = [
       {
         field: "name",
         width: columnWidth("myGridId",25)
       } 
]
```
This worked fine for me.
