### ISSUE TITLE
rowClass only works if a function

### ISSUE THREAD

**Issue by greglockwood** [ceolter/angular-grid#230]
According to [the documentation](http://www.angulargrid.com/angular-grid-grid-options/index.php):

> rowClass	Class to use for the row. Can be string, array of strings, or function.

However, when I set this to a string, in `RowRenderer.prototype.addClassesToRow()`, you have the following line which breaks:

    var extraRowClasses = this.gridOptionsWrapper.getRowClass()(params);

because `getRowClass()` just returns the value of `rowClass`, which if a string or array of strings, is not invokable.

I'll change it to a function for now, but I recommend either updating the documentation or fixing this bug.

Thanks for all your amazing hard work, btw!

**Comment by ceolter** [comment]
thanks for raising

**Comment by ceolter** [comment]
fixed in 1.11.1
