### ISSUE TITLE
Vertical scrolling is quite slow with 10,000 rows ad 25+ columns

### ISSUE THREAD

**Issue by elaijuh** [ceolter/angular-grid#231]
When number of coloumns is less than 10, it seems to be OK, though.

**Comment by ceolter** [comment]
i don't experience this. what browser are you using?

**Comment by elaijuh** [comment]
chrome 35

**Comment by elaijuh** [comment]
so comparing to horizontal scrolling, the vertical scroll bar is not quite following the mouse

**Comment by ceolter** [comment]
ok, will take a look, see if i can speed it up. however the scrolling is pretty fast on my machine.

**Comment by elaijuh** [comment]
@ceolter , if you already know some tricks can be applied, when do you estimate i can see the scrolling speed magic? that might drive me to decide which lib to use, angularGrid or ui.grid :)

**Comment by ceolter** [comment]
tempted to say this weekend, but am already very busy!!!! this weekend? if not, the weekend after??

**Comment by ceolter** [comment]
if your 50/50, i'm working on a very cool sidebar to allow column visibility, reorder and grouping, all with drag and drop. that should help push you!!

**Comment by elaijuh** [comment]
or maybe a minimal viable demo just to show the speed under big volume? for the sidebar, i would expect it to be a button at the right up side corner of the grid, that's surely a brilliant feature which i am looking forward to.

**Comment by ceolter** [comment]
@elaijuh are you looking to do advanced cells with the cellRenderers? i've spent some time looking into this tonight, and it appears to be the dom manipulation that i am doing in creating the cells that's slowing it down. if i just created the rows as one big string of HTML, then it would render much more quickly (as i'd just give the html to the browser in one go, rather than calling multiple DOM methods). I wonder, if you are not intending to do complex cell customisations, maybe I put in a 'fast switch' where it just does string based rendering (which means you won't be able to do advanced stuff in your cellRenderer either).

**Comment by elaijuh** [comment]
i am not doing advanced DOM rendering by cellRenderers, but some raw data passed in could be Date/Boolean object. the thing is even if i open your test drive http://www.angulargrid.com/example.html, i still feel slow vertical scrolling with 50000 rows.

**Comment by ceolter** [comment]
ok, it's on my list to make vast improvements here. but it's going to be a big job, so i can't promise anything in the short term.

with my example, if i take out all the cell renderers (ie just to built-in plain text rendering) it does speed things up by about 50%. the problem appears to be the dom interaction IE does, which isn't such a big deal with the other browsers.

**Comment by elaijuh** [comment]
i think new ngGrid 3 vertical scrolling is acceptable, except for it's flashing white

**Comment by ceolter** [comment]
ouch!!!!!!  . .. . . now i can't have them with one up on me!!!!!! . . . . . . . looks like i've some work to do . . . .

**Comment by elaijuh** [comment]
lol, easy man, you are one man team right? i am working for bank either, i know your feelings, cheers!

**Comment by ceolter** [comment]
yea one man team. i can't take help from others because i'm very particular about how i want things done :) and yea i'm working for a bank.

**Comment by AvishekNath** [comment]
Hi Ceolter, Hope u r doing well. 
I am facing slow rendering f rows issue when I do vertical scrolling in IE11. Can u please suggest me something to speed it up.

**Comment by ceolter** [comment]
i'm working on performance improvements at the moment, should speed it up. the next major release (this coming weekend???) should have it.

in the mean time, these pointers:
a) avoid angularjs inside the grid
b) if using custom cell renderers, return strings of html (do not construct dom elements)

**Comment by ceolter** [comment]
all vertical scrolling issues should now be gone. my example 'test drive' works fine on internet explorer (thanks to a new feature called 'scroll lag'), chrome, safari and firefox. interested to get feedback :)

**Comment by AvishekNath** [comment]
Hi Ceolter, 

Thanks a lot for spending time on this. Its working fine in IE 11 now. The only issue is, when we use mouse scroll wheel for scrolling up/down, it again lags. Is there is any way to control the vertical scrolling when we use mouse scroll wheel. Please suggest. 

Thanks,
Avishek

**Comment by ceolter** [comment]
Nope, no suggestion. It doesn't lag for me in IE with mouse wheel so
difficult to troubleshoot.

However given its only ie and not all users of ie, don't think it's a major
issue.

**Comment by elaijuh** [comment]
@ceolter , good job!

**Comment by AvishekNath** [comment]
Hi Ceolter,

I just took angular grid update (1.12.1) for handling scroll lag in IE11, which is now enabled by default. But I didn't see any improvement while vertical scroll. It behaves same as earlier version. Is version 1.12.1 has virtual dom implementation that you are talking about. (in IE11)

Did I miss something. Please suggest

**Comment by ceolter** [comment]
yes 1.12.1 has the vdom. makes ie redraw twice as fast.

however the biggest performance gain for IE and Safari (not the others) comes with the 'scrollLag' feature. when you are scrolling, the grid listens to the scroll events to update the dom. in IE and Safari, this gave a very 'jumpy' scrollbar (on my machine). with this enabled, then it will wait for 50ms and do nothing if another scroll event comes in. that means, if you are scrolling, the grid will not redraw until the scroll has stayed still for 50ms. this allows you to use the scrollbar without jumps until you come to a steady position.

see the gridOptions suppressScrollLag and isScrollLag
http://www.angulargrid.com/angular-grid-grid-options/index.php

try turning this feature on and off, see if you can notice the difference.

to make sure it's behaving (ie picking up your options), the logic is done in gridPanel.ts requestDrawVirtualRows().

interested in your feedback. all my test were done on one laptop with one version of each browser.

**Comment by AvishekNath** [comment]
Thanks for your suggestion. 

I am doing a testing in IE11 with feature enabled. Now, if I scroll with using scroll arrows, it works good. But, when you use scrollbar square button to forcefully drag up/down to a large amount. It  shows lag in rendering the rows in IE11.

I am still doing testing, will update u soon.

**Comment by ceolter** [comment]
can we close this issue?

**Comment by AvishekNath** [comment]
Sure Ceolter. Thanks a lot for your support. 

Thanks,
Avishek
