### ISSUE TITLE
Grand Total?

### ISSUE THREAD

**Issue by oliverzy** [ceolter/angular-grid#232]
I'm wondering how to achieve grand total, in the examples, it seems that I can create multiple level grouping and for each group, I can have its total.

Is it possible in angular-grid?

**Comment by ceolter** [comment]
yes it is possible to have multi level groups with each one containing the total of all it's children (and sub children)

**Comment by oliverzy** [comment]
maybe my question is not clear. For example, I have a grid group by country, I would like to have a group called 'All' that show aggregation for all country, how can I do in angular-grid?

**Comment by ceolter** [comment]
ah - you want to reduce the rowset? ie you could have 10 countries, each with 20 cities, giving 2000 rows, you want a grid with just 10 rows (not drilldown), is that right?

**Comment by oliverzy** [comment]
Well, sorry for my explanation. Let's take the example http://www.angulargrid.com/example.html.
In that example, the requirement is that the grid can have a fixed footer which can display the grand total for all countries balance amounts.

**Comment by ceolter** [comment]
ok, i got you. you want floating rows at the bottom, or a totaliser row. now this is not supported. floating rows at the bottom is already raised in:
https://github.com/ceolter/angular-grid/issues/45

**Comment by oliverzy** [comment]
Exactly. Thanks for consideration.
