### ISSUE TITLE
resize column UI breaks

### ISSUE THREAD

**Issue by loongdefect** [ceolter/angular-grid#233]
When resize column with small width will cause UI breakage .
See more pictures:

![Break UI](https://c2.staticflickr.com/6/5608/18853314151_17b772706b_z.jpg)

**Comment by ceolter** [comment]
i don't experience this. i tried with the resizing example in the docs, by making all cols (except the first) the minimum size, and then hitting 'sizeColsToFit()' button and it worked fine.

is it browser specific? can you provide a plunker?
