### ISSUE TITLE
Comparator function argument list varies for filter and sort function calls

### ISSUE THREAD

**Issue by sudevkk** [ceolter/angular-grid#234]
The data1 and data2 parameters are missing on the comparator function call making the function not usable across sort and filter.

**Comment by ceolter** [comment]
I can't reproduce. I check my test drive (the 'bought' col has a comparator) and debugged through the following:

>function booleanComparator(value1, value2) {
>    var value1Cleaned = booleanCleaner(value1);
>    var value2Cleaned = booleanCleaner(value2);

and it's working???

**Comment by sudevkk** [comment]
Ok, explaining the issue I faced below in details.

I have a comparator function which uses the four params (value1, value2, data1, data2), and the sort works very well. But for some reason the Filter wont work on this coloumn. And it looks like the reason is 'Filter' calls the comparator method internally but without the data1, data2 parameters. Though didn't check the code for this.

**Comment by ceolter** [comment]
The code is passing in the data1 and data2, this is the code:
[code]
    function compare(objA, objB, colDef){
        var valueA = that.getValue(objA.data, colDef, objA);
        var valueB = that.getValue(objB.data, colDef, objB);
        if (colDef.comparator) {
            //if comparator provided, use it
            return colDef.comparator(valueA, valueB, objA, objB);
        } else {
            //otherwise do our own comparison
            return utils.defaultComparator(valueA, valueB, objA, objB);
        }
    }
[/code]

The function uses objA and objB to get valueA and valueB, so I don't see how the values could be working if the obj was missing . . .. ?????

**Comment by sudevkk** [comment]
Ok, looked like it did not when it gets called from the Filter method. Anyway will check again and update rather than wasting your time!
