### ISSUE TITLE
Number filter when in server filtering mode resets the filter data once the server call has returned

### ISSUE THREAD

**Issue by jonsamwell** [ceolter/angular-grid#236]
Hi,

Awesome grid thank you so much!  I've doing server side paging + filtering and when I have a number filter type on a numeric column the filtering popup behaves very strangely and resets all data after it changes once i.e. the type changes or a value is entered in the input.  If you change the filter type it immediately calls the server to get data regardless of if there is a value in the input and once the server call returns all the data in the filter popup is removed and the type dropdown resets to the original equals value.

Here is a very basic Plunker which reproduces the issue:

http://plnkr.co/edit/NqFHsNQU5cz7sRFrb8Ur?p=preview

Another nice idea might be to have a debounce function on the change method of the text input otherwise there is a server call for every key press.

Thanks,

Jon

**Comment by ceolter** [comment]
Yes i'm aware of this, you need to do this:
{headerName: "Age", field: "age", width: 90, filter: 'number', filterParams: {newRowsAction: 'keep'}}

Basically the filters by default clear themselves when new data is loaded - they are not aware of been using server side  or not - so need to turn this off to behave as you expect.
