### ISSUE TITLE
Header Renderer for specific Column

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#237]
Is it possible to render the custom header for a specific column? Like we can do for Cell by setting up template/templateUrl

**Comment by ceolter** [comment]
yes it is. cell headerRendereing in documentation.

**Comment by ammar91** [comment]
I can not find here: http://www.angulargrid.com/angular-grid-column-definitions/index.php

Can you please me an example

**Comment by ceolter** [comment]
http://www.angulargrid.com/angular-grid-header-rendering/index.php

**Comment by ammar91** [comment]
Is this work specific to single cell header?

**Comment by ammar91** [comment]
Also, there isn't way to specify template url for specific cell header?

**Comment by ceolter** [comment]
yes. two options. 1) set it on gridoptions (for all cols) or 2) set it on colDef (for a specific col)

**Comment by ammar91** [comment]
Right.

By the way, do you have plan to introduce headerTemplate/headerTemplateUrl? Some time there is a need to render complex html for a header, so we can specify the path like we do for a cell currently instead of defining inline template inside headerRenderer function.

**Comment by jongravois** [comment]
+1 (actually, +10)

**Comment by ceolter** [comment]
for headerTemplate, does this imply you will be using angular in your template???

**Comment by jongravois** [comment]
I definitely will

Jon

**Comment by ammar91** [comment]
Yes.

**Comment by ammar91** [comment]
Currently I have to define inline template for one of my column header:

         {
                   suppressMenu: true,
                   suppressSorting: true,
                   width: 100,
                   template: '<a data-ng-class="data.singlesFlag && \'flagged\' || \'unflagged\'" data-ng-click="vm.flaggedSingle(data)" href="#" class="glyphicon glyphicon-flag"></a>',
                   headerCellRenderer: function () {
                       return '<div class="dropdown" dropdown-append-to-body>' +
                       '<a href="#" class="glyphicon glyphicon-flag dropdown-toggle" data-toggle="dropdown" aria-expanded="true"></a>' +
                           '<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">' +
                           '<li data-ng-click="vm.clearAllFlaggedSingle()" role="presentation"><a role="menuitem" tabindex="-1" href="#">Clear All Flags</a></li>' +
                           '<li data-ng-click="vm.flagAllSingles()" role="presentation"><a role="menuitem" tabindex="-1" href="#">Select All Flags</a></li>' +
                           '<li data-ng-click="vm.emailFlagged()" role="presentation"><a role="menuitem" tabindex="-1" href="#">Email Flagged</a></li>' +
                           '</ul>' +
                        '</div>';
                   }
               },

And the problem I am going throw it's not opening up the dropdown. However I already set the angularCompileHeaders:true .. Not sure what's going wrong.

**Comment by jongravois** [comment]
I am at least using a private function to clean up columnDefs a bit:

var columnDefs = [
    {
        displayName: 'Pending',
        field: '',
        suppressSorting: true,
        templateUrl: './pending.icons.html',
        width: 92,
        suppressSizeToFit: true,
        headerCellRenderer: pendingHdr,
        headerTooltip: 'On/Off'
    }
];


function pendingHdr(params) {
    //console.log('before', params);
    if(params.context.pending_view){
        return '<div style="text-align:center !important;"><span class="pendicon glyphicon glyphicon-exclamation-sign" ng-click="sortPending()" style="color:#006837;"></span></div>';
    } else {
        return '<div style="text-align:center !important;"><span class="pendicon glyphicon glyphicon-exclamation-sign" ng-click="sortPending()" style="color:#aaaaaa;"></span></div>';
    }
}

**Comment by ceolter** [comment]
can't really comment on why the dropdown isn't appearing. you can test if angular is working by putting in {{2+2}} (see if 4 comes out) into your template. at least then you know if it's the grid that's broke or something on your end.
