### ISSUE TITLE
Any chance there will be .d.ts (TypeScript definitions) any time soon?

### ISSUE THREAD

**Issue by Alber70g** [ceolter/angular-grid#240]
Any chance there will be .d.ts (typescript definitions) any time soon?

**Comment by ceolter** [comment]
yes, in a few weeks. i'm giving serious thought to moving the whole thing to TS.

**Comment by Alber70g** [comment]
Great! I'll be waiting for it :) Thanks for the fast response.

**Comment by greglockwood** [comment]
@Alber70g You may be best to wait for the "official" types, but I created a set of interfaces for the API you could use for now if you prefer. You can check it out here: https://gist.github.com/greglockwood/67ea53a5f43852ba24c4. Names are not great, I didn't follow the usual "I" prefix for interfaces, and it is all in the one namespace/module. But maybe you can refactor it into something you prefer.

**Comment by Alber70g** [comment]
Wow, thanks a lot. I'll be using this and updating when needed. Thanks again!

**Comment by greglockwood** [comment]
@Alber70g I would be interested in seeing what improvements you make to it. Can you please post them here?

**Comment by Alber70g** [comment]
Yes when I'm using it, we are still starting up the project and when we are ready to use the .d.ts I'll certainly will fork you d.ts
