### ISSUE TITLE
Grid render data in different order

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#242]
The server return data in descending order over the int field that is a primary key of a table. But I noticed when data render, it shows record in a order that is different than the original one.  Is there anything I need to define in order to render the data as it is?

**Comment by ceolter** [comment]
if no sort or group or filter, then the order should be as you provide it. if this is not the case, then something is wrong. you could also use the API to sort the data via the grid after the data load

**Comment by ammar91** [comment]
I can sort the grid using the API but the problem is, the field I want to sort with not bound to the grid. In other words I don't have column definition for a field that I want to sort with, so how it would be done?

Also, I noticed when I fetch initial 10 rows, it shows in correct order and when I change the page size to 20, it start displaying in wrong order even though the server return sorted data.

**Comment by ceolter** [comment]
got it, i introduced a bug when putting in the sorting API :(

it's checked into master (but i wouldn't advise grabbing master at this time, it's not ready for the next release).

if you want to fix it locally, you can hack, basically change:
```
if (sortingOptions.length >= 0) {
```
to 
```
if (sortingOptions.length > 0) {
```

**Comment by ammar91** [comment]
Thanks so much. I fixed it locally and works great:)
