### ISSUE TITLE
get GridOptions in cellDoubleClicked function

### ISSUE THREAD

**Issue by vladdvs** [ceolter/angular-grid#243]
I dynamically create several grids
I have attached to them one function cellDoubleClicked
I need to find from wich one grid function was called
how can i do that?

**Comment by ceolter** [comment]
don't attach one function, attach a different function to each. all these several grid functions can then call another function, passing in another argument with the grid details.

**Comment by vladdvs** [comment]
i can't becouse i keep gridOPtions in JSON in localstorage of brouser. And JSON does not allow for function

**Comment by ceolter** [comment]
ok - all i can say for now, is that it's not possible.

**Comment by vladdvs** [comment]
thanks))
