### ISSUE TITLE
CheckBox selection with multiple selection cell click bug

### ISSUE THREAD

**Issue by aalex675** [ceolter/angular-grid#247]
When a checkboxSelection column is included in a grid with rowSelection: 'multiple', clicking in the checkbox cell (but not on the checkbox) clears other selected cells.

Steps to reproduce:
1. Open the example project: http://www.angulargrid.com/example-data-grid/basic.html
2. Click the checkboxes on the first 3 rows.
3. Click in the checkbox cell, but not on the checkbox on the 4th row.
Result: The 4th row is selected and the first 3 rows are deselected.

I think it would be a usability improvement to make clicking anywhere in the checkbox cell the same as clicking the checkbox itself (especially on grids where the row height might be a lot taller than the example).

**Comment by ceolter** [comment]
afraid i disagree!

clicking on the row is normal row selection. the grid is designed that if you click on the row, it unselects other rows. to do multi-select with row selection, you have to hold down shift.

to get it behaving 'more nicely', then use the gridOption.suppressRowClickSelection=true

that way, the checkbox is used exclusively for selection, giving a consistent feel.

**Comment by BasitAli** [comment]
Sorry for bringing up this old issue but I kind of agree with the issue. Clicking on the checkbox cell should be equivalent to clicking on the checkbox. I agree with you on deselecting all other rows when clicking on another other cell. Trying to implement a custom renderer to implement this behaviour. Any tips would be helpful.
