### ISSUE TITLE
How to update current page rows from the server

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#251]
I want to update the current page rows from the server after some action has been performed. Let say, If I am on Page 2 and the current rows that are visible 20 to 40. When some action being performed on the grid, I want to update the current page only and ask server to return me back 20 t0 40 rows. Is there any method I could use who give me the information about start and end row?

**Comment by ceolter** [comment]
nope. already an issue open for API on top of pagination.

what you could do is keep track of what was last loaded via your data source.
