### ISSUE TITLE
remove inline sourcemap from dist Javascript

### ISSUE THREAD

**Issue by robshep** [ceolter/angular-grid#253]
Hi,

I'd like to request that the inline sourceMap present in the packaged javascript is removed from the Javascript file and externalised.

1) It breaks my own bundling and minification as there's a sourceMap blob in the middle of other scripts.
     I have to hack the build script to ensure it always last to be concatenated.
2) Even though I have my own sourceMap, this is the one that Chrome references and I can't see my own source references.
3) it's 160% of the size of the source itself, and is only really useful in this format for agGrid development itself.

Cheers

angularGrid is excellent by the way!

**Comment by ceolter** [comment]
makes sense. will stick this onto my list. thanks.

**Comment by ceolter** [comment]
since moving to typescript, i've reviewed this. the maps are not included when i do releases now.
