### ISSUE TITLE
Setting a datasource with any method throws TypeError on 1.9.2

### ISSUE THREAD

**Issue by ninety7** [ceolter/angular-grid#255]
Just tried to add a datasource with any method to the grid options and this is the error message shown:
Using ready():
```
TypeError: Cannot read property 'setDatasource' of null
    at Grid.setDatasource (grid.js:202)
    at Object.Grid.addApi.api.setDatasource (grid.js:512)
```
Setting datasource property before grid is initialized:
```
TypeError: Cannot read property 'setDatasource' of null
    at Grid.setDatasource (grid.js:202)
    at new Grid (grid.js:77)
```
Using onNewDatasource():
```
TypeError: Cannot read property 'setDatasource' of null
    at Grid.setDatasource (grid.js:202)
    at Object.Grid.addApi.api.onNewDatasource (grid.js:515)
```

**Comment by ninety7** [comment]
I can confirm that this error happens when the `dontUseScrolls: true` option is used. Any idea why the pagination controller is not initialized when this option is used?
```
if (useScrolls) {
    paginationController = new PaginationController();
    paginationController.init(this.ePagingPanel, this, gridOptionsWrapper);
}
```

**Comment by ceolter** [comment]
you can't do paging when 'dontUseScrolls', it's not supported.

the dontUseScrolls is intended for printing a grid (i'm going to change it's name soon), the grid is laid out differently. so you just can't do datasource things when in print mode.
