### ISSUE TITLE
CSS conflict with material design

### ISSUE THREAD

**Issue by joebordes** [ceolter/angular-grid#256]
Hi,

I am trying to use angular grid with ngmaterial (Material Design). The grid works correctly if I load the angular-grid.css but not if I load either theme-fresh nor theme-dark

http://plnkr.co/edit/HaV1kT?p=preview

**Comment by ceolter** [comment]
you always need angular-grid.css

the themes are option that should be used in addition to the core css

see the examples.

also that's whats mentioned in the docs!!

**Comment by joebordes** [comment]
Sorry to bother.
Thanks.
