### ISSUE TITLE
QuickFilter not taking valueGetter value into account

### ISSUE THREAD

**Issue by a1martin** [ceolter/angular-grid#257]
looking at the code in InMemoryRowController.prototype.aggregateRowForQuickFilter it seems that only field value is put to aggregated text. Thus the user cannot search using values obtained from valueGetter.

**Comment by a1martin** [comment]
at the moment quick fix for me was changing the aggregateRowForQuickFilter method as follows:

InMemoryRowController.prototype.aggregateRowForQuickFilter = function(node) {
    var aggregatedText = '';

    for(var i = 0; i < this.columnModel.getAllColumns().length;i++){
        var colDefWrapper =  this.columnModel.getAllColumns()[i];
        var data = node.data;
        var value = this.getValue(data,colDefWrapper.colDef,node);
        //var value = data ? data[colDefWrapper.colDef.field] : null;
     
	   
        if (value && value !== '') {
            aggregatedText = aggregatedText + value.toString().toUpperCase() + "_";
        }
    };
    node.quickFilterAggregateText = aggregatedText;
};

Really nice grid by the way!

**Comment by Fangmingdu** [comment]
Just started trying to use quick filter today. This is also an issue for me.

**Comment by ceolter** [comment]
yea i'll fix this soon!!

**Comment by ceolter** [comment]
this is working now.
