### ISSUE TITLE
Changing Width and Height

### ISSUE THREAD

**Issue by bkirk1012** [ceolter/angular-grid#259]
Hi,

I am using angular grid in a directive, and set the height and width of the grid through the directive, which updates the height and width values. These changing values are set via ng-style.  The documentation states: If the width and / or height change after the grid is initialised, the grid will automatically resize to fill the new area - I am not seeing this functionality. I tried using percentage values for the width and height and still did not see the desired effect.  Is there something I am missing? Thanks in advance!

Best,

Billy

**Comment by ceolter** [comment]
in the last release (1.10.0), this functionality was taken out. i'll do a
mini release and put this back in (1.10.1). will do first thing in the
morning.

basically, the resize is now triggered by the window resizing. i'll change
it back to the way it was (which was polling the size every few hundred
milliseconds)


On 22 June 2015 at 21:52, Billy Kirk <notifications@github.com> wrote:

> Hi,
>
> I am using angular grid in a directive, and set the height and width of
> the grid through the directive, which updates the height and width values.
> These changing values are set via ng-style. The documentation states: If
> the width and / or height change after the grid is initialised, the grid
> will automatically resize to fill the new area - I am not seeing this
> functionality. I tried using percentage values for the width and height and
> still did not see the desired effect. Is there something I am missing?
> Thanks in advance!
>
> Best,
>
> Billy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/259>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by bkirk1012** [comment]
Thank you (as always) for the swift response! The functionality I am looking for was included in Version 1.4.1.  Specifically, I am looking at changes in the sizeColumnsToFit function within the grid API.  In the most recent version, it appears to get the available width variable through the following:
   
        var availableWidth = that.gridPanel.getWidthForSizeColsToFit();

Whereas in 1.4.1, this is done like so:

       var availableWidth = that.eBody.clientWidth;

It looks like the getWidthForSizeColsToFit method in gridPanel uses this line - but it seems to pull the old clientWidth off the eBody, i.e. it still does not pull the updated width when the change is made. Instead of pulling the updated with, it pulls the previous width of the grid.

For reference - I am setting my height and width like so:

       <div ag-grid="mygrid.gridOptions" class="theme-fresh" ng-style="{'height': mygrid.gridHeight, 'width': mygrid.gridWidth}"></div>

**Comment by ceolter** [comment]
this is working in my demo - the documentation page on resizing - can you advise if this is broken for you? or is it just in your app it's broken?

**Comment by bkirk1012** [comment]
Ended up fixing the issue.  Thanks!

**Comment by ceolter** [comment]
cool. thanks for closing the issue.

**Comment by chiptus** [comment]
@bkirk1012 Can you tell us how did you fix it? Might be useful for me
