### ISSUE TITLE
Double scroll bar issue if grid's parent container is a fixed height

### ISSUE THREAD

**Issue by jonsamwell** [ceolter/angular-grid#261]
Hi,

If grid is within a fixed height container it will take the parent container height for the rows div (id: centerRow) and the paging div (id: south) will add another 38px or so to the overall height resulting in the parent container having a vertical scrollbar and the row container having a vertical scrollbar.  The height of the rows div should be calculated taking into account the height of the pagination container to avoid double scrollbars.

**Comment by jonsamwell** [comment]
It appears that in the function 'BorderLayout.prototype.layoutHeight' the height of the south container is always zero.  So your calculation to set the height of the centerRow container is correct it's just that the south container's  height isn't correct (maybe because it hasn't got any content at that point?)

**Comment by ceolter** [comment]
i've just done an update, 10.1.1, now the grid checks it's size every 500ms. can you advice is that fixes it? if not, i fear you might be experiencing something that's only for a particular browser / platform / version.

**Comment by jonsamwell** [comment]
@ceolter thanks for the quick response!  I'll give it a go :-)

**Comment by ceolter** [comment]
can you advise, is this fixed?

**Comment by jonsamwell** [comment]
Sorry for the delay in getting back to you.  Unfortunately this hasn't fixed the problem.

**Comment by jonsamwell** [comment]
I'm going to do a reproducing Plunker so you have something to work with.

**Comment by ceolter** [comment]
thanks

**Comment by jonsamwell** [comment]
I cannot reproduce this now in a plunker so closing.
