### ISSUE TITLE
Use of .bind() problematic for PhantomJS

### ISSUE THREAD

**Issue by greglockwood** [ceolter/angular-grid#262]
Unfortunately, there is a known issue where PhantomJS, which we (along with many others) use to run unit tests in, don't have `Function.prototype.bind()` defined, which means that loading and running the angular grid code will cause it to exception and abort the tests.

If you could find some alternative to using the native `.bind()`, that would be great (Underscore/Lodash both have one) or use a polyfill, that would be helpful.

Otherwise, I guess I could try making sure we include a polyfill in our tests prior to loading the `angular-grid.js` file.

**Comment by ceolter** [comment]
noted. thats crap!!!!! i use bind a lot, it's very useful!!! i'll create my own polyfil (so i don't bring in a dependency).

**Comment by ceolter** [comment]
what do other libraries (ie angularjs) do? thinking about it, the 'bind' operation is quite core to functional programming . . . .

**Comment by greglockwood** [comment]
Angular has it's own [`bind()`](https://docs.angularjs.org/api/ng/function/angular.bind) function that it uses instead.

I did find a workaround for this issue, which was to use [this PhantomJS polyfill](https://www.npmjs.com/package/phantomjs-polyfill) from NPM and include that first up in my list of files to load for unit testing. So this issue could be considered lower priority now.

**Comment by ceolter** [comment]
thanks for the feedback

**Comment by ceolter** [comment]
given this is a workaround, and it's more an issue with PhantomJS, am closing this issue.
