### ISSUE TITLE
TypeError: this.gridOptionsWrapper.getRowClass(...) is not a function

### ISSUE THREAD

**Issue by dereklin** [ceolter/angular-grid#265]
Here is my plunker: http://plnkr.co/edit/RTdKWTcBfGcFGlosAOlf?p=preview

I have added 
```
rowClass: "angular-grid-row"
```

in
```
vm.gridOptions = {
      columnDefs: columnDefs,
      rowData: rowData,
      rowClass: "angular-grid-row"
  };
```
I am getting:

```
TypeError: this.gridOptionsWrapper.getRowClass(...) is not a function
    at r.addClassesToRow (angular-grid.js:4)
    at r.createRowContainer (angular-grid.js:4)
    at r.insertRow (angular-grid.js:4)
    at r.ensureRowsRendered (angular-grid.js:4)
    at r.drawVirtualRows (angular-grid.js:4)
    at r.refreshAllVirtualRows (angular-grid.js:4)
    at r.refreshView (angular-grid.js:4)
    at r.updateModelAndRefresh (angular-grid.js:2)
    at new r (angular-grid.js:1)
    at new r (angular-grid.js:1)
```

**Comment by ceolter** [comment]
small bug in the grid, it is expecting a function. to get around this, just
use a function to return back the class (or array of classes).

eg:

vm.gridOptions.rowClass = function(params) {
return 'my-class';
}

or
vm.gridOptions.rowClass = function(params) {
return ['class-one','class-two'];
}


On 23 June 2015 at 18:52, dereklin <notifications@github.com> wrote:

> Here is my plunker: http://plnkr.co/edit/RTdKWTcBfGcFGlosAOlf?p=preview
>
> I have added
>
> rowClass: "angular-grid-row"
>
> in
>
> vm.gridOptions = {
>       columnDefs: columnDefs,
>       rowData: rowData,
>       rowClass: "angular-grid-row"
>   };
>
> I am getting:
>
> TypeError: this.gridOptionsWrapper.getRowClass(...) is not a function
>     at r.addClassesToRow (angular-grid.js:4)
>     at r.createRowContainer (angular-grid.js:4)
>     at r.insertRow (angular-grid.js:4)
>     at r.ensureRowsRendered (angular-grid.js:4)
>     at r.drawVirtualRows (angular-grid.js:4)
>     at r.refreshAllVirtualRows (angular-grid.js:4)
>     at r.refreshView (angular-grid.js:4)
>     at r.updateModelAndRefresh (angular-grid.js:2)
>     at new r (angular-grid.js:1)
>     at new r (angular-grid.js:1)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/265>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.
