### ISSUE TITLE
Grid shows only when dontUseScrolls: false

### ISSUE THREAD

**Issue by dereklin** [ceolter/angular-grid#266]
Here is my plunker: http://plnkr.co/edit/ZF4vi7LQM0rizyK9lMkR?p=preview

When you load it, no grid is shown.

Go to app.js, change
```
dontUseScrolls: false
```
to
```
dontUseScrolls: true
```
Now the grid shows.

**Comment by ceolter** [comment]
You need to specify height on your grid div.

**Comment by dereklin** [comment]
When using 1.9.2, I don't have to specify div height.  In fact, the grid auto grows with the number of rows I have.  I think that's nice.

Does it mean the "auto grow" feature will no longer work if dontUseScrolls is false?

**Comment by ceolter** [comment]
Yes, that feature is now gone. Actually it wasn't a feature, it was
accidental.

**Comment by dereklin** [comment]
Would it be possible to bring that "feature" back as an option? autoGrow true/false?

**Comment by ceolter** [comment]
In time yes. Not sure how much coding it would take, as would have to code
for it now. Before it was by accident. So not a switch I can just enable :(

The layout as it is now is foundations for showing / hiding other parts,
such as floating rows, other headers / footers etc.
