### ISSUE TITLE
Autofit columns at init

### ISSUE THREAD

**Issue by ocombe** [ceolter/angular-grid#269]
Hello,

this is probably a problem with my config (or some options that I haven't found), so if you could tell me where I'm wrong that would be appreciated.

I want my table to auto fit its width on init without having to call: `api.sizeColumnsToFit()`.
My grid options are the following:
```js
var columnDefs = [{
    headerName: "Campaign",
    field: "campaign",
}, {
    headerName: "TV Channels",
    field: "tvchannels"
}, {
    headerName: "# Spots",
    field: "spots"
}, {
    headerName: "GRP",
    field: "grp"
}, {
    headerName: "Cost",
    field: "cost"
}];


var rowData = [{
    campaign: "C1",
    tvchannels: "TF1",
    spots: 55,
    grp: 10,
    cost: 35000
}, {
    campaign: "C1",
    tvchannels: "FRANCE 2",
    spots: 55,
    grp: 10,
    cost: 35000
}, {
    campaign: "C1",
    tvchannels: "FRANCE 3",
    spots: 55,
    grp: 10,
    cost: 35000
}, {
    campaign: "C1",
    tvchannels: "CANAL +",
    spots: 55,
    grp: 10,
    cost: 35000
}, {
    campaign: "C1",
    tvchannels: "Arte",
    spots: 55,
    grp: 10,
    cost: 35000
}, {
    campaign: "C1",
    tvchannels: "M6",
    spots: 55,
    grp: 10,
    cost: 35000
}];

$scope.gridOptions = {
  columnDefs: columnDefs,
  rowData: rowData,
  suppressVerticalScroll: true
};
```

When the grid is initiated, there is an horizontal scrollbar because the columns don't fit into the container.
I tried adding `api.sizeColumnsToFit()` into the `ready` callback but it doesn't change anything.
I added `api.sizeColumnsToFit()` into the `ready` callback with a timeout 0 and it didn't changed. Then with a timeout 1000ms and it worked but you will see the original table (with scrollbars) and then it will resize to fit (after 1s).

Is there something wrong here? It should be working in the `ready` callback without a timeout, shouldn't it?

Maybe it's because I don't have a fix width for my container (it uses the flexbox model)?

**Comment by ocombe** [comment]
And by the way, how are the widths of the columns computed? Right now each column takes 200px of width, but there is a lot of margin left, it could be only 130px without any problem.

**Comment by ceolter** [comment]
putting 'sizeColsToFix' in ready does work, see the example on this page:
http://www.angulargrid.com/angular-grid-refresh/index.php

maybe your grid is not visible when you call it, so the width is returning back as zero to my function?

the widths are computed as follows:
+ each col has a default width (if not defined, there is a default width assigned by the grid)
+ the 'remaining' space is calculated
+ the 'remaining' space is distributed evenly between each col

so if two cols, 50px and 100px each, and 50px to spare, the cols end up 75px and 125px

ps am closing this issue, as it's not something wrong with the grid! questions best placed on the board on the website :)

**Comment by ocombe** [comment]
Well calling `$scope.gridOptions.api.sizeColumnsToFit();` in the ready callback doesn't work for me... no idea why.
The grid is not hidden or nothing, it just takes 500ms to render for some reasons.

**Comment by ocombe** [comment]
Also I'm compiling the template myself before inserting it. Maybe that's the reason ?

```js
$element.html($compile('<div ag-grid="gridOptions" class="ag-hmx"></div>')($scope));
```

**Comment by ceolter** [comment]
have not used the grid in that way, so entering new territory for, am guessing the 'ready()' callback is called when you compile, before the item is inserted into the dom.

so if your compiling the element, then your also inserting it into the dom yourself, try calling 'sizeColsToFit()' after you insert into the dom???

**Comment by ocombe** [comment]
There is no callback to the html function so it doesn't change anything... BUT using a regular template (without compiling it myself) does work, the function is called as expected on ready.
Now I have to find a way to do that with $compile (because I'm lazy loading the lib and I have to wait for the files to load)

**Comment by ceolter** [comment]
quick fix . . .. poll every 20ms until the width is available (check visibility on the grid div??), then call sizeColsToFix it and stop polling???

**Comment by ocombe** [comment]
I got it working with an ng-if based on a variable that I define after the compile & dom insertion.
Hacky as hell but it works fine !

**Comment by ocombe** [comment]
Now I need to find out if I can define a max-height for the container, or if it needs a height (currently with a height of 100% and a max height the grid gets a height of 0).

**Comment by ceolter** [comment]
height of 100% should work . . . but have found on some browsers, the parent needs a height for this to work, so you end up with 100% (or something) all the way back to the root

**Comment by ceolter** [comment]
> I got it working with an ng-if based

good to know thanks

**Comment by ocombe** [comment]
Okay, I'll use a height for now

**Comment by JeffMichelson** [comment]
I must say that I'm having the exact problem that has been described by ocombe.  I have to apply a 1/2 second $timeout on the OnReady api.sizeColumnToFit() function in order to render properly.  Otherwise, the columns are rendered too wide and produce a horizontal scrollbar.  Interestingly, without the sizeColumnsToFit call, the columns naturally size to something smaller than the grid width and leave a whitespace to the right.

Just fyi...

**Comment by hollanderbart** [comment]
I was having the same issue. I solved it with the modelUpdated event call.
In HTML:
`(modelUpdated)="onModelUpdated()"`
In typescript class:
```
    private onModelUpdated() {
        if (this.gridOptions.api && this.columnDefs) {
            this.gridOptions.columnApi.autoSizeColumns(this.columnDefs);
        }
    }
```

**Comment by realavaloro** [comment]
I am also having this issue with my Angular 1.x project and agGrid 4.0.5
Furthermore, I can configure a timeout to apply the resize columns as follows:
```
private setColumnsToFit(): void {
       this.$timeout(() => {
          this.gridOptions.api.sizeColumnsToFit();
       }, 5000);
}
```
but if for example, and without modifying the grid at all, I go to another tab/view and come back, the grid is still there with the data but the columns are again as per default (not column-fitted) so I have to manually invoke that method again.

Has anybody a better solution for this?

One of the previous comments said something about constantly checking for the table width and once there is a width then the function to fit columns can be called. Is there any way to do this check through the grid api?

**Comment by stefyzx** [comment]
I wrote ag-grid as a component in Angular 1.5, and I just put this in gridOptions
`onGridReady: function($event) {
                    $event.api.sizeColumnsToFit();
                }`
without setting the default size for each column, and the resizing works well after loading all data.
Help that can help you

**Comment by congphu97** [comment]
> I am also having this issue with my Angular 1.x project and agGrid 4.0.5
> Furthermore, I can configure a timeout to apply the resize columns as follows:
> 
> ```
> private setColumnsToFit(): void {
>        this.$timeout(() => {
>           this.gridOptions.api.sizeColumnsToFit();
>        }, 5000);
> }
> ```
> 
> but if for example, and without modifying the grid at all, I go to another tab/view and come back, the grid is still there with the data but the columns are again as per default (not column-fitted) so I have to manually invoke that method again.
> 
> Has anybody a better solution for this?
> 
> One of the previous comments said something about constantly checking for the table width and once there is a width then the function to fit columns can be called. Is there any way to do this check through the grid api?

Good job! Bro

**Comment by caglarsarikaya** [comment]
> I got it working with an ng-if based on a variable that I define after the compile & dom insertion.
> Hacky as hell but it works fine !

i have same problem i am using vue.js and i am beginner could give me more detail about compile and dom i tried in every hook like mounted or beforemount or beforeupdate its not working properly i am using  this.gridApi.sizeColumnsToFit(); on beforemount when you press something the table will be fixed but i want to do it on begining of table
