### ISSUE TITLE
Allow filters to have time delay, or an apply button, for server side

### ISSUE THREAD

**Issue by ceolter** [ceolter/angular-grid#272]
http://www.angulargrid.com/forum/showthread.php?tid=2393

**Comment by dozortsev** [comment]
:+1:

**Comment by dozortsev** [comment]
Hi @ceolter. Please implement this feature on nearest release. It's so important.

**Comment by ceolter** [comment]
> Please implement this feature on nearest release. It's so important.

noted :)

**Comment by ceolter** [comment]
i opted for 'apply button', quickest to implement and get you guys out of a hole! get latest from master, or wait for this weekends release.

**Comment by jonsamwell** [comment]
Could the need to press this apply button be optionally?  This problem of the filters firing the clients 'getRows' method on ever key press is easily solved in client code via a de-bounce function on the getRows method.  I don't want to have to force my users to click apply.

```javascript
api.setDatasource({
        getRows: getDebouncedGetPageFn(),
        pageSize: 50
      });

function getDebouncedGetPageFn() {
    return _.debounce(myGetRowsFn, 500, {
      maxWait: 1500
    });
  }
```

**Comment by ceolter** [comment]
> Could the need to press this apply button be optionally?

it is option. by default, it behaves as before (ie backward compatible). to enable, you have to set an attribute "apply=true" on each filter.

**Comment by jonsamwell** [comment]
thanks!
