### ISSUE TITLE
Grouping - suppressCount with groupUseEntireRow set to true and Custom Template for Group Row

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#273]
I started implementing a Grouping feature in one of my grid and start with very basic configuration which is:
            
        var columnDefs = [
               {
                  headerName: "Name",
                  field: "name",
                  width: 100,
                  filter: agGrid.ColumnQuickFilter
              },
              {
                  headerName: "Profession",
                  field: "occupation",
                  width: 120,
                  filter: agGrid.ColumnQuickFilter
              },
              {
                  headerName: "Telephone",
                  field: "phone",
                  width: 120,
                  filter: agGrid.ColumnQuickFilter
              },
              {
                  headerName: "Email",
                  field: "email",
                  filter: agGrid.ColumnQuickFilter
              }
        ];

        var gridOptions = {
                columnDefs: columnDefs,
                enableSorting: true,
                enableFilter: true,
                enableColResize: true,
                angularCompileRows: true,
                angularCompileFilters: true,
                groupUseEntireRow: true,
                groupKeys: ['matchedOn']
            }

The grouping works perfectly fine, but I want to suppressCount that appears right after the Group. How it would be done by having groupUseEntireRow: true ? 

Also, Is it possible to use the custom template for Group row? Like I want to add a menu icon along with Group Name  which will be a dropdown of having couple of action buttons

**Comment by ceolter** [comment]
> How it would be done by having groupUseEntireRow: true

you would need to provide your own inner renderer for that.



> Also, Is it possible to use the custom template for Group row? Like I want to add a menu icon along with Group Name which will be a dropdown of having couple of action buttons

same as above actually, if you provide your own group cell renderer, then you have total freedom as to what goes in.

there is an example of a custom cell renderer on the grouping documentation page.

PS please use the board for questions, i want to keep the github issues for issues with the grid, it items i need to work on! thanks!

**Comment by ammar91** [comment]
OK. Is there anyway I can compile the DOM that I wrote inside groupInnerRenderer? 


    var gridOptions = {
                columnDefs: columnDefs,
                enableSorting: true,
                enableFilter: true,
                enableColResize: true,
                angularCompileRows: true,
                angularCompileFilters: true,
                groupUseEntireRow: true,
                groupKeys: ['matchedOn'],
                groupDefaultExpanded: true,
                groupInnerRenderer: groupInnerRenderer
            }

            function groupInnerRenderer(params) {
                return '&nbsp;&nbsp;<span><a data-ng-click="vm.takeAction();" href=""><i class="glyphicon glyphicon-tasks"></i></a>&nbsp;&nbsp;' + params.node.key + '</span>';
            }

**Comment by ceolter** [comment]
do you have angularCompileRows=true set in your grid options?

**Comment by ammar91** [comment]
Yes, Please review the GridOptions.

**Comment by ammar91** [comment]
Also, I am wondering we can change the background color for a specific Group inside innerRenederer.

**Comment by ammar91** [comment]
I have a scenario in which I have to change the background color of Group to Red. As the DOM is not ready before the groupInnerRenderer function execute, I setup a logic like this

 function groupInnerRenderer(params) {
                
                setTimeout(function () {
                    
                    if (params.node.children[0].data.isInDiscussion) {

                        angular.element(".ag-body-container div.ag-row-group[row=" + params.rowIndex + "] span.ag-group-cell-entire-row").css('background-color', 'red');
                    } else {
                        angular.element(".ag-body-container div.ag-row-group[row=" + params.rowIndex + "] span.ag-group-cell-entire-row").css('background-color', '#aaa')
                    }
                }, 500);
                
                return '&nbsp;&nbsp;<span><a data-ng-click="vm.takeAction(' + "'" + params.node.key + "'" + ');" href=""><i class="glyphicon glyphicon-tasks"></i></a>&nbsp;&nbsp;' + params.node.key + '</span>';
            }

**Comment by ceolter** [comment]
didn't I ask you to raise question about the grid on the board and not github issues????

i feel if i keep answering, you are just going to keep using the github issues so am gong to stop! :)

**Comment by ammar91** [comment]
I am sorry, but I thought as this issues have already been closed and I was in the same context so still continue here. Again sorry, I will open this question on Board.
