### ISSUE TITLE
Grid Rendering break v1.10

### ISSUE THREAD

**Issue by ammar91** [ceolter/angular-grid#274]
I took the latest version i.e, v1.10 and surprisingly The grid data not seems to be appear, only the pagination of the grid display. I believe there is no breaking change in the latest release but not sure why Grid suddenly stop displaying. 

This s how it looks like after the update:
![after](https://cloud.githubusercontent.com/assets/7683970/8396889/a31d5df6-1dd2-11e5-9133-d02d293f509d.PNG)

Please suggest

**Comment by ceolter** [comment]
make sure there is height on your grid, that's probably what it is.

**Comment by ammar91** [comment]
I see, but in previous version I didn't have to set the height manually, why it is needed in the latest release?

Also, now I need to set the height manually, any idea how would I make the grid not use vertical scroll bar? something like making the grid height to auto but this not seems to be working.

I am sorry, will use board next time for these kind of questions.

**Comment by ceolter** [comment]
Used to work before by accident, just happened to work, a quirk.

In the last release I moved to a more rigid layout to pave the way for
dockable bits, like the tool panel. Going forward I will be making much
more use of these 'pluggable parts'.

Re no vertical scroll, the trick you were using wasn't intended. In time I
will cater for this.

**Comment by equilerex** [comment]
if you really need it then you can use a dirty work-around...by adding inline style on the grid element  style="height:{{31+gridOptions.rowData.length*30}}px" where 30 is the height of your rows and 31 is the header's height (1 extra px to avoid scrollbar)
