### ISSUE TITLE
ag-grid v1.10.0 will not work once added the <!doctype html> on the top of the HTML file

### ISSUE THREAD

**Issue by lenient** [ceolter/angular-grid#275]
Hi All,
After upgraded the ag-grid to v1.10.0, the grid does not work, it only shows the blank instead of the part of grid. 

It spent me a lot of time to find the problem is caused by the <!doctype html>, if it's removed, then the grid works.

However, this declaration is needed for our project. 

Here is an example, since the json data is loaded from the anguar-grid site, so need to launch the browser with  --disable-web-security --allow-file-access-from-files --enable-file-cookies.
http://jsbin.com/qakatoyamu/1/edit?html,js,output

Anyone would have any inputs on this will be highly appreciated.

**Comment by ceolter** [comment]
Does your grid div have height specified?

**Comment by ninety7** [comment]
I have the same issue. Specifying the height in pixels works but I want my grid to be as high as its content (auto height) how is it done? the suppressVerticalScroll=true option is not working for me.

**Comment by ceolter** [comment]
having the grids hight adjust with the number of rows is not directly supported. this was working with previous versions out of coincidence. the new layout i've introduced (for the toolbar and more addons coming) prevent the simple flow that was there before.
