### ISSUE TITLE
Grid footer with aggregates on some columns and total number of rows

### ISSUE THREAD

**Issue by okonovalenko** [ceolter/angular-grid#276]
Hi, amazing grid!
Is there a way to do grid footer with aggregates on some columns and total number of rows like it has been done for grouping?

Example from ui-grid
:
![image](https://cloud.githubusercontent.com/assets/4671733/8408718/4326fb6c-1e6a-11e5-8104-640f2096f475.png)

**Comment by ceolter** [comment]
Plan to put this in, but it's a few months away. Already tracked here:
https://github.com/ceolter/angular-grid/issues/45

**Comment by shivekundefined** [comment]
Hey there!
Is this feature is up or not..? Please tell ASAP.

**Comment by ceolter** [comment]
footers is in. you will need to calculate the totals yourself.

**Comment by burcusozay** [comment]
Can we use floating rows with aggregate functions?

**Comment by Ram-SR** [comment]
Can someone please give me a link with footer in the grid?

**Comment by SWGeekPD** [comment]
Is this feature up and running, Can some one please share the link of any example using footer.
