### ISSUE TITLE
Investigate 'ensure row visible' with 'virtual paging'

### ISSUE THREAD

**Issue by ceolter** [ceolter/angular-grid#279]
http://www.angulargrid.com/forum/showthread.php?tid=2349&page=4

**Comment by lucasvall** [comment]
Have you made progress on this issue (virtual pagination and ensureIndexVisible in 1.10 not working)?

**Comment by lucasvall** [comment]
Have you made any progress on this (ensureIndexVisible not working on virtual pagination on latest releases)

**Comment by ceolter** [comment]
haven't looked. sorry.

**Comment by SoftwareDevQ** [comment]
I am going to try to solve this issue, because this is a blocker for me. Can you give me a kick start? Do you have any ideas where the bug is likely to happen?

**Comment by ceolter** [comment]
virtualPageRowController.ts for loading the rows, then gridPanel.ts for the grid's containers (ie where you will find the div that needs to be scrolled). also look at how the current ensureIndexVisible works.

btw, i've just merged in a huge refactoring, would be good for you to make sure your working off latest.

**Comment by SoftwareDevQ** [comment]
I think I found the bug. In grid.ts you have setupComponents. The rowModel is set to use the rowModel of inMemoryRowController by default. I think it is missing the setup for virtualPageRowController's rowModel when grid.doingPagination. The grid is reading virtualRowCount off inMemoryRowController, while datasource is storing data into virtualPageRowController.

**Comment by SteveQiu** [comment]
I have submitted a pull request for the fix.

SDQ

**Comment by ceolter** [comment]
i didn't fully test this, so please advise if issue should be reopened.
