### ISSUE TITLE
Expand All/Collapse All don't work when grouped + filtered

### ISSUE THREAD

**Issue by greglockwood** [ceolter/angular-grid#29]
Hi, impressive grid! Thanks for sharing it with the community.

I was playing with your "Test Drive" page and found a bug with it.

Here is how to reproduce it on the [Test Drive page](http://www.angulargrid.com/example.html):

1. Enter text to filter by in the "Filter..." input. I used "Sophie".
2. Select a property to Group By. I used "Language".
3. Try to click Expand All or Collapse All. Nothing happens.

**Comment by ceolter** [comment]
Thanks @greglockwood , I'll get that fixed. :)

Funny, everyone filters for Sophie . . . . .

One person brought to my attention I only have girls names, I had no idea!!!! (wasn't intentional)
