### ISSUE TITLE
callback for column changes

### ISSUE THREAD

**Issue by ceolter** [ceolter/angular-grid#294]
http://www.angulargrid.com/forum/showthread.php?tid=2426

**Comment by mathielen** [comment]
+1

**Comment by meganke** [comment]
+1

**Comment by ceolter** [comment]
done via a contributed CR

columnResized	Function callback, gets called when a column has finished being resized by dragging its handle.
columnVisibilityChanged	Function callback, gets called when a column has its visibility toggled from the tools panel.
columnOrderChanged	Function callback, gets called when a column is re-ordered by changing its position from the tools panel.

**Comment by daljeetsingh1985** [comment]
@ceolter columnVisibilityChanged  doesn't work for me.

**Comment by ceolter** [comment]
@daljeetsingh1985 it's columnVisible, not columnVisibleChanged
