### ISSUE TITLE
sizeColumnsToFit not filling my screen

### ISSUE THREAD

**Issue by chiptus** [ceolter/angular-grid#296]
Hi,

I have sizeColumnsToFit triggered on window resize (would be nice if it was part of the module - suggestion)...
It works when I make the window smaller, but when I stretch the window, the grid stays at the same size and columns are not sized up.

**Comment by chiptus** [comment]
Ok, i guess the event is called before the end of it, and thus the grid thought the size is smaller than it should have been. inserting a timeout helped.

**Comment by ceolter** [comment]
> Ok, i guess the event is called before the end of it, and thus the grid thought the size is smaller than it should have been. inserting a timeout helped.

yes, that shounds right, no way to tell the order of things getting fired. the grid listens to window resize to do the layout again.
