### ISSUE TITLE
how to trigger recalculate height of centerRow?

### ISSUE THREAD

**Issue by chiptus** [ceolter/angular-grid#298]
I'm having a problem where because my grid was initialized with no rows, it is left at 40px height even when i get new rows and call onNewRows (this is when i have the directive main element on 100% height instead of a fixed height). Looking in the html I found that centerRow stays at 40px and that changing it to 100% fixes this problem...
Is onNewRows recalculates this height?

Thanks!

**Comment by ceolter** [comment]
Does the main grid div have height?

**Comment by ceolter** [comment]
sorry, i see that you are setting the main grid to 100% height.

if the main div is not taking the 100% that you specify, then something is wrong with the layout before your page. the grid doesn't change the height of the directive's div, but tries to fill it. if this div is not taking 100%, them maybe something wrong with it's layout.

**Comment by daric81** [comment]
I was having a similar issue of centreRow being 40px during initial load. adding the following css corrected the issue for me. 

#centerRow {
height:100%;
}
