### ISSUE TITLE
Buttons in cell

### ISSUE THREAD

**Issue by asm0dey** [ceolter/angular-grid#30]
Hello!

Is it possible to place button into cell? And will it work with angular scope methods?

**Comment by ceolter** [comment]
Yes for both questions.

If you want the button to be an AngularJS one, do the following:

'''
// set in grid options
gridOptions.angularCompileRows = true;

// set in the colDef
colDef.cellRenderer = function(params)  {
    return '<button ng-click="functionOnScope(data)">Expand All</button>';
}
'''

In short, enable Angular compiling of rows. Then in the HTML you turn back, do whatever AngularJS you want. For each row, the table creates a new scope and inserts the data for the row into that scope. So the method on the scope will receive which data to work on.

There is a full example of this in the docs here:
http://www.angulargrid.com/angular-grid-angular-compiling/index.php

**Comment by PhiLhoSoft** [comment]
Page linked above: "This page no longer exists."...
https://www.ag-grid.com/angular-grid-cell-rendering/index.php is probably the most relevant equivalence (angularCompileRows is mentioned there).
Note: the above page, and some others, still have "Angular Grid" in the title...

**Comment by kedomonzter** [comment]
Is this working in Angular2?

**Comment by ceolter** [comment]
@kedomonzter the cells don't use angular compiling in ng2. so you will have to put the logic in using standard jaascript, or you have to do the angular 2 compiling yourself.

**Comment by ImranAhmed** [comment]
Is there an example for this anywhere? I am interested in the angular 2 compiling option. Trying to pass a template to the the **cellRenderer** in the following format and it looks like I am hitting the same issue. Thanks,

```
template = `<label class="c-input c-checkbox">
                          <input type="checkbox" (change)="onItemSelected(item)">
                          <span class="c-indicator"></span>
                          ${v.value} 
                    </label>`;
```

**Comment by ImranAhmed** [comment]
I managed to get this working using the standard JS way. Would be interested to see an angular compiling solution. This is my code for anyone who is interested.

This adds a checkbox to each cell. When the user changes the checkbox value in each cell it will update a selectedItems property on the model.


            cellRenderer: (params) => {
                  const element = document.createElement('span');
                            element.innerHTML = '-';

                            if (_.isUndefined(params.value)) {

                                return element;

                            } else {

                                const data = params.node.data;
                                const group = data['group'];
                                const code = data['code'];

                                const item = new Item(group, code, params.value);

                                let template = `<label>
                                  <input type="checkbox">
                                    ${params.value}
                                  </label>`;

                                element.innerHTML = template;
                                element.addEventListener('change', () => {

                                    const index = _.findIndex(this.selectedItems,
                                        o => (o.toString() === item.toString()));

                                    if (index === -1) {
                                        this.selectedItems.push(item);
                                    } else {
                                        _.pull(this.selectedItems, item);
                                    }
                                });
                            }
                            return element;
                        }

**Comment by vknaveenkumar** [comment]
@ImranAhmed : how to call the class function inside the event listener?

**Comment by ImranAhmed** [comment]
@vknaveenkumar, please elaborate.What are you specifically trying to do?

**Comment by tonyeung** [comment]
@vknaveenkumar  you should probably either ask on stackoverflow or open a new issue

**Comment by ceolter** [comment]
fyi - we are trying to get ng2 bindings working with ag-grid. we are finding it very difficult how to work with ng2 at this level.

**Comment by jmls** [comment]
was this ever sorted ?

**Comment by bhaskerchari** [comment]
Is it still in ag-grid TODO list to support angular2 binding to make it work for inline cell renderers?
