### ISSUE TITLE
filters with group issue

### ISSUE THREAD

**Issue by dbubs** [ceolter/angular-grid#300]
I am having an odd issue with filters when using groups. The quickFilterText is working correctly for all fields except the group text.

I created a [jsfiddle](http://jsfiddle.net/dknell/zxsaexsu/1/) to show the issue. I also created some random data and a similar columnDefs that DOES work correctly. This suggests that there is an issue with my data. I've tried changing the values, but nothing is working.

You can switch between the working data and non-working data by modifying the `works` variable.

Any ideas would be greatly appreciated!

**Comment by ceolter** [comment]
The 'quick filter' works by matching against all of your column definitions.

In your 'working' example, you have a column for the group (eye color).

In your 'not working' example, you don't have a column for warehouse.

So, in short, if you want the quick filter to work from group text, then have your group as a column.

If you don't want to show the column, then mark it as hidden (colDef.hide = true).

**Comment by dbubs** [comment]
Thanks! I knew I was missing something...
