### ISSUE TITLE
Table is overflowing screen

### ISSUE THREAD

**Issue by chiptus** [ceolter/angular-grid#301]
My solution for https://github.com/ceolter/angular-grid/issues/298 was going recrusivley to the body and setting the hieght of everynode on the way from the grid to the body element. it fixed the resizing of the height, meaning that the grid isn't stuck on 40px.
But when I get a-lot of data it is overflowing the screen, and I can't see the end of the scrollbar and the pagination element.
Is this a known problem which can be fixed with something similar to how we solved issue 298?
If not, I guess there's a bug in my style or in your code. I would be happy to help searching for the problem, but I'm not sure where to start.

Thank you!

**Comment by ceolter** [comment]
> the grid isn't stuck on 40px

sorry, not sure what you mean here.

do you have height specified on the grid div? the grid will fill whatever div height you give it. it sounds like you are trying to have your grid with a dynamic height based on the number of rows that it has???

**Comment by ceolter** [comment]
ps am closing this issue, as it's not an issue with the grid, it's a question. :)
