### ISSUE TITLE
Filter Menu not working properly when displaying more than one grid at the same time

### ISSUE THREAD

**Issue by jkorrek** [ceolter/angular-grid#308]
Hi there,

I'm having a lot fun using your grid in our application, hower there seems to be a problem with the filter menu when using more than one grid at the same time (since release 1.11.1). It only works for the grid that was initialized last.

I could trace this to the PopupService. As far as I can tell, this is supposed to work as a singleton, however the init function always overrides the popupParent. 
Therefore all displayed grids would use the popupParent from the "last" grid.

Could you please take a look at that?
Thanks!

**Comment by ceolter** [comment]
ah crap, yea, of course, the singleton is application wide, not grid wide. this crept in when moving to typescript classes. i'll fix for the next release. thanks for pointing this out and your troubleshooting.

**Comment by ceolter** [comment]
popup service is no longer a singleton
