### ISSUE TITLE
some divs have id's

### ISSUE THREAD

**Issue by westor21** [ceolter/angular-grid#311]
Looking in the html code, I noticed, that there is an id in some of the divs, and some of them are also not unique (e.g. <div id="center" ... is used twice)
That could lead to some problems and interfere the surrounding application.

**Comment by ceolter** [comment]
thanks for pointing this out. however i'm aware of this and am ok with it! although the spec says the id should be unique, all browsers support having the id duplicated. as long as the path to the object is unique (ie no two elements with the same id can be siblings) then it won't cause any issues for you. i decided to stick with the current design as its easier (ie more maintainable).

**Comment by westor21** [comment]
Well, I think, many developers my have selectors on document.getElementById("id") base without specifying extra path information. And the api does not allow to add a path here.

**Comment by ceolter** [comment]
you can have many selectors, one after the other, which act as parent / child, eg this:
".parentPanel #22"
will select the element with id 22 that is within the element with the class parentPanel

**Comment by westor21** [comment]
Of course you can build your selectors like that. But following the HTML specs, you can select an element with document.getElementById. You will get a single element, and you would also expect only one per document. If more then one exists, you will get the first one - may be it's from ag-grid or may be it's from the surrounding code.

You can not know, how developers are using their selectors.
