### ISSUE TITLE
Double click to edit a cell, double click another cell; wait; editing automatically ends and after that it's not possible to edit any cell anymore

### ISSUE THREAD

**Issue by abhijeetpathak** [ceolter/angular-grid#318]
Steps to reproduce:
1) Double click to start editing of a cell
    Editing starts, textbox is shown.
2) Double click on some other cell to start that cell's editing
    Editing starts, textbox is shown.
3) Wait for a couple of seconds.
    Textbox automatically disappears.
4) Its not possible to edit any cell after this.

**Comment by abhijeetpathak** [comment]
I've debugged it a bit.
It happens if we call ```api.refreshView()``` when editing is active. The editing then stops and no further editing is allowed on any cell.

**Comment by ceolter** [comment]
could not reproduce on test drive. if you are calling api.refreshView() while editing, then this is a deal breaker, you can edit and refresh the view at the same time.

**Comment by radopas** [comment]
Hello,
I have a similar problem - when in edit mode, and do a scroll via the mouse - the edit box disappears, and it is not possible anymore to edit any cell.
Another case - if in edit mode, and inside the callback cellChanged, if i call rowDataChanged() - the edit box disappears and can't enter in edit mode again. 

I don't know if it does matter but the grid is with virtualPaging: true

**Comment by ceolter** [comment]
@radopas what version are you on? this sounds like something that i fixed about 4 weeks ago.

**Comment by radopas** [comment]
The package.json says "version": "1.11.1"

**Comment by ceolter** [comment]
@abhijeetpathak is it also fixed for you in the latest? i believe it should be

**Comment by abhijeetpathak** [comment]
Yes. It is fixed.
