### ISSUE TITLE
BUG: Fill entire grid width when resizing last header column

### ISSUE THREAD

**Issue by erwin-beckers** [ceolter/angular-grid#321]
When resizing the last header column the grid becomes smaller.
I would expect that the grid would fill the entire width by extending the last header column width

![resize](https://cloud.githubusercontent.com/assets/7457725/8717156/d4cad0ee-2b98-11e5-8a1f-65192404c5dd.jpg)

**Comment by ceolter** [comment]
i disagree. this is not how windows explorer works on my windows 7 box, and  now behavious i've observed in other grids.
