### ISSUE TITLE
Add new option for grouping rows

### ISSUE THREAD

**Issue by erwin-beckers** [ceolter/angular-grid#323]
Can you add a new option (in gridoptions) ? 

when this option is set and the first cell of a row is empty (no text)
then the grid should not draw the bottom border of that row.
This way the current and next row are 'merged' / grouped together

**Comment by ceolter** [comment]
that's custom, don't think it belongs in the grid as an option. if you want different group behaviour, provide your own group agg function. if you want different rendering behaviour, then you provide your own theme (or override a style in one of the existing themes).
