### ISSUE TITLE
Cell word wrap / row with 2 lines 

### ISSUE THREAD

**Issue by nelreina** [ceolter/angular-grid#328]
Is it possible to like a word wrap cell ??

Or 

Like a row with 2 lines ?

**Comment by ceolter** [comment]
please keep github issues for issues!!! the board for questions, thanks :)

for word wrap, you need to add the relevant css to the cell to enable word wrap. i don't know what it is offhand, but others have managed it. easiest way to find is to inspect the dom element in your dev tools and apply different css to find what works.

**Comment by nelreina** [comment]
@ceolter Ok tnx for the response. Next time I will use the board for questions. I am sorry for that.
