### ISSUE TITLE
Value Zero not view

### ISSUE THREAD

**Issue by sidahmedbenkhaoua** [ceolter/angular-grid#334]
hi , i have json file to showing in table have a zero number it is work with auther number but not with zero

**Comment by ceolter** [comment]
i don't understand. are you saying the grid doesn't display zeros???

**Comment by sidahmedbenkhaoua** [comment]
it contains zero number not displayed

**Comment by ceolter** [comment]
it's probably confusing zero with undefined or null. thanks for pointing out, i'll look into it.

**Comment by sidahmedbenkhaoua** [comment]
yes
