### ISSUE TITLE
Allow 'not showing' the group row

### ISSUE THREAD

**Issue by ceolter** [ceolter/angular-grid#336]
http://www.angulargrid.com/forum/showthread.php?tid=2539

**Comment by ocombe** [comment]
Cool thanks :)

**Comment by ocombe** [comment]
I'll see if I can work on a PR for this, any hints where I should start searching ?

**Comment by ceolter** [comment]
yes, put a new property 'suppressGroupRow' which, when true, does enables this.

when creating the groups in inMemoryRowController.doGrouping(), always expand the groups by default.

then in doGroupMapping(), don't include the group rows.

you would also need a new cell renderer for the groups, as you will render differently for these.

**Comment by ocombe** [comment]
Ok it's done, but I didn't defined a new cell renderer, I'm not sure why I would need one ? (unless you're talking about the ability to only show the content of the first grouped row in the "group column"?)

**Comment by ocombe** [comment]
PR done here: https://github.com/ceolter/angular-grid/pull/345

**Comment by jongravois** [comment]
THIS IS AWESOME!!!!

If I do a bower install, will this fix move into my project?

Jon

**Comment by ceolter** [comment]
no, not until the next release.

if you want this now, you will need to check the project out and build yourself.

**Comment by jongravois** [comment]
It’s automated, isn’t it? Gulp? I might be able to handle that.

**Comment by jongravois** [comment]
BTW, did you ever consider taking a break from issues and create a kickass screencast actually building your Test Drive from scratch? I for one would pay for THAT!

Jon

**Comment by ocombe** [comment]
We would also love to have you on angular-air if that's something that might interest you !

**Comment by ceolter** [comment]
@jongravois yes, i even bought a mic to do it with!!!! i have my little 'non features list' in my head, my current one was angular 2.0 migration. two weeks ago it was all about performance. maybe the week after next.

@ocombe yes sure, what would i have to do???

**Comment by ocombe** [comment]
@ceolter send me a mail at olivier.combe@gmail.com and we'll make this happen !
