### ISSUE TITLE
Add support for functions as valueGetters

### ISSUE THREAD

**Issue by bartread** [ceolter/angular-grid#346]
The value expressions are nice for simple cases but it would be really helpful to be able to use a function as a valueGetter. The reason is that this would give you access to anything in the current closure.

Here's an example of what I mean:

```javascript
    function UserListController(userManagementApi) {
        var vm = this;

        ...

        vm.gridOptions = {
            columnDefs: [
                {
                    headerName: 'Name',
                    valueGetter: '(data.firstName ? data.firstName + " " : "") + (data.lastName || "")'
                },
                { headerName: 'Username', field: 'username' },
                {
                    headerName: 'Department',
                    valueGetter: getDepartment
                },
                ...
            ],
            rowData: [] // Will be initialised later with contents from vm.users
        };

        function getDepartment(ctx, node, data, colDef, api, getValue) {
            var departmentNames = '';

            for (var index = 0, size = data.department.length; index < size; ++index) {
                if (index > 0) {
                    departmentNames += ', ';
                }
                departmentNames += data.department[index].name;
            }
                
            return departmentNames;
        }
```

I realise I can achieve this by decorating the context with my getDepartment function but it feels a bit ghetto, compared with providng the function directly to the valueGetter.

Not the end of the world by any means, but certainly would be a nice addition for the future.

**Comment by ceolter** [comment]
you can already do this. see here, value getters as functions. the example 'age now' column is this:
http://www.angulargrid.com/angular-grid-value-getters/index.php
