### ISSUE TITLE
[BUG] Pinned columns leaves a white space at the bottom, sometimes

### ISSUE THREAD

**Issue by lukelalo** [ceolter/angular-grid#35]
Hi!

I've noticed that *sometimes* the pinned columns container layer does not fill all the grid height, and leaves a white space at bottom:

![angulargrid issue](https://cloud.githubusercontent.com/assets/4819263/6982124/3906c2e4-da0d-11e4-8c67-9442ec862fad.png)

The problem is that the layer height of .ag-pinned-cols-viewport misses some pixels (corresponding to the not pinned rows horizontal scrollbar height, I think). I'm not sure as I've not swam into the code yet.

I'm using a Chrome 41.0.2272.118 on a Mac. In Safari it also seems to fail.
I've tested it on Chrome for windows and there you can see that the missing height is the same as the horizontal scrollbar, or 2 pixels higher...

Regards
Pablo García

**Comment by ceolter** [comment]
You analysis is correct. It was a 'rough and ready' first pass on the
scrolling and pinned columns. When a scroll bar is in the main body, then
the pinned body gets cut by the scrollbar height. The scroll height is
hard-coded to what looked best on my Chrome & Windows, so I need to come up
with a way that measures the scroll width in the running platform. However
have you found something else wrong outside of this? (ie no scroll bars in
body, but sill pinned column clipped?) - if so, please explain how to
recreate. Thanks :)

On 3 April 2015 at 13:34, lukelalo <notifications@github.com> wrote:

> Hi!
>
> I've noticed that *sometimes* the pinned columns container layer does not
> fill all the grid height, and leaves a white space at bottom:
>
> [image: angulargrid issue]
> <https://cloud.githubusercontent.com/assets/4819263/6982124/3906c2e4-da0d-11e4-8c67-9442ec862fad.png>
>
> The problem is that the layer height of .ag-pinned-cols-viewport misses
> some pixels (corresponding to the not pinned rows horizontal scrollbar
> height, I think). I'm not sure as I've not swam into the code yet.
>
> I'm using a Chrome 41.0.2272.118 on a Mac. In Safari it also seems to fail.
> I've tested it on Chrome for windows and there you can see that the
> missing height is the same as the horizontal scrollbar, or 2 pixels
> higher...
>
> Regards
> Pablo García
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/35>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by lukelalo** [comment]
Nothing else apart of you need to move to the 'unpinned' layer to scroll up and down with the mousewheel. But I think this has been reported previously. 

Anyway, I'll be testing the grid for the next weeks, and I'll report you all I find. I'm very interested at using your grid. I am currently using jqGrid with angular.js and I need a powerful solution with a good performance, like yours. 

Thanks for the good work. Regards
Pablo García

**Comment by tannerlinsley** [comment]
I'll try and get a good PR set up for this.  I'd also like to go over some repo organizational things and API with you @ceolter.  I really think this grid is the best one I've used (and like you, I've used them all).  Let's chat.  tannerlinsley@gmail.com

**Comment by ceolter** [comment]
fixed

**Comment by lukelalo** [comment]
I stilll see this issue. Is the test drive updated with the last fix?

Regards
Pablo García

**Comment by ceolter** [comment]
no, i hadn't pushed out to the website test drive since fixing this.

i have just pushed it out now. can you try again?

On 26 April 2015 at 11:29, lukelalo <notifications@github.com> wrote:

> I stilll see this issue. Is the test drive updated with the last fix?
>
> Regards
> Pablo García
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/35#issuecomment-96361328>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by lukelalo** [comment]
Wow!, now it's working fine. Good job!

**Comment by ceolter** [comment]
another one off the list!!

On 26 April 2015 at 12:38, lukelalo <notifications@github.com> wrote:

> Wow!, now it's working fine. Good job!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/35#issuecomment-96367082>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by lukelalo** [comment]
There might have been a regression? I am having this issue again :(

**Comment by lukelalo** [comment]
Ok, I've tested it with Mac and it works as expected, however in all browsers I've tested in windows it lets the scroll height unfilled :(

![angulargrid issue](https://cloud.githubusercontent.com/assets/4819263/7475418/c5fc7c7c-f347-11e4-98a8-cfd14d2f204b.PNG)

**Comment by ceolter** [comment]
Ah crap, wasn't expecting that, I though we had this one fixed. Will look deeper when back from hols.

**Comment by ceolter** [comment]
i think it is working as expected. the pinned cols should have a solid block if there is a visible scroll on the main body. the block should be the same height as the scrollbar. if the scrollbar has no height (such as on safari on mac), then no block will be at the bottom. the screenshot you have above is what i would expect in windows and chrome. can you please confirm?

**Comment by lukelalo** [comment]
Meh... I don't like it very much... it seems that there's missing something :( 

¿Would it be so difficult to make the pinned columns as high as  the grid container?

Regards

**Comment by ceolter** [comment]
Nope,  would be easy.  I can stick this in as an option.

**Comment by lukelalo** [comment]
That would be nice! Thks
