### ISSUE TITLE
Wrong parent childIndex when > 2 row groups

### ISSUE THREAD

**Issue by ocombe** [ceolter/angular-grid#350]
When I'm grouping rows, if I set 1 or 2 groups it works fine.
But when I have 3 groups, the values of node.parent.parent.childIndex is all wrong...

Example:
2 groups:
- node.parent.childIndex = 0 to 9 // correct
- node.parent.parent.allChildrenCount = 10 // correct
- node.parent.parent.children.length = 10 // correct

3 groups:
- node.parent.parent.childIndex = always 0 // wrong
- node.parent.parent.parent.allChildrenCount = 30 // correct
- node.parent.parent.parent.children.length = 6 // wrong ?!! when the children count says 30 and there is in fact 30 children, but the children array of this parent only contains 6 children

**Comment by ceolter** [comment]
allChildrenCount is all children and children's children, not just immediate children.

**Comment by ocombe** [comment]
OK, but it doesn't explain the childIndex at 0?

Le jeu. 30 juil. 2015 19:12, Niall Crosby <notifications@github.com> a
écrit :

**Comment by ceolter** [comment]
where are you printing to the console?

**Comment by ocombe** [comment]
in the cell renderer, from the headers

**Comment by ceolter** [comment]
from the headers? you mean colDef?

**Comment by ocombe** [comment]
yes :)

**Comment by ceolter** [comment]
i'm not getting what your getting

i put this into the test drive
```
        rowClass: function(params) {
            var node = params.node;
            if (node.parent && node.parent.parent && node.parent.parent.parent) {
                console.log('' + node.parent.parent.parent.childIndex);
            }
            return [];
        },
```
and then pivot by country, language, game of choice,

and i get a mixture of indexes

**Comment by ocombe** [comment]
I'll try to make you a plunkr tomorrow, I'm at home right now

**Comment by ceolter** [comment]
cool
