### ISSUE TITLE
Clicking the "Apply Filter" button should close the filter box.

### ISSUE THREAD

**Issue by EmmetA** [ceolter/angular-grid#352]
Looking through the source I don't see an easy way to access the hidePopup function after the filter modal is opened. 

Ideally it'd be available in an event after the filter is processed or an option to close the modal after the "Apply Filter" button is clicked.

**Comment by ceolter** [comment]
Emmet - does 379 fix it for you?

**Comment by EmmetA** [comment]
Perfect. Thanks
