### ISSUE TITLE
Allow zebra striping to extend to the edge of the grid

### ISSUE THREAD

**Issue by JannesMeyer** [ceolter/angular-grid#355]
Currently it looks like this if the columns don't fill the entire space:
![untitled-2](https://cloud.githubusercontent.com/assets/704336/9034083/e2fba2f8-39c4-11e5-947c-77967b2cae56.png)

It would be great to have the grey background color of the striped rows to extend to the edge of the grid.

**Comment by ceolter** [comment]
Use the api.sizeColsToFit method??

**Comment by JannesMeyer** [comment]
I suppose that works, but I was hoping there was a way to do it without changing the column width.

**Comment by ceolter** [comment]
i'm going to close this as it's only a minor issue and fixing it would require reworking how the colors are done. so cost / benefit analysis deems it's not important enough to change the design.

**Comment by JannesMeyer** [comment]
By the way, Is sizeColumnsToFit() documented anywhere? I can't find any mention of it in the docs.

**Comment by ceolter** [comment]
http://www.angulargrid.com/angular-grid-resizing/index.php
