### ISSUE TITLE
Support for default sort direction

### ISSUE THREAD

**Issue by surjikal** [ceolter/angular-grid#360]
Right now, upon clicking a header in initial sorting state, the next sort order is ascending. I need it to be descending instead. Would you accept a pull request for this?

The hardest part is thinking of a name for this option.

**Comment by surjikal** [comment]
I'd probably need this at the column-level as well, which shouldn't be too hard to build either. I can build it I just want to know if you'd accept a pull request for this feature. If yes, then I'd love to get some suggestions for the property name.

**Comment by ceolter** [comment]
already pr created that i'll be accepting soon
https://github.com/ceolter/angular-grid/pull/356

**Comment by surjikal** [comment]
Oh sorry about that!
