### ISSUE TITLE
angularCompileRows + quickFilterText doesn´t work together

### ISSUE THREAD

**Issue by livioalves** [ceolter/angular-grid#361]
When I set angularCompileRows: true, I cannot use quickFilterText because it is readonly.

**Comment by chiptus** [comment]
What are you doing exactly? I use them both on a few of my grids

**Comment by ceolter** [comment]
could not reproduce so closing. if you want to reopen, please provide how to reproduce, providing a fiddle would be very helpful. or if it's a question, please use the forum. thanks :)
