### ISSUE TITLE
Grouping Footers cause the header summaries to clear out after scrolling

### ISSUE THREAD

**Issue by ataft** [ceolter/angular-grid#362]
"gridOptions.groupIncludeFooter = true" causes this problem.  Look at the Grouping Footers example here: http://www.angulargrid.com/angular-grid-grouping/index.php

Expand a group, scroll to the bottom, then back to the top and you'll see that the header summaries are now blank.  When I use a cell renderer for formatting, it's NaN instead of blank.

**Comment by ataft** [comment]
just saw that this was addressed yesterday. you're on top of it, thanks!

**Comment by ceolter** [comment]
yup, had noticed that a few days ago.

**Comment by ceolter** [comment]
i was beginning to wonder if anyone was using footers, as it was broken about two releases ago and nobody complained!

**Comment by ataft** [comment]
interesting. i think as time goes on and word of angular-grid gets out, you may have a different type of user. i'm using it as part of a reporting and analytics offering, not just a simple excel-like spreadsheet, and i think that this is a big draw of angular-grid over the other ones.  in this type of usage, summarization, footers, and grand totals (which i bugged you about in another post) are critical. there are a million grids that do basic excel-like functions, but angular-grid is much more than that. again, i think your community of users will change as they see why angular-grid is better than the rest, not just faster.  personally, i hope that it doesn't get bloated with add-ons like the tool panel, but rather allows us to build our own column and grouping management, using the grid as one part of a bigger picture with other content.  thanks again!

**Comment by ceolter** [comment]
> allows us to build our own column and grouping management, using the grid as one part of a bigger picture with other content

noted.

you sound like your requirements are like mine.

the grid won't be getting bloated in one direction, it will all be about 'well you can do this, or you can build your own', just like the filters, i should you how a filter is done, give some examples, but it's the pluggable nature of the filters that make it powerful, rather than 'one size fits all'.

also the cell renderers, i used to treat grouping, for example, as a special case inside the grid. now it's changed so the grouping is just a provided custom cell renderer, allowing you to replace it if you want the grouping cells to have different behaviour.

and then also the tool panel, as you mention, i used to have logic in there that updated the model. but i'm refactoring, and moving all the logic into the columnController (proper MVC), so if you want to provide your own tool panel, you can. or even share one columnController against many grids (again proper MVC).

interesting comments on the other grids, i welcome this knowledge as i haven't given many other grids thorough usage, just a small bit of a few, and didn't like them without getting deep!

**Comment by ataft** [comment]
This issue is back, but now the group header aggregates disappear when you simply expand a group. Before, they disappeared after a scroll away and then back. Again, look at the Grouping Footers example here: http://www.angulargrid.com/angular-grid-grouping/index.php

**Comment by ceolter** [comment]
this is working as i expect. when the group is closed, the group data is displayed beside the group. when the group is open, the group data is displayed at the bottom of the group in the footer.

**Comment by ataft** [comment]
thanks for the reply. from a UX perspective, users do not react well to disappearing data. i can see your point in cases where the footer is visible when you expand, but when the footer is not visible, it's even more of a problem.  i've been in the reporting industry for 15 years and this immediately stood out as a bug/undesirable behavior.  is there any way to make this configurable?  also, i'm using a custom groupAggFunction and the header aggregates show as "NaN" rather than blank (see screenshot below).

![image](https://cloud.githubusercontent.com/assets/11670864/9186377/dd2d70ae-3f78-11e5-93b3-830ab8d83c34.png)

**Comment by ceolter** [comment]
> i'm using a custom groupAggFunction and the header aggregates show as "NaN" rather than blank

shouldn't be happening like this. when i do my own custom agg functions, i don't set the fields that have no data (so they remain undefined). this is what is happening on the demo page (and on your page by the looks of things, looking at month, product and month number, all have blank for the header.

re the header dropping to become the footer, what would the desired behavior be? maybe two modes, one for 'drop header' (what it it now) and one for 'header and footer separate'? wold the node then require two pieces of data, one for header, on for footer?

it makes sense for me, as i developed this feature for a P&L account, where the 'total income' is below the list of income details. i appreciate it's not the desired behavior for everyone, but i do have use cases that use this so i need  to keep it the way it is. but i'm open to making it configurable.

**Comment by ataft** [comment]
The "NaN" was due to an error in the cellRenderer since params.value is undefined. Easy fix.

As for the "keep header" feature, since the design is already "groupIncludeFooter" (true/false), perhaps the logic would be "groupKeepHeaderOnExpand" (true/false)?  Or, maybe your "header/footer modes" gives you more leeway if/when new ideas come in later.

I can see the use for a P&L report, where most/all of the details fit on the screen.  I would definitely use the 'drop header' feature both ways, depending on the report.

**Comment by ceolter** [comment]
i'm still not clear on what data you would have.

would you want to display the same data in the header and the footer?

or would you have two separate data sets, one for the header and one for the footer?

**Comment by ataft** [comment]
Same data in the header and footer.  This is useful for reports where you have to scroll down to see the footer.  I agree this would be undesireable for reports that you don't have to scroll to see the footer.  I can't see a use case for different data in the header and footer, that would just be confusing unless it was labeled, which would get messy.

**Comment by ceolter** [comment]
@ataft I added a new property groupSuppressBlankHeader, the feature will be in the next release.

**Comment by ataft** [comment]
awesome, you truly are the best!

**Comment by ceolter** [comment]
> awesome, you truly are the best!

there's a donate button on the website :)
