### ISSUE TITLE
SetFilter with newRowsAction as 'keep' hides new rows even though selectAll checkbox selected

### ISSUE THREAD

**Issue by wagonburger** [ceolter/angular-grid#363]
This occurs only when the new row contains a value for the filtered column that is not in the current set of unique values for that filter.

Example:
* rowdata = [{status:'A'}, {status:'B'}, {status:'C'}]
* Click filter menu on status column
* Uncheck select all
* Check select all
* Add new row to dataset {status:'D'}
* New row is not shown
* clicking on the filter menu shows status A.B,C selected and D unchecked

I have a fix which i'll add a PR for soon but will need some feedback as i'm not familiar with all the use cases and don't want to f*ck it up for everyone else!

**Comment by ceolter** [comment]
you wont phuck it up for anyone, as i won't be accepting any PR without doing a full review of the code!!!!

**Comment by wagonburger** [comment]
That goes without saying. If i wanted to wear a cowboy hat i would would contribute to ui-grid

**Comment by ceolter** [comment]
lol

**Comment by ceolter** [comment]
sorry if i'm getting mixed up, but did i accept a PR form you fixed this the other day? and hence we can close this issue?

**Comment by wagonburger** [comment]
Yes mate. All merged in. Thank you
