### ISSUE TITLE
Feature request: Wrapper for Polymer

### ISSUE THREAD

**Issue by matoorn** [ceolter/angular-grid#368]
Would be extremely useful to have a wrapper as a webcomponent for polymer (polymer-project.org).
Thank you for such a great grid.

**Comment by ceolter** [comment]
something like this:
http://localhost/example-web-component-grid/index.php

**Comment by matoorn** [comment]
This is great -  managed to add it as a web component with Polymer.
Many thanks.

**Comment by ceolter** [comment]
Great. I plan on making it more 'web component' in the future, such as having the api methods directly on the DOM object, and also having the gridOptions as dom attributes where appropriate. any advice on this is welcome, you might know more about web components than i do!
