### ISSUE TITLE
Context menu support

### ISSUE THREAD

**Issue by nelreina** [ceolter/angular-grid#37]
It will be nice to have a context menu support. Right click event on a row.

**Comment by xenit-raven** [comment]
Is there no event for right click yet? I'm also interested in a contextmenu / right click event

**Comment by ceolter** [comment]
not in yet, sorry :(

**Comment by ceolter** [comment]
this is now in. next release will have cellContextMenu callback for right click.

**Comment by nelreina** [comment]
@ceolter Much appreciated :+1: You are the best. Can't wait to implement it.

**Comment by anpatil** [comment]
Has this issue been released. I tried with 1.16.1 and it does not have the feature.

**Comment by ceolter** [comment]
nope. 2.0, in the next day or two.

**Comment by mikeerickson** [comment]
Hello gang

We are in the process of evaluating all the various popular grid controls and one of the key features is support for contextual menus (right click)   I am assuming now that ag-grid is out, this feature is now supported?

If you could please confirm this, I would greatly appreciate it.

**Comment by anpatil** [comment]
2.0.1 has the context click support. I am using it

**Comment by ceolter** [comment]
yup, it's in the latest.

**Comment by TheDebbish** [comment]
I'm new to react, and I have the method firing, but I'm having trouble getting how to actually get the menu to show. Does anyone have a good reference for examples of this?

**Comment by mrinalsing** [comment]
@ceolter , while using the cellContextMenu, in angular2 , the callback method is invoked, but I don't see my "custom" right click options.
for testing purpose I am using following callback-
 private  onCellContextMenu($event) {
        return [
                'copy','separator','paste'
        ];
}

But I see the default context menu. Could you please, think of any reason?
Regards

**Comment by MangeshTak** [comment]
Hi,

Is the contextmenu is enterprise feature?

Thanks
Mangesh

**Comment by nsankaranarayanan** [comment]
That's what it looks like @MangeshTak . In the documentation it is marked with an (e) symbol for enterprise specific feature.
https://www.ag-grid.com/javascript-grid-context-menu/

**Comment by praveen1241** [comment]
Is there a possibility to prevent the Context menu for some columns in the grid

**Comment by Romanow88** [comment]
yes, use `preventDefaultOnContextMenu=true`
