### ISSUE TITLE
angular-grid.d.ts is unusable as is.

### ISSUE THREAD

**Issue by tomc974** [ceolter/angular-grid#375]
When I tried to compile an angular project using angular-grid, I received the following error:
```
ts_declarations/angularjs/angular.d.ts(9,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'angular' must be of type 'any', but here has type 'IAngularStatic'.
```
The problem is caused by ```angular-grid.d.ts``` having the following declaration:
```typescript
declare var angular: any;
```
This declaration contradicts the one included in ```angular.d.ts``` from DefinitelyTyped.

To fix this issue you could remove the line ```declare var angular: any;``` from ```src/ts/main.ts``` so that it won't appear in the generated declaration file and reference ```angular.d.ts``` from DefinitelyTyped for the development of angular-grid either by copying the file manually or by using tsd.

**Comment by ceolter** [comment]
try now. i've wired up angular slightly differently. btw i'm avoiding angular typed files on purpose to keep it simple, and also not do anything that would confuse supporting both angular 1 and angular 2.

**Comment by tomc974** [comment]
No more compilation error, thanks for the quick fix.
