### ISSUE TITLE
Duplicated ID - itemForRepeat

### ISSUE THREAD

**Issue by S-YOU** [ceolter/angular-grid#378]
id="itemForRepeat" is duplicating, is that by design?

![duplicated_id](https://cloud.githubusercontent.com/assets/1001175/9292384/6b12de16-4430-11e5-9088-f7f7e3279ec9.png)

**Comment by ceolter** [comment]
yes. it's only a problem if you want it to be. the browsers are not bothered about duplicate id's, it's just humans who get upset when they see this!!! it's already mentioned in a previous issue so will close this one. going forward i'll keep my id's unique, just to keep people happy!!

**Comment by S-YOU** [comment]
hahaha, if I upset, i won't bother to take screenshot and post here anyway. I accidentally found it while I troubleshooting my css. just saying...

**Comment by ceolter** [comment]
no worries :) thanks for sharing :)
