### ISSUE TITLE
Provide hidePopup to afterGuiAttached after showing filter.

### ISSUE THREAD

**Issue by scotthovestadt** [ceolter/angular-grid#379]
Currently, hidePopup is being returned from addAsModalPopup but is not being used when showing a filter in showFilter (filterManager.ts). The requirement for my project is to close the filter GUI after the user has submitted the form. Currently, the only way to do that is a hack:
 ````
if($('.ag-filter').length) {
  $('body').click();
}
````

Obviously, it'd be much cleaner if afterGuiAttached was given the hidePopup reference. Here is my suggestion:
````
public showFilter(column: Column, eventSource: any) {

    var filterWrapper = this.getOrCreateFilterWrapper(column);

    this.popupService.positionPopup(eventSource, filterWrapper.gui, 200);
    var hidePopup = this.popupService.addAsModalPopup(filterWrapper.gui);

    if (filterWrapper.filter.afterGuiAttached) {
        filterWrapper.filter.afterGuiAttached({ hidePopup: hidePopup });
    }
}
````

Please let me know your thoughts.

**Comment by scotthovestadt** [comment]
Similar issue: https://github.com/ceolter/angular-grid/issues/352

**Comment by ceolter** [comment]
sounds good. done.
