### ISSUE TITLE
How to set programatically the selected Row?

### ISSUE THREAD

**Issue by HaythemJ** [ceolter/angular-grid#381]
Hi,

I have an angular grid and a form. Each time I select a row, I amke changes and I save and refresh data. Everything looks good unless I need to keep  my row selected since this is not appropriate for the end user.

Best Regards
HJ

**Comment by ceolter** [comment]
Please see the selection methods in the API:
http://www.angulargrid.com/angular-grid-api/index.php

**Comment by HaythemJ** [comment]
Many thanks for your support, it was there in the documentation, I did not scroll down:

    $scope.gridOptions.api.forEachInMemory( function (node) {
            if (node.data.country === 'United States') {
                $scope.gridOptions.api.selectNode(node, true);
            }
        });

**Comment by darkmanAmazigh** [comment]
i try to set set the value of selected row to Angularjs variable, it shown good in console, but in html page, i have undefined,
have you any idea please !

**Comment by safeerk** [comment]
This one is fine , this works fine if its a straight grid,.. But if its a Tree view structure .. is there any way we can point out the selected node...

**Comment by rrazong** [comment]
Just updating the link to the API's selection methods:
https://www.ag-grid.com/javascript-grid-selection/
See the "Node Selection API" section.

**Comment by harsh5400** [comment]
I tried node selection it is working but scroll down is not working 

Please help us

**Comment by gregbown** [comment]
The grid selection documentation does not describe how to search for a row based on a known field value.  Just in case anyone needs it.
```
          this.gridOptions.api.forEachNode( (node) => {
            if ( node.data.user_name === this.searchResults.user_name ) {
              // Master open detail.  You could also call node.setSelected( true ); for alternate design.
              node.setExpanded(true);
            }
          });
```

**Comment by chat-du-cheshire** [comment]
Hi, does anyone knows can I select row silently? I mean without emiting rowSelected event.

**Comment by PWDrew** [comment]
setSelected has a third argument, suppressFinishActions, that unhelpfully this is not mentioned in the API docs. If you set this to true, it will not issue callbacks after AG grid has handled selection.

So you can do 
`    event.api.forEachNode((node: any) => {
      const nodeIsSelected = setOfSelectedNodes.has(node.data.path);
      
      if (node.isSelected() !== nodeIsSelected) {
        node.setSelected(nodeIsSelected, false, true);
      }
    });`

**Comment by caglarsarikaya** [comment]
aggrid on ready function is not proper for this transact. agon ready just drawing table if you want manipulate data you have to approach before ag ready. but there is no option for this.if you add this code on your methods. 
```
getProducts: async function() {
      let data = await repository.getAll("Product").then(r => r.list);
      for (let i = 0; i < this.value.length; i++) {
        for (let j = 0; j < data.length; j++) {
          if (this.value[i].productId == data[j].productId) {
            let x = data.splice(j, 1)[0];
            data.unshift(x);
            break;
          }
        }
      }
      this.productDataForAggrid = data;
      this.gridApi.setRowData(this.productDataForAggrid);
      window.watcher = setInterval(this.setSelectedItems, 50, this.gridApi);
    }
```
this function is normal get method except last part. İf you selected some rows on ag and if you close ag all selection will deleted on the table but you stıll have which data selected on your data property when you openin ag again. You will fallow this way.this part of code for real ready function i mean before preparation of data. 

```
setSelectedItems(api) {
      if (this.productDataForAggrid.length == api.getDisplayedRowCount()) {
        for (let i = 0; i < this.value.length; i++) {
          let node = api.getRowNode(this.value[i].productId.toString());
          if (node) {
            node.setSelected(true);
          }
        }
        this.gridApi.sizeColumnsToFit();
        clearInterval(window.watcher);
        window.watcher = 0;
        //console.log("ready!");
      }
    }
```

firstly we will add all selected data on value prop for adding to billing list. But if customer wants to reopen product select aggrid again customer cant see the selected products. This getproducts func work for everytime on ag open. and getting all products. compare this data with our value property. and sending to setSelectedItems funciton for check selected.
```

 saveSelectedProducts() {
      this.value.splice(0, this.value.length);
      for (var i = 0; i < this.gridOptions.api.getSelectedRows().length; i++) {
        if (this.gridOptions.api.getSelectedRows()[i].sellPrice === undefined)
          this.gridOptions.api.getSelectedRows()[
            i
          ].sellPrice = this.gridOptions.api.getSelectedRows()[i].odooId;

        if (this.gridOptions.api.getSelectedRows()[i].piece === undefined)
          this.gridOptions.api.getSelectedRows()[i].piece = 1;

        this.value.push(this.gridOptions.api.getSelectedRows()[i]);
      }
      //this.$emit("selectedProductsList", this.value);
      this.openProductPopup = false;
    },
```
