### ISSUE TITLE
Grid height minimises after new data has been assigned.

### ISSUE THREAD

**Issue by vivektodi** [ceolter/angular-grid#384]
When I fetch my data after the grid has been drawn and then assign the data using: 

``` javascript
$scope.gridOptions.rowData = dataList;
$scope.gridOptions.api.onNewRows();
```

The grid shows only a scrollable single row.
Like this:
![screen shot 2015-08-18 at 4 48 01 pm](https://cloud.githubusercontent.com/assets/1806863/9328760/3f1e7424-45c9-11e5-9320-b31c2735f1df.png)

Where as it should have looked like,
![screen shot 2015-08-18 at 4 50 57 pm](https://cloud.githubusercontent.com/assets/1806863/9328768/5647194e-45c9-11e5-8e11-baf3937921bf.png)

This issue exists in all versions ahead of 1.7

**Comment by ceolter** [comment]
sounds like your don't have a height specified in your grid. specify a height on the div element where you have ag-grid directive.

**Comment by vivektodi** [comment]
We cannot do that everywhere since we are using it to implement grids which expand on their own as and when the user enters data from outside.

Would we have to handle that on our own? If yes, could you guide us?

**Comment by ceolter** [comment]
Yes you would. ag-grid is designed to use the space you give it. it is not designed to expand automatically depending on the size of the rows. if you want to do this, you will need to control the height of your grid div.

**Comment by vivektodi** [comment]
Oh but, it used to work like this till 1.7 is there some change after that?

**Comment by ceolter** [comment]
yes it was introduced on purpose to support pluggable panels (such as the tool panel). going forward, more pluggable panels will be introduced. this meant the grid needs to have a known height to lay out the panels. the fact it was working before was not an intended feature, just happened to work that way.

**Comment by vivektodi** [comment]
Alright! Thank you! We'll take care of this from now then!
