### ISSUE TITLE
Properties "colId" and "field" are used inconsistently when getting / setting the filter model.

### ISSUE THREAD

**Issue by jkorrek** [ceolter/angular-grid#385]
Hi there,

after upgrading to the latest version, I noticed that, when calling the getFilterModel() function, I receive information based on the columns "field" property.
However, calling the setFilterModel will only work, when the filter information is using the "colId" property of the column. I think this is to a recent change to the getColumn function of the ColumnController - before it was matching columns by "field" - not its using "colId".

As I am working with grids using two dimensional arrays as data, "colId" and "field" are not the same for my columns.

It would be nice if you could take a look at this. Thanks!

**Comment by ceolter** [comment]
the colId is calculated as follows:
```
            if (colDef.colId) {
                this.colId = colDef.colId;
            } else if (colDef.field) {
                this.colId = colDef.field;
            } else {
                this.colId = '' + Column.colIdSequence++;
            }

```

in other words, if you don't provide a colId in your colDef, it will then use the field. if the field is also missing, an id will be generated.

knowing this, is it still a problem??

**Comment by jkorrek** [comment]
Thanks for the quick response - let me try to clarify my problem.

I'm setting both the field and the colId in the column configuration, for example
field: '0' and colId': 'code'
As I mentioned I'm working with two dimensional arrays as data - therefore I use the colId to specifiy a meaningful name for the column.

Now when calling getFilterModel, I get:
```
{
  "0" : { 
   //filterModel
  }
}
```

Calling setFilterModel with the same object won't work, I have to use the following object:
```
{
  "code" : { 
   //filterModel
  }
}
```

As far as I can tell getFilterModel uses the columns field property. However setFilterModel needs the columns colId to work properly.

**Comment by ceolter** [comment]
they should both be using the colIds - in case field is not unique. let me check . . .

**Comment by ceolter** [comment]
i checked in a fix. now col-id is used consistently everywhere.

using field was legacy, before i introduced col-id. col-id is unique, field may not be.

**Comment by jkorrek** [comment]
Nice, thanks for your help!
