### ISSUE TITLE
css collision in tool panel messes with display

### ISSUE THREAD

**Issue by bdougherty1** [ceolter/angular-grid#386]
When mixed with the nvd3 graphing package, 		

<link rel="stylesheet" href="packages/nvd3/angular-nvd3-0.0.3/lib/nv.d3.min.css">

there is a css collision that makes the tool panel bullet circles become as tall and wide as the tool panel itself because the inherited style width is set to 100%. 

This can be corrected by forcing the svg style width, height, and display like so:

            else {
                eSvg.setAttribute("width", "10");
                eSvg.setAttribute("height", "10");
>>> NEW >>>                eSvg.setAttribute("style", "width : 10px; height : 10px; display : inline");
            }

**Comment by ceolter** [comment]
i am already giving width and height on all the generated svg's. can you advise further??

code from svgFactory.ts is:
```
    function createIconSvg(width?: any) {
        var eSvg = document.createElementNS(SVG_NS, "svg");
        if (width > 0) {
            eSvg.setAttribute("width", width);
            eSvg.setAttribute("height", width);
        } else {
            eSvg.setAttribute("width", "10");
            eSvg.setAttribute("height", "10");
        }
        return eSvg;
    }
```

**Comment by bdougherty1** [comment]
Hi,
     I'm not well versed in this stuff so forgive the poor explanation, but when looking at the svg element containing the circle in the inspector in firefox it showed that it was inheriting display=block and width=100% from the graphing package css. As you say, the height=10 and width=10 were set on your svg element, but the style element seems to override those settings.  I ended up with the column name 170px down from the svg circle for each column heading. If I force the 10x10 and inline with a local style setting, it displays as intended. There may be a better way to avoid the css collision, but the local setting from javascript worked.

    When I remove the graph package css file from my page, there are no width or display css elements associated with the svg element in the selector and the column name does display properly adjacent to the svg circle. Then of course, the graphs do not display properly.

     If you include this css file in your demo example, you should reproduce the problemhttps://github.com/krispo/angular-nvd3/blob/master/lib/nv.d3.min.css

Thanks. 


     On Tuesday, August 18, 2015 10:37 AM, Niall Crosby <notifications@github.com> wrote:
   
 

 i am already giving width and height on all the generated svg's. can you advise further??code from svgFactory.ts is:    function createIconSvg(width?: any) {
        var eSvg = document.createElementNS(SVG_NS, "svg");
        if (width > 0) {
            eSvg.setAttribute("width", width);
            eSvg.setAttribute("height", width);
        } else {
            eSvg.setAttribute("width", "10");
            eSvg.setAttribute("height", "10");
        }
        return eSvg;
    }

**Comment by ceolter** [comment]
that is totally the fault of the nvd3

what you can do to get around it is put the following style in AFTER you include the nvd3 styles:
```
        <style>
            svg {
                width: auto;
                height: auto;
                display: inline-block;
            }
        </style>
```

but the problem is with nvd3. they are applying a style to EVERY svg element. that's just silly and how clashes happen. please raise this on their github project!!!
