### ISSUE TITLE
found a bug in setFocusedCell function

### ISSUE THREAD

**Issue by matrixl** [ceolter/angular-grid#387]
rowRenderer.ts

        // called via API
        public setFocusedCell(rowIndex: any, colIndex: any) {
            var renderedRow = this.renderedRows[rowIndex];
            var column = this.columnModel.getDisplayedColumns()[colIndex];
            if (renderedRow && column) {
                //var eCell = renderedRow.getCellForCol(column.colId);
                // should be replace to 
                var eCell = renderedRow.getCellForCol(column);
                this.focusCell(eCell, rowIndex, colIndex, column.colDef, true);
            }
        }

**Comment by ceolter** [comment]
thanks. fixed.
