### ISSUE TITLE
caught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by kobiv** [ceolter/angular-grid#388]
I am trying to use a virtual paging process while getting the data for every 1000 new rows from indexdb

i get the following errors caught TypeError: Cannot read property 'destroy' of undefined , the rows are not destroyed they are just added to the grids so when we are doing virtual paging we are adding more and more rows

  gridOptions = {
    columnDefs: this.columnDefs,
    virtualPaging: true,
    pageSize: 30,
    maxPagesInCache: 1
  };

      var dataSource = {
        pageSize: 30,
        maxPagesInCache: 3,
        maxConcurrentRequests: 1,
        rowCount: null, //???- not setting the row count, infinite paging will be used
        overflowSize: 50,
        getRows: function(params) {
          console.time("ag grid paging");
          console.log('asking for ' + params.startRow + ' to ' + params.endRow);
          var lastRow = -1;
          var offset = bindingContext.currentPage * bindingContext.pageSize;

          if (bindingContext.pageSize <= params.endRow - offset) {
            //var page = Math.floor(params.endRow/bindingContext.pageSize);
            bindingContext.currentPage++;
            bindingContext.GetData(bindingContext.BindGrid);
          }

          params.successCallback(bindingContext.GlobalCache.data.slice(params.startRow - offset,        
          params.endRow - offset), lastRow);
          console.timeEnd("ag grid paging");
        }
      }

**Comment by ceolter** [comment]
i put your datasource settings into my example here:
http://localhost:8082/angular-grid-virtual-paging/index.php

and it was working fine.

can you give me more information so i can recreate the problem?

any chance you can provide a plunker or fiddle?

**Comment by kobiv** [comment]
hey i created a plunker it took some time

but it is an aurelia based plunker 

http://run.plnkr.co/plunks/ymskxzpyh5NqmC7eCFq4/#/grid

try scrolling and you see the error

**Comment by ceolter** [comment]
can you give me a link to the plunker where i can see the code?

**Comment by kobiv** [comment]
http://plnkr.co/edit/zoGl6a?p=preview

here it is i use a minified file you can change it yourself .

**Comment by ceolter** [comment]
when i put in the un-minified code, i get the error:
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Payload content length greater than maximum allowed: 1048576"
}
```
which makes it impossible for me to troubleshoot :(

**Comment by kobiv** [comment]
use this line in grid.js

instead of import 'angular-grid'
use 
import 'https://raw.githubusercontent.com/ceolter/angular-grid/master/dist/angular-grid.js'
works well

**Comment by ceolter** [comment]
The problem is your datasource. You should NOT call params.successCallback() in the same thread. It is intended that you will call successCallback() asynchronously.

```
getRows: function(params) {
          console.time("ag grid paging");
          console.log('asking for ' + params.startRow + ' to ' + params.endRow);
          var lastRow = -1;
          var offset = bindingContext.currentPage * bindingContext.pageSize;

          if (bindingContext.pageSize <= params.endRow - offset) {
            //var page = Math.floor(params.endRow/bindingContext.pageSize);
            bindingContext.currentPage++;
            bindingContext.GetData(bindingContext.BindGrid);
          }

          // this is the problem - if you are not going to do so async HTTP call to get the data,
          // then you need to at least put it into a timeout.
          params.successCallback(bindingContext.GlobalCache.data.slice(params.startRow - offset, params.endRow - offset), lastRow);
          console.timeEnd("ag grid paging");
        }
```

**Comment by kobiv** [comment]
the issue is not related always to the call back after scrolling 100 or 120 items the error appears
after 1000 items i do the call back so it is not related please check again

**Comment by ceolter** [comment]
have you fixed the above?

**Comment by kobiv** [comment]
i removed the async call to the indexdb 
but the error still prevails  , please check it

**Comment by ceolter** [comment]
I am now on  holidays without my laptop, afraid it will have to wait :( am back Tuesday.

**Comment by DeepikaSohani** [comment]
How was the issue resolved?
