### ISSUE TITLE
changing rowData

### ISSUE THREAD

**Issue by rweng** [ceolter/angular-grid#390]
I guess I am blind, but is there something special I need to do when updating the rowData array? When I do `gridOptions.rowData.push({id: 1})` the new row is not display, calling `gridOptions.api.refreshView()` doesn't change that.

Can anyone help? Looked through all examples but can't find one that adds rows. Thanks!

**Comment by rweng** [comment]
nevermind, `gridOptions.api.onNewRows()` does the trick :)

**Comment by danwf** [comment]
Noob here. Having this same issue and it looks like onNewRows() is no longer a function. Wat do??

**Comment by ceolter** [comment]
onNewRows() was replaced with setRowData();

**Comment by Bhawna14** [comment]
is setRowData(); replaced with any new method. As i am not finding this method in the api?
![error](https://user-images.githubusercontent.com/12491471/27587395-da99ab26-5b61-11e7-82ca-b2e94488046d.PNG)
