### ISSUE TITLE
Filter menu and field name with dot

### ISSUE THREAD

**Issue by S-YOU** [ceolter/angular-grid#391]
When field name contains dot (nested objects), filter menu only show "(Blanks)".

Is that supposed to work, or am I missing something? Let me know if you need more info.

Thank you

**Comment by ceolter** [comment]
dots in field name not supported. if you need 'embedded' fields, then use valueGetter and expressions.

**Comment by S-YOU** [comment]
ok, thank you

**Comment by goodies4uall** [comment]
What if you do not have 'embedded' fields but rather just column names with dots in them like (Parent.Name)? It still is showing blanks even though row data has "Parent.Name" property with values.

**Comment by ceolter** [comment]
@goodies4uall user property suppressFieldDotNotation use the dots as part of the name

**Comment by iwangbowen** [comment]
> @goodies4uall user property suppressFieldDotNotation use the dots as part of the name

Thanks a lot
