### ISSUE TITLE
Multi-selection is not as expected

### ISSUE THREAD

**Issue by amcdnl** [ceolter/angular-grid#4]
When I set to multi select, when clicking a new row i would expect it to deselect the previous one.  Perhaps, checkboxes would be a ideal solution for this too?

**Comment by ceolter** [comment]
Multi select is just that, so don't expect it to deselect. That's what
single select a s for!

Yea agreed with check box selection. On my to do list.

**Comment by amcdnl** [comment]
Ya, I understand :) 

My thought process was explorer / finder style multi select where you use keyboard to select them.
