### ISSUE TITLE
Number filter - doing less equal and not strict less

### ISSUE THREAD

**Issue by chiptus** [ceolter/angular-grid#403]
When I have a number column and I add the filter:"number" to it's definition, doing greater than or less then is doing a weak comparison, e.g if i'm looking for all number less than 0 I get also 0.
I think there should also strict less and greater than.
I'll try and look into the code and give you a pull request, just wanted to let you know.

Thanks

**Comment by ceolter** [comment]
it's doing 'less than' and not 'less than or equal to', et:

this is the code:
```
            switch (this.filterType) {
                case EQUALS:
                    return valueAsNumber === this.filterNumber;
                case LESS_THAN:
                    return valueAsNumber < this.filterNumber;
                case GREATER_THAN:
                    return valueAsNumber > this.filterNumber;
                default:
                    // should never happen
                    console.warn('invalid filter type ' + this.filterType);
                    return false;
            }
```

**Comment by chiptus** [comment]
I guess I had an old version, I'll update my js. thanks

**Comment by ceolter** [comment]
makes sense, this was something i fixed about 6 weeks ago.
