### ISSUE TITLE
Data Ordering is wrong in version 1.9.2, but size of the grid is the best -- is there a simple fix I can apply?

### ISSUE THREAD

**Issue by dereklin** [ceolter/angular-grid#404]
Hi,  I am still stuck at 1.9.2 because the size of the grid is most stable in that version.  For newer versions, when I load the grid again, the size becomes smaller.

However, in version 1.9.2, when there are more than 10 items in the data array, the order of the array is not honored in the grid.  This seems to be the only problem I am facing with 1.9.2.  Could you please point me to right place to fix the ordering problem?

Thanks.

**Comment by ceolter** [comment]
> For newer versions, when I load the grid again, the size becomes smaller.

This is your problem. If that gets fixed, then you can come to the latest version? What do you mean by the size becomes smaller? Sounds like you are having issues sizing your div.

PS This isn't an issue with the grid, so closing it. The best place for questions and help is on the forum :)
