### ISSUE TITLE
FR: Please allow CSS class parameter to column header cells

### ISSUE THREAD

**Issue by scotthovestadt** [ceolter/angular-grid#405]
I need to target the column header cells and there is no non-hacky way of doing it right now.

**Comment by S-YOU** [comment]
headerClass?

**Comment by ceolter** [comment]
yes use headerClass - it's undocumented (i've fixed that, will be in the docs of the next release).

put this on your colDef. works same as cellClass (ie provide a string (class), and array of strings (and array of classes), or a function that returns a string or array of strings).
