### ISSUE TITLE
Only append v_elements to DOM that can see under viewport?

### ISSUE THREAD

**Issue by S-YOU** [ceolter/angular-grid#406]
As you can see, v_elements is more than 2x in DOM than that you can see on viewport.

![2015-08-28 19 58 15](https://cloud.githubusercontent.com/assets/1001175/9544887/473ddfac-4dbf-11e5-9fa3-787211c9af4b.png)

Is there any way to improve it, just to render what you can see on screen?
Since you have grid height fixed, and cell height fixed, I think its possible.

**Comment by ceolter** [comment]
rowBuffer in gridOptions tells how many rows past the viewable area to render. set this to a lower number to get what you want.

**Comment by S-YOU** [comment]
thanks for the rowBuffer option, didn't know that there is a settable option.
