### ISSUE TITLE
Multiple Pivot items

### ISSUE THREAD

**Issue by S-YOU** [ceolter/angular-grid#411]
Not sure this is supported features or proper way to use, but just for the information.

![pivot-1](https://cloud.githubusercontent.com/assets/1001175/9571481/f144cb08-4fd8-11e5-89bc-bb557a1fccca.png)

When you choose drag items into pivot area, and some errors throws and have blank rows in grid.

**Comment by ceolter** [comment]
fixed now. thanks.

**Comment by S-YOU** [comment]
:thumbsup:
