### ISSUE TITLE
Error loading angular-grid when running PhantomJS (e.g. for unit tests)

### ISSUE THREAD

**Issue by russell-miller** [ceolter/angular-grid#420]
When I have angular-grid 1.14.1 installed into my project I am unable to run my project's unit tests via PhantomJS because of the following error:

```
TypeError: 'undefined' is not a function (evaluating 'this.stopDragging.bind(this)')
```

A simple way to reproduce this error is:
```
$ npm install -g phantomjs
$ phantomjs dist/angular-grid.js
```

This appears to relate to https://github.com/ceolter/angular-grid/blob/06ec095705d963ed261dae854a32408e45fc1a0c/src/ts/dragAndDrop/dragAndDropService.ts#L22

I'm unable to reproduce this error when using angular-grid in a browser. Also, I can't tell from looking at the code *why* the error is occurring.

**Comment by ceolter** [comment]
PhantomJS at fault, it doesn't have the bind method. This can be fixed by including a poly for the bind method.

fyi
http://www.angulargrid.com/forum/showthread.php?tid=2516
