### ISSUE TITLE
[Bug or Feature Request] Tool Panel - cannot remove pivoted columns

### ISSUE THREAD

**Issue by milesburton** [ceolter/angular-grid#427]
Good day,

I'm not sure if it was intended as such but once you select you're pivoted columns/values you are no longer able to remove them again.

I can't see any documentation which would let a user drag a column back to the "column" section. 

I think it would also make sense that if a user pivots on a column, that column is removed from the "columns" pane.

Let me know what you think

**Comment by ceolter** [comment]
> let a user drag a column back to the "column" section

there is an 'x' beside the column name in the pivot section, you click this to take it out.

yes the pivot, and tool panel, in general, there is so much more i can do there. i intend doing a massive 'push' on it at some point, but there is a lot of work involved and i've other stuff to get in before i do 'tool panel version 2'.
