### ISSUE TITLE
Remove column from tool panel column chooser

### ISSUE THREAD

**Issue by a497988** [ceolter/angular-grid#428]
I am wondering if it is possible to have a column NOT appear in the column show/hide section of the tool panel? I want to be able to create a checkbox column and allow a user to use that for selections, but not allow them to re-position it within the grid. I was wondering if this was a possible feature?

**Comment by ceolter** [comment]
already requested
https://github.com/ceolter/angular-grid/issues/340

it's all in the plan, but unfortunately i've a day job :(
