### ISSUE TITLE
Multiple Columns Edit

### ISSUE THREAD

**Issue by axelex** [ceolter/angular-grid#433]
Hi, 
I've had a quick look on the grid documentation and didn't see anything about multiple columns editing and I wanted to ask you if this functionality doesn't exist or if it's available but I just didn't saw it.

Thanks!

**Comment by ceolter** [comment]
with the built in editing, you can only edit one cell at a time.

if you want more than this, for now (i may implement something in the future), then you need to create this functionality yourself using the cellRenderers.
