### ISSUE TITLE
Documentation update....

### ISSUE THREAD

**Issue by cgat** [ceolter/angular-grid#438]
The Floating Rows documentation page has:

     // no rows to float to start with
     floatingHeaderRowData: [],
     floatingFooterRowData: []

In the grid options. "Header" should be replaced by "Top" and "Footer" replaced by "Bottom". The example still works because these aren't use to actually set the floating rows, but it threw me off when I copied and pasted this options.

**Comment by ceolter** [comment]
cool, thank you.

i've updated it in github, will be updated online when i do the next release.
