### ISSUE TITLE
angularCompile as a option in column def

### ISSUE THREAD

**Issue by bidiboom** [ceolter/angular-grid#441]
Hello

is it possible to have an angularCompile option at the column definition level ? I have some use case where it's not really interesting to have angular compile at row level because of the number of columns and it is much more interesting to have at column level in order to use a directive in the first column for example.

**Comment by S-YOU** [comment]
in my understanding, you only have one new shared scope for every columns in a row, so having scope in different columns won't be different from performance side in my opinion.

**Comment by ceolter** [comment]
not possible. the compiling is done when the entire row is created. as s-you says, the child scope is created for the row, so there would be no gain in having it done multiple times for different columns.

**Comment by bidiboom** [comment]
ok, thanks for you explanations!
