### ISSUE TITLE
[FEAT] Totalizer row

### ISSUE THREAD

**Issue by lukelalo** [ceolter/angular-grid#45]
Hi, 

It would be great to have a totalizer row, which shows the aggregate data of all rows, like this:

![angulargrid-totalizer](https://cloud.githubusercontent.com/assets/4819263/7002773/4c89fa80-dc50-11e4-8e66-9f5a481bdf01.png)

Regards
Pablo García

**Comment by ceolter** [comment]
Yea I agree. That would be a floating row . . . it would be good to have
floating rows at top and bottom which display whatever data you give, or
have a built in option of showing totals.

**Comment by amcdnl** [comment]
pinned rows? maybe like this? http://handsontable.com/demo/fixed.html

**Comment by tannerlinsley** [comment]
@amcdnl That grid really is the most intense thing I've ever seen haha.

**Comment by amcdnl** [comment]
I dont know @ceolter is starting to rival it.

**Comment by vinnytheviking** [comment]
+1.  We're switching to your grid at the moment and require this feature.

I'm trying to figure out a workaround at the moment so, any ideas welcomed.

Vinny

**Comment by ceolter** [comment]
Yes it's a common feature request. It will be in in a few weeks. I don't
have a workaround, apart from having a separate table below the main one,
but then the scrolls will be out of sync.

On 22 April 2015 at 04:55, vinnytheviking <notifications@github.com> wrote:

> +1. We're switching to your grid at the moment and require this feature.
>
> I'm trying to figure out a workaround at the moment so, any ideas welcomed.
>
> Vinny
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/45#issuecomment-95020302>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by z-boy** [comment]
+1. I would also love to see such a feasture as I understand it as a common feature of table implementations.

**Comment by ceolter** [comment]
i guess this could work almost like the header currently works, except it displays something different, and doesn't need to sort / filter / re-size etc . . .

**Comment by vivektodi** [comment]
Makes sense to have this. +1

**Comment by cgat** [comment]
I've found a bit of a work around. If you group on an invalid key, a single top level group will form. By utilizing the groupInnerCellRenderer function, you can customize the name of the invalid key group to show whatever you want (ie 'Totals', "All", etc).

**Comment by AdamEwing1849** [comment]
Hi @ceolter ,
We've implemented your awesome grid, many thanks for that.
Any updates on `totalizer row` feature? Is it still in your to-do list?
This function is crucial for us and we would appreciate any rough estimation how long it will take.
Thank you in advance!

**Comment by devfxplayer** [comment]
please implement!

**Comment by ceolter** [comment]
only so much i can do, i'm working flat out on the grid, this isn't top of my list :(

**Comment by devfxplayer** [comment]
Can you delegate this to me?
On 1 Jul 2015 18:31, Niall Crosby <notifications@github.com> wrote:only so much i can do, i'm working flat out on the grid, this isn't top of my list :(

**Comment by ceolter** [comment]
will think about it!!!!!

problem is, that getting this in is a big change, and design decisions need to be done. because i have ideas on where i'm pushing things, i'm slow to get peoples help without them sitting beside me to discuss designs with :(

**Comment by ataft** [comment]
ag grid is so much more than handsontable. mini-excel-in-the-browser is a totally different thing...

agreed with everyone here that this is a very important feature of grids. i think it would be a mistake to think of it as a separate table and think that @ceolter got it right with "i guess this could work almost like the header currently works, except it displays something different, and doesn't need to sort / filter / re-size etc . . ".  the only addition would be that it should use the groupAggFunction to aggregate and the cell renderer to format the same as the other cells.

**Comment by ShwetShah** [comment]
Superb grid! we are using it with all functionalities it provides. 

Now, we on stage where we strongly need Total / Sum / Aggregate values in Footer row which would not scrolled out with grid scroll bar. I already been through all the post related to this point. Would like to request you to guide me to workout some way for this or request you to put this point for your this week while you are working on github issues.

Thanks very much

Shwet

**Comment by ceolter** [comment]
> request you to put this point for your this week while you are working on github issues

you funny!!!! i'm afraid, given this is open source, and lots and lots of users, i try not to listen to individual requests, especially if they are large ones!!!! unless of course there is money in the equation, that persuades me!!

anyway, you might be in luck, i'm working on something very similar that will achieve what you want. i'm going to have the ability to 'lock' a grid onto another grid (not sure the naming yet), so the second table will minic the columns of the first. so you can have the second table directly below the first table acting as a footer, and the columns and scrolls will all be synced up. then just hide the header on the second table (so only one column header). that's the plan, and i need this for my own job, so very good chance it will be in soon.

as for a specific 'footers' as you request, that wont be in this weekend. just not enough hours outside my day job to do it :(

**Comment by vinnytheviking** [comment]
Hi @ceolter 

Thanks for looking into this. The functionality to lock a grid into another could be a good interim solution to having a global footer.

I look forward to seeing how you implement this. 

Keep us posted.

Vinny

**Comment by a497988** [comment]
Hi @ceolter Just wondering if there is any update on the expected timeline for the 'grid-lock' to be finished? It is exactly what I need right now, and instead of trying to create a weird work around I was hoping this would be done soon.

**Comment by ceolter** [comment]
i was meant to have it done last weekend, but didn't get it finished. it's the current thing i'm working on in work (when i'm not doing team lead stuff), so i hope to get it done this week.

**Comment by a497988** [comment]
Thank you for the update, do you think it would be possible to let me know when you do the push of this code? I am going to be away for work for the next week, but can pass this along to my colleague once I know it is complete for him to look at.

Thanks again for this add-on!

**Comment by ceolter** [comment]
when it's up, i'll comment on this thread. it's actually already 'half' there, as i released today my latest, which has the first pass. you can see my example here:
https://github.com/ceolter/angular-grid/tree/master/docs/angular-grid-lock

so far i've the column sizing working (keeping two grids column sizes in sync). i've to complete the other parts (scroll, column group open / close etc). also no guarantee that the design won't change.

**Comment by ceolter** [comment]
@a497988 I have now pushed this code. The feature is called "Master / Slave Grids" and can be used to provide floating footers. I've given an example of floating footers also. Will be in the next release, or you can get / build the latest yourself.

**Comment by a497988** [comment]
@ceolter Thank you! Do you know when the next release will be?

**Comment by ceolter** [comment]
@a497988 i did a release last weekend.

**Comment by a497988** [comment]
@ceolter I noticed in the examples online that the horizontal scroll does not work for both grids as it says it should, nor does the column show/hide. Is there something I might be missing in the examples that are included in the documentation?

**Comment by ceolter** [comment]
just checked and it's working for me. i went to the online example with chrome, IE and firefox (all windows 8).

**Comment by ataft** [comment]
thanks for this feature, it's a great improvement over the footer that I hacked into my grid.  i'm wondering if there's any thought about adding an option for "showTotalizer" on the master that would not require a slave grid to be configured separately?  it seems that there is a lot of necessary code in order to create a summary footer when it could just use the configuration from the master.  as it stands, one has to duplicate their logic for aggregation, figure out how to update totals when the master grid data is updated, rebuild it when grouping is changed, and so on.  maybe i'm wrong, but i would think that most users of angular-grid would want a footer summary on most/all grids they create.

if this is not in the works, how would i go about updating the footer summaries when filters are applied?  also, what's the best way to rebuild the grid when the groups change?

**Comment by ceolter** [comment]
the master / slave is meant for so much more than just footers - that's just one application of them. i intend going back and adding headers and footers as a separate feature. but because master / slave allows footers (albeit, as you say, with to much coding required), the pressure is off me to provide the nice easy footers.



> how would i go about updating the footer summaries when filters are applied

gridOptions.modelUpdated -	Function callback, gets called when displayed rows have changed. Happens following sort, filter or tree expand / collapse events.



> what's the best way to rebuild the grid when the groups change?

if your changing the gridOptions.groupKeys, then you need to call onNewRows()

or you can use the columnController (undocumented right now, intend making it public this weekend), something link this:
```
var columnController = gridOptions.api.getColumnController();
var columns = columnController.getAllColumns();
var col = getTheColWeWantToPivotBy(columns);
columnController.addPivotColumn(col);
```
the grid listens for change events on the column controller and will rebuild when it gets the event of a pivot change.

**Comment by lukelalo** [comment]
Wow, nice work. Thanks!!! :+1:

**Comment by dctdct** [comment]
So can we use the "easy footers"? Total sum row would be so nice!!

**Comment by murali424** [comment]
Hi @ceolter 

Could you please provide an example of displaying grand totals for numeric columns?

The github link you've provided in the above comments does not exist:
[https://github.com/ceolter/angular-grid/tree/master/docs/angular-grid-lock](https://github.com/ceolter/angular-grid/tree/master/docs/angular-grid-lock)

**Comment by eazybit** [comment]
> when it's up, i'll comment on this thread. it's actually already 'half' there, as i released today my latest, which has the first pass. you can see my example here:
> https://github.com/ceolter/angular-grid/tree/master/docs/angular-grid-lock
> 
> so far i've the column sizing working (keeping two grids column sizes in sync). i've to complete the other parts (scroll, column group open / close etc). also no guarantee that the design won't change.

This link doesn't work. Returns 404

**Comment by Maharramoff** [comment]
After long hours of effort, I found a solution for myself. Maybe it will help someone else. [Total Footer Row #1791](https://github.com/ag-grid/ag-grid/issues/1791)
https://codepen.io/Maharramoff/pen/NEEpyq

**Comment by howlettt** [comment]
For anyone looking for an example of the total row:
https://www.ag-grid.com/javascript-grid-aligned-grids/#aligned-grid-as-footer

**Comment by xenouk** [comment]
https://www.ag-grid.com/javascript-grid-aligned-grids/#aligned-grid-as-footer is basically 2 grids stack together. Sounds good but doesn't work on most cases. 

Total Footer is also useless because you cant export the values and you have to scroll down to see the values too.
