### ISSUE TITLE
Editable column does not redraw the checkbox after editing

### ISSUE THREAD

**Issue by jdcaballerov** [ceolter/angular-grid#48]
Hi,

I just noticed that when using a column as editable, that uses a checkbox for selection, after editing the field the checkbox is not redraw.

Please take a look at the example http://www.angulargrid.com/example.html 

1. Select Editable Yes.
2. Edit the Name column.

You will notice the checkbox is not redraw

regard,

**Comment by ceolter** [comment]
Thanks for creating the issue. This is on my list.

**Comment by ceolter** [comment]
This is now fixed.
