### ISSUE TITLE
Bower name is already registered.

### ISSUE THREAD

**Issue by tannerlinsley** [ceolter/angular-grid#49]
If I'm not mistaken, I think angular-grid is already registered to ng-grid/ui-grid here: https://github.com/angular-ui/ng-grid. I suggest finding a unique bower name, and registering in the bower registry.
http://bower.io/docs/creating-packages/#register

**Comment by tannerlinsley** [comment]
If you'd registered it as another name, be sure to update the bower.json file

**Comment by davidgeary** [comment]
I think you'll find that ng-grid is registered as `angular-ui-grid`, rather than `angular-grid`.

I have both installed in a single project for evaluation and bower had no problem installing them side by side.

**Comment by ceolter** [comment]
My intention was:

published to bower as ag-grid (angular-grid already taken in bower) and
angular-grid in npm

Sounds like I need to update my package.json.....

**Comment by ceolter** [comment]
I meant, bower.json! I've updated now and checked in, bower.json now references ag-grid. This issue good to close?
