### ISSUE TITLE
[FEAT] Pagination

### ISSUE THREAD

**Issue by amcdnl** [ceolter/angular-grid#5]
Virtual/Infinite scrolling is awesome but sometimes you need to give perspective to where you are at in the actual page structure so a user can leave and come back and easily find the item they were viewing.

I've implemented something like this on https://github.com/Swimlane/ng-table but I'd love to work with you to integrate this into your grid to make the ultimate grid! :)

**Comment by ceolter** [comment]
Interesting. Am in pub at the mo. Will check out ng-table over the weekend.

Where you based??

**Comment by amcdnl** [comment]
The demo doesn't work that great but you can review the code.  I'm working on getting it better but i use it internally fine.  

It has jqueryui dependency i'd love to remove and has some missing features and it can be slowish sometimes hints why interested in your project. 

The really cool thing about it is its directive driven!

I'm based in South Florida US

**Comment by ceolter** [comment]
Ah Florida, I am 5 or 6 hours ahead of you in London!!

**Comment by ppneo** [comment]
Hi, ceolter ! I have checked your “Angular Grid”， It is greate! but the example does not have "Client side Pagination"??   which I think is  the basic functions of a grid.  I hope that I can found this function soon.   Now I'm trying it...

**Comment by ceolter** [comment]
Hi Ppneo, this feature isn't in yet, on my to do list. However the grid can handle very large data sets (tested up to 100k rows), why do you need pagination, why not load everything into the GUI and allow user to filter?

**Comment by amcdnl** [comment]
@ceolter I'm not sure throwing 100k is a good suggestion, maybe should give a demonstration on how to server side page based on scroll position and grid height.

**Comment by ceolter** [comment]
lazy loading of rows based on scroll wasn't something i had in mind, grid doesn't support it :( . . . . but am curious what the use case is for paging - if your report has more than 1000 rows, then the user is not going to go through each row of the report, typically they would filter / search / aggregate (either in the client or the server). my gut feeling is paging is from old-style applications, where you couldn't handle large data sets in the client. one of the strong points of angular grid is you can manage large datasets, and filter / aggregate you way through it!

**Comment by amcdnl** [comment]
I think @ceolter sees the light after our discussion on gitter ;)

**Comment by sheymann** [comment]
+1

**Comment by sequoiar** [comment]
+1

**Comment by hjzheng** [comment]
+1

**Comment by ionut-tanasa** [comment]
+9001

(:D)

**Comment by ceolter** [comment]
it's coming it's coming!!!

**Comment by nelreina** [comment]
I am with you ceolter. I don't see the point for pagination neither

**Comment by ceolter** [comment]
Yeay!!!! At least one other person agrees with me!!!!

Unfortunately (for me!!) I'm still having to implement it, even if I'm
never going to use it myself!!!

I have the core of pagination and infinite scrolling working now, I'm just
patching it all up before merging into trunk. Will probably be in this
weekend.


On 11 April 2015 at 16:34, nelreina <notifications@github.com> wrote:

> I am with you ceolter. I don't see the point for pagination neither
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/5#issuecomment-91869935>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by sheymann** [comment]
@ceolter I'll give you a use case:

Fill in the table with results coming from a paginated search (e.g. using ElasticSearch), because you hell don't want to load large bulks of data. In general, pagination is recommended for goal-oriented finding tasks.

Sources:
- http://www.nngroup.com/articles/infinite-scrolling/
- http://ux.stackexchange.com/questions/15982/regular-pagination-vs-infinite-scroll
- http://ux.stackexchange.com/questions/33406/infinite-scroll-vs-pagination-in-e-commerce-websites

Don't also forget that providing an infinite scroll feature is more difficult than what you think, because it's not "just" infinite scrolling but also much more features to make it usable:

- http://blog.adrianroselli.com/2014/05/so-you-think-you-built-good-infinite.html

**Comment by ceolter** [comment]
so-you-think-you-built-good-infinite
<http://blog.adrianroselli.com/2014/05/so-you-think-you-built-good-infinite.html>
.
. . . . just read!!! . . . . mostly concerned about scrolling a webpage
though, not a grid.

funny, everyone else just asked for pagination, you asked for the best one
in the world!!!!

baby steps, baby steps, give my first iteration a try when it's ready :)

On 11 April 2015 at 17:37, Sébastien Heymann <notifications@github.com>
wrote:

> @ceolter <https://github.com/ceolter> I'll give you a use case:
>
> Fill in the table with results coming from a paginated search (e.g. using
> ElasticSearch), because you hell don't want to load large bulks of data. In
> general, pagination is recommended for goal-oriented finding tasks.
>
> Sources:
>
>    - http://www.nngroup.com/articles/infinite-scrolling/
>    -
>    http://ux.stackexchange.com/questions/15982/regular-pagination-vs-infinite-scroll
>    -
>    http://ux.stackexchange.com/questions/33406/infinite-scroll-vs-pagination-in-e-commerce-websites
>
> Don't also forget that providing an infinite scroll feature is more
> difficult than what you think, because it's not "just" infinite scrolling
> but also much more features to make it usable:
>
>    -
>    http://blog.adrianroselli.com/2014/05/so-you-think-you-built-good-infinite.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/5#issuecomment-91877238>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by sheymann** [comment]
@ceolter I can't wait for it ;)

**Comment by ceolter** [comment]
ok pagination and infinite scrolling is in! going to leave this issue open, i'm sure am going to get hammered with "you forgot this and that", so please just add to this about how i did it wrong rather than raising new issues!!!!!

**Comment by ceolter** [comment]
no feedback . . . . . :( . . . . . might have to close the issue . . . . .
