### ISSUE TITLE
Move styles to external file

### ISSUE THREAD

**Issue by tannerlinsley** [ceolter/angular-grid#51]
Styles are very hard to customize and manage in their current state.  The build scripting looks pretty crazy, and it also looks like they are all combined and injected as a style tag in the head in the end, making overrides cumbersome and at the mercy of script execution sequence.

Ideally, keeping all of the css files in the organization you have them in `src` would make them easier to customize/override/improve. 

The core styles for layout and functionality could be in a required `angular-grid.css` file, and the themess as optional files eg. `angular-grid-fresh-theme.css` would make theming a snap.

**Comment by ceolter** [comment]
this is tied in with the use of requirejs - how it's done is the requirejs
way. however going forward, may be moving away from requirejs to something
more modern, maybe commonjs (and browersify) or ecma 6 modules.

On 10 April 2015 at 23:08, Tanner Linsley <notifications@github.com> wrote:

> Styles are very hard to customize and manage in their current state. The
> build scripting looks pretty crazy, and it also looks like they are
> injected as a style tag in the head in the end, making overrides cumbersome
> and at the mercy of script execution sequence.
>
> Ideally, moving the core styles for layout and functionality out to a angular-grid.css
> file would make them easier to customize/override/improve. Then extracting
> the themes out into their own files eg.angular-grid-fresh-theme.css`
> would make theming a snap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/51>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by tannerlinsley** [comment]
Fixed by #69
