### ISSUE TITLE
Contributions & more widely supported build and development environment

### ISSUE THREAD

**Issue by tannerlinsley** [ceolter/angular-grid#53]
So far, I'm confused on how to make a build or contribute to this repo.  We should definitely get things switched over to a gulp build and more standard build and test tools.

**Comment by ceolter** [comment]
Fair point. It's just a matter of time before I get onto 'making a better
build' - it's the way it is now as I didn't intend this project to shared
when I was starting out - so I did what was quickest for me to get things
done. Right now I want to get all the paging stuff done (that's where my
brain is at), I'll take a step back after that, might be a good time to
move towards gulp, and maybe away from requirejs while at it.

**Comment by davidgeary** [comment]
+1 for gulp

As for contributions, presumably a pull request from the contributor's fork is the obvious way?

**Comment by tannerlinsley** [comment]
Absolutely. We need to work up a contributors guide. One of the best I've
seen and is that of chart.js
https://github.com/nnnick/Chart.js/blob/master/CONTRIBUTING.md

**Comment by tannerlinsley** [comment]
Fixed by #69
