### ISSUE TITLE
state version inside js

### ISSUE THREAD

**Issue by chiptus** [ceolter/angular-grid#60]
Hi,

Great module! I'm just starting to integrate it into my app, hoping that it will go smooth.
Can you please state the version number on the top of the js file? It confuses me when I don't know if I should upgrade or if i have the latest...

Thanks!

**Comment by ceolter** [comment]
Sure, makes sense.

**Comment by ceolter** [comment]
Done. Now js has the following (for example) at the top:

// Angular Grid
// Written by Niall Crosby
// www.angulargrid.com
//
// Version 1.4-SNAPSHOT
