### ISSUE TITLE
[FEAT] Selection API improvements

### ISSUE THREAD

**Issue by pauljoey** [ceolter/angular-grid#63]
Would like an option `keepLastSelected` that would allow de-selection of the selected row in "single" selection mode when the selected row is clicked.

**Comment by ceolter** [comment]
Makes sense.

**Comment by pauljoey** [comment]
Changed topic from "Option to allow de-selection of rows" to "Selection API improvements"

1. Add: `keepLastSelected` option that would allow de-selection of the selected row in "single" selection mode when the selected row is clicked.
2. Add: `api.getSelectionIndices()` to get indices of current selections. This would allow `api.selectIndex()` to be used externally to implement a previous/next functionality.
3. Add: `api.selectRow(input)` to select a row based on `row.data === input`, or alternatively `input(row) === true` if `input` is a function

**Comment by ceolter** [comment]
Agreed.

On 16 April 2015 at 23:37, Paul <notifications@github.com> wrote:

> Changed topic from "Option to allow de-selection of rows" to "Selection
> API improvements"
>
>    1. Add: keepLastSelected option that would allow de-selection of the
>    selected row in "single" selection mode when the selected row is clicked.
>    2. Add: api.getSelectionIndices() to get indices of current
>    selections. This would allow api.selectIndex() to be used externally
>    to implement a previous/next functionality.
>    3. Add: api.selectRow(input) to select a row based on row.data ===
>    input, or alternatively input(row) === true if input is a function
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/63#issuecomment-93854718>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
I've updated the API, now has the following methods:
```
selectIndex(index, tryMulti, suppressEvents)
deselectIndex(index)
selectNode(node, tryMulti, suppressEvents)
deselectNode(node)
isNodeSelected(node)
getSelectedNodes()
```
The selection is node based, not data or index based, the index is there just to help the rows, as they know which index they are rendering.

So instead of getting the selected indexes, you should get the selected nodes.

With the above methods, can you now do what you need to do?

I think what's missing, that  you need, is a way to get:
1) a list of all nodes??? (maybe not)
2) a way to map from a) index to node and b) node to index

Plus the 'allow deselection' option - i haven't forgotton about that.

**Comment by pauljoey** [comment]
Thanks for the quick turn around. We have two behaviours that we need that I am trying to implement at the application level (keeping in mind that we use infinite scrolling). This is the main impetus for the feature request, though I can easily foresee a broad range of use cases that would need to read and modify selections externally. For us, presently, we need to:

 - Select previous/next row
 - Change the selection externally and update the row selection accordingly

Given that `node` is mainly an internal data representation specific to angular-grid it may ultimately be preferable (in an ideal world located in a vacuum) to construct the "final" API (down the road) in such a way that it avoids its use. Having said that, I understand that it may not be possible to provide a sufficient degree of control to demanding power users with one-off use-cases such as myself :) Thus the simplest and most effective approach to covering the broadest possible use-cases may very well be to simply expose the internal functions.  

So far I'm really pleased with angular-grid. A solid API will make the project extendable and help keep  the core simple and focused. Keep up the good work.

Had a look at the recent patch, had a few thoughts: 

`getSelectedNodes()` appears to be missing a return statement :)
`selectedNodesById` seems to retain extra keys after de-selection by setting the values to `delete this.selectedNodesById[node.id]` instead of calling `delete this.selectedNodesById[node.id]` in  `deselectRealNode()`. Can this be changed or do other parts of the code rely on this behaviour?

**Comment by ceolter** [comment]
Re the bugs, how embarrassing!!! (especially the first one)

I've just fixed these two and checked them in. Thanks for pointing them out.

Regarding the selection by node query - the reason for using the node, and
not the data, for selection, is when you get into groups, there is no data
equivalent for the group row. Another reason is that the grid is not
dependent on any key within the data (where as the node has an id) - which
is needed for selection - as object equality cannot be used when paging /
virtual scrolling as the row may exist many times as the page in question
is reloaded. And then don't forget that not all rows will have an index, if
the row is within a group that is now expanded.

I'd prefer keeping the selection node focused underneath the hood. If we
had the lookup of node based on index, and index based on node, wouldn't
that solve your problem??? (assuming the node is loaded into memory).


On 17 April 2015 at 18:07, Paul <notifications@github.com> wrote:

> Thanks for the quick turn around. We have two behaviours that we need that
> I am trying to implement at the application level (keeping in mind that we
> use infinite scrolling). This is the main impetus for the feature request,
> though I can easily foresee a broad range of use cases that would need to
> read and modify selections externally. For us, presently, we need to:
>
>    - Select previous/next row
>    - Change the selection externally and update the row selection
>    accordingly
>
> Given that node is mainly an internal data representation specific to
> angular-grid it may ultimately be preferable (in an ideal world located in
> a vacuum) to construct the "final" API (down the road) in such a way that
> it avoids its use. Having said that, I understand that it may not be
> possible to provide a sufficient degree of control to demanding power users
> with one-off use-cases such as myself :) Thus the simplest and most
> effective approach to covering the broadest possible use-cases may very
> well be to simply expose the internal functions.
>
> So far I'm really pleased with angular-grid. A solid API will make the
> project extendable and help keep the core simple and focused. Keep up the
> good work.
>
> Had a look at the recent patch, had a few thoughts:
>
> getSelectedNodes() appears to be missing a return statement :)
> selectedNodesById seems to retain extra keys after de-selection by
> setting the values to delete this.selectedNodesById[node.id] instead of
> calling delete this.selectedNodesById[node.id] in deselectRealNode(). Can
> this be changed or do other parts of the code rely on this behaviour?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/63#issuecomment-94028636>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
@pauljoey regarding knowing the selected indexes, when doing virtual paging (and only when doing virtual paging), then the node id is in fact the row index. Hope this info helps you out!

**Comment by ceolter** [comment]
1. deselect row is implemented. Now, if gridOptions.rowDeselection=true, you can deselect rows with ctrl+click.
2. New callback for iterating through each row in memory. See the selection documentation example using forEachInMemory.

Converting between nodes and indexes is just messy, because as mentioned above, not every row has an index (due to grouping and pagination). Using forEachInMemory I believe will solve your problems. So am closing this issue!

All above I'll be releasing in 1.7.0 later today.

**Comment by germanger** [comment]
Is there a way to make multiselection and deselection with just click and no "ctrl+click" ?

**Comment by ceolter** [comment]
```
Is there a way to make multiselection and deselection with just click and no "ctrl+click" 
```
only if you use checkbox selection
