### ISSUE TITLE
How to handle filtering with infinite scroll

### ISSUE THREAD

**Issue by bkirk1012** [ceolter/angular-grid#64]
Hello,

I am working on using Angular Grid for a particular feature where I will send the grid a large amount of data from a server call. If infinite scrolling is in place, I need a way for the grid to be able to filter on my entire data set, not just rows 1-1000, for example. When using other grid libraries, I implemented this by setting up the filter options through running a specific query to return the filter options for that specific column. I tried this methodology within Angular Grid using the customs filter, yet was unsuccessful in writing the getGui function (the html i sent the function was not able to recognize my data variables.

Any suggestions on how I should proceed?

Thank you!

-Billy

**Comment by ceolter** [comment]
Hi Billy,

So what you want is table with infinite scroll and:

1) Load data (first page) into grid.
2) Set filter on a col.
3) Load data again, this time using the filter.

Is this correct?

**Comment by bkirk1012** [comment]
Yes - to add more detail: 

1) Load data (first page) into grid. - first page sent from the server
2) Set filter on a col - have the filter be representative of my entire data set, not just the first page sent from the server
3) Load data again, this time using the filter. -Say I select two options from the filter: one item was loaded through the first page, and one item was not (due to the infinite scroll) so that item would remain on the server.  The filter would still need to know that second item was on the server, even though it was not loaded initially.  Selecting the two options would then load the data appropriately.

**Comment by ceolter** [comment]
Is the set of options fixed? Or do you need to find out from the server?

**Comment by bkirk1012** [comment]
The set of options would be fixed, and the data would need to come from the server.

I want to avoid re-implementing the default 'Set' filter, but I need to retrieve all the possible filter options from the server even if all the data for the grid is not sent - if that makes sense

**Comment by ceolter** [comment]
ok - so two parts to this.

first part i will be implementing soon, which is providing the set filter with a set of values. so you can give it values, for example, A, B, C and D. then regardless of what your data has, these values will be always present in your filter. if these are fixed, you can just provide them. if they are not fixed, then you will have to query the server yourself and provide them to the grid before the grid is created.

with regards the second part, sending the filter to the server with the query, i that will take me longer to implement. i can't estimate how long  . . . . maybe 3 or 4 weeks from now.

in the mean time, the only thing you can do is have a filter outside of the grid that provides the options to the user.

**Comment by bkirk1012** [comment]
The first part would be awesome! Do you have an idea of when this would be implemented?

Also, thank you for the quick/helpful responses.

**Comment by ceolter** [comment]
first part i will probably do over the weekend!!!

**Comment by pauljoey** [comment]
We handle sorting and filtering on the server side by constructing a custom URL that is referenced by the datasource that we construct and manipulate outside of angular-grid. The only issue that we ran into was in clearing the data when the criteria changes - for this we discovered that calling `options.api.setDatasource()`(even with the same data source) has the desired effect.

**Comment by ceolter** [comment]
"for this we discovered that calling options.api.setDatasource()(even with the same data source) has the desired effect."

yes that's right - i intended it to work that way. your safe to do that.

or there is another method options.api.onNewDatasource() (doesn't take a parameter) to inform the grid that the datasource is 'new'.

internally, when either of the above are called, the grid knows to 'reset' the datasource.

**Comment by nsang92** [comment]
+1

**Comment by raciel88p** [comment]
You can use this library to page view, it will track your content url and it will appear in your google analytics.

https://github.com/googleanalytics/autotrack
