### ISSUE TITLE
[FEAT] Force fill column widths

### ISSUE THREAD

**Issue by amcdnl** [ceolter/angular-grid#7]
The ability to determine if the total column widths are < than the width of the grid, it would be nice to fill the columns to equal the grid width.  http://www.screencast.com/t/DLuA5bQWzhO

Ember table supports this:
http://addepar.github.io/ember-table/#/ember-table/documentation

So does my grid:
https://github.com/Swimlane/angular-table/blob/master/src/table.js#L96

The tricky part is dealing with when a user resizes a column after a force fill but then resizes the table to be greater than the widths again ;)

**Comment by ceolter** [comment]
Agreed a feature to put in. Btw - check out the 'no scrolls' option. This
achieves something similar.

On 8 March 2015 at 02:28, Austin <notifications@github.com> wrote:

> The ability to determine if the total column widths are < than the width
> of the grid, it would be nice to fill the columns to equal the grid width.
> http://www.screencast.com/t/DLuA5bQWzhO
>
> Ember table supports this:
> http://addepar.github.io/ember-table/#/ember-table/documentation
>
> So does my grid:
> https://github.com/Swimlane/angular-table/blob/master/src/table.js#L96
>
> The tricky part is dealing with when a user resizes a column after a force
> fill but then resizes the table to be greater than the widths again ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/7>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by ceolter** [comment]
Just checked your screencast now - coincidentally I updated the sample table earlier with my 'no scrolls' feature - take a look at my updated website! - if only a few rows, the 'no scrolls' works very well.

**Comment by ceolter** [comment]
I implemted this last week :)

**Comment by dvrakas** [comment]
Where  is the "No Scroll" option.

**Comment by S-YOU** [comment]
@dvrakas, I think its was called `dontUseScrolls` and after 2.0 it is called `forPrint`

**Comment by S-YOU** [comment]
@dvrakas, may be its was called dontUseScrolls and after 2.0 it is called forPrint
http://rawgit.com/S-YOU/ag-docs/master/1.10.0/angular-grid-no-scrolls/index.php.html
