### ISSUE TITLE
init table from click does not work

### ISSUE THREAD

**Issue by consigliory** [ceolter/angular-grid#82]
this is simple demo you have
    // body...
        $scope.columnDefs = [
        {displayName: "Make", field: "make"},
        {displayName: "Model", field: "model"},
        {displayName: "Price", field: "price"}
    ];

    $scope.rowData = [
        {make: "Toyota", model: "Celica", price: 35000},
        {make: "Ford", model: "Mondeo", price: 32000},
        {make: "Porsche", model: "Boxter", price: 72000}
    ];

    $scope.gridOptions = {
        columnDefs: $scope.columnDefs,
        rowData: $scope.rowData,
        dontUseScrolls: true // because so little data, no need to use scroll bars
    };
if move it into function then it does not work anymore 

var module = angular.module("example", ["angularGrid"]);

module.controller("exampleCtrl", function($scope) {

$scope.showgrid = function (argument) {
    console.log('init table');
    // body...
        $scope.columnDefs = [
        {displayName: "Make", field: "make"},
        {displayName: "Model", field: "model"},
        {displayName: "Price", field: "price"}
    ];

    $scope.rowData = [
        {make: "Toyota", model: "Celica", price: 35000},
        {make: "Ford", model: "Mondeo", price: 32000},
        {make: "Porsche", model: "Boxter", price: 72000}
    ];

    $scope.gridOptions = {
        columnDefs: $scope.columnDefs,
        rowData: $scope.rowData,
        dontUseScrolls: true // because so little data, no need to use scroll bars
    };
}

});
function on click is called but no table generated.

**Comment by ceolter** [comment]
That's not a bug, the grid options needs to be present on the scope when the grid is created. The correct thing to do, if you don't have the grid ready, is to either a) create an empty gridOptions or b) put a ng-if on the grid div, that way, angular will not create the directive until after your data is ready.

eg of B is:

'''
<div angular-grid='gridOptions' ng-if='gridOptions'/>
'''

**Comment by consigliory** [comment]
what about dynamic columns? once it populated with columns and data is it possible to change columns?!

**Comment by consigliory** [comment]
all is fine. thanks for great work and quick respose!

**Comment by Abhinay1235** [comment]
`api, columnApi` are not generated for the $cope.gridOptions. The `$scope.gridOptions` is created with below structure when seen in console.log.

```
Object {columnDefs: Array[27], rowData: Array[50]}
columnDefs: Array[27]
rowData: Array[50]
__proto__: Object
```

Here api, columnApi are missing. i dont know why they are not generated.

My HTML is
`<div ag-grid="gridOptions" ng-if="gridOptions" class="ag-fresh" style="height: 700px;width:100%;display:block;">&nbsp;</div>`

and my JS is
`            $scope.gridOptions = {
                columnDefs: tableHeaders,
                rowData: tableData
            };`
**tableHeaders,tableData** are arrays with data 
this Js is called in a function using a button click.

**Comment by ceolter** [comment]
all i can say is there must be something wrong in your code. the gridOptions defiantly gets the api and columnApi attached to it - otherwise the thousands of people using the grid would be complaining.

**Comment by Abhinay1235** [comment]
Yes @ceolter , It was a initialization problem. I fount it. Thank you.
