### ISSUE TITLE
Server side filtering and sorting

### ISSUE THREAD

**Issue by vanthiyathevan** [ceolter/angular-grid#84]
Is there a way to achieve this? I'm thinking the `getRows` function in the datasource can be extended to include the filter and sorting parameters

**Comment by ceolter** [comment]
yes that's right, my plan is to do exactly that. there is a chunk of coding i need to get it in, but it's on my list.

**Comment by TravisTX** [comment]
Is there any known work-around for this currently?

**Comment by ceolter** [comment]
only way currently is to implement this outside of the grid. when a new sort or filter is applied, then call onNewDatasource (you don't have to provide a new one, just pretend to the grid that it has changed). The datasource should then refer to the external sort / filter that was selected.
