### ISSUE TITLE
UI issue when using Column Pinning.

### ISSUE THREAD

**Issue by vivektodi** [ceolter/angular-grid#89]
I found this while using column pinning. A small rectangular section appears on top of the last row, covering half of the data value of the pinned columns. Please refer the screenshot.

![screen shot 2015-04-24 at 3 42 45 pm](https://cloud.githubusercontent.com/assets/1806863/7316902/c72615f2-ea98-11e4-89ad-5b54824bf98b.png)

**Comment by lukelalo** [comment]
This is a dup of #35

**Comment by ceolter** [comment]
yup it's a dupe, i know what's going on here, will be fixed soon
