### ISSUE TITLE
create API for filtering

### ISSUE THREAD

**Issue by ceolter** [ceolter/angular-grid#93]
should be able to query and set the filter through the API

**Comment by bgauvey** [comment]
I can definitely use this.  Any projected dates yet?

**Comment by ceolter** [comment]
From now, about 4 to 6 weeks.

**Comment by psalaberria002** [comment]
Nice feature ;) Is there any solution meanwhile for saving the state of the filters (and sorting) in local storage or cookies?

**Comment by ceolter** [comment]
@psalaberria002  - nope, no way to store state of filters currently. sorry :(

**Comment by bgauvey** [comment]
just pulled 1.7.0.  looks great!  Is there a getCurrentFilters type of function so that we can save the current filters?

**Comment by TMJones** [comment]
Thanks Niall.

On Sat, Apr 25, 2015 at 10:36 AM, Niall Crosby <notifications@github.com>
wrote:

> should be able to query and set the filter through the API
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/angular-grid/issues/93>.
>



-- 
Timothy M. Jones
Life Science Annex Building, Room A257
Louisiana State University
Baton Rouge, LA 70803
Website - http://www.herbarium.lsu.edu/keys/

**Comment by ceolter** [comment]
@bgauvey . . . . hmmmm, something like getModel() and setModel(model) on each filter, , , , , and then getAllFilterModels() to return an object (not an array) of all the filters mapping colDef.field to filterModel . . . that sort of thing? and then a setAllFilterModels(models)?

**Comment by ceolter** [comment]
included in 1.8.0
