### ISSUE TITLE
Support multi-column sorting

### ISSUE THREAD

**Issue by sfescape** [ceolter/angular-grid#98]
Extend sorting to multi-column by allowing the selection of additional sort columns with shift-click.

**Comment by ceolter** [comment]
Fair enough :)

**Comment by ceolter** [comment]
In latest release.

**Comment by sfescape** [comment]
Thanks!

**Comment by semko2m** [comment]
Dear Celoter,
I am using your grid. I use the custom header. How can I get sorting number, on multi sorting? Do you have API for that? 

Kind Regards
